### ISSUE TITLE
Samung Phones MediaLibraryService throws ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by BejanCorneliu** [androidx/media#820] opened 2023-11-17 13:45 UTC
### Version

Media3 1.1.1

### More version details

api 'androidx.media3:media3-ui:1.2.0'
api 'androidx.media3:media3-exoplayer:1.2.0'
api 'androidx.media3:media3-exoplayer-hls:1.2.0'
api 'androidx.media3:media3-exoplayer-dash:1.2.0'
api 'androidx.media3:media3-exoplayer-ima:1.2.0'
api 'androidx.media3:media3-cast:1.2.0'
api 'androidx.media3:media3-session:1.2.0'

### Devices that reproduce the issue

From Firebase Crashlitycs only :
Samsung (Galaxy S22 Ultra, S22+, S20+, S22 Ultra, S20+, S23 Ultra)
Phone that i do not have

### Devices that do not reproduce the issue

Phones that i have tested : Samsung S21, Pixel 8, Motorola 

### Reproducible in the demo app?

No

### Reproduction steps

I suppose when player start playing music. It's happened on some samsung devices as firebase crashlytics report

### Expected result

No crash and no need for custom notification

I'm using MediaSessionService started in foreground using SessionToken(nInterface.getActivity(), ComponentName(nInterface.getActivity(), PlayerService::class.java))

Inside my service implementation i use ExoPlayer (androidx.media3:media3-exoplayer:1.2.0 ) and MediaSession.Builder for media3 notification with control. No extra custom notification implementation.

onForegroundServiceStartNotAllowedException listener does not trigger on any of my phone. I suppose default media3 notification should be enough

I can paste code if needed with my MediaSessionService implementation

### Actual result

Playback crash with : 
- Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
- android.app.ForegroundServiceDidNotStartInTimeException - Context.startForegroundService() did not then call Service.startForeground()

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment] 2023-11-17 14:01
Duplicate of #167

Please check whether you have implemented playback resumption correctly ([docs](https://developer.android.com/guide/topics/media/session/mediasessionservice#resumption)) specifically if you add the media button receiver, you have to implement the callback.

If this does not help please comment in the other issue and add a stack trace from Crashlytics.

**Closed by marcbaechinger** 2023-11-17 14:01 UTC
Labels: bug, needs triage
