### ISSUE TITLE
Attach sample demo APK to GitHub tags

### ISSUE THREAD

**Issue by vanniktech** [androidx/media#215] opened 2022-11-29 15:13 UTC
Attach the sample demo to the Github Tags. It would be beneficial if the sample APK would be attached to a release like: https://github.com/androidx/media/releases/tag/1.0.0-beta03 that way you could download the APK and test the behavior and see if the issue reproduces also in the sample app.

**Comment by rohitjoins** [comment] 2022-11-29 17:10
Duplicate of [#1920](https://github.com/google/ExoPlayer/issues/1920)

Here is the link to our [documentation](https://exoplayer.dev/demo-application.html) on how to build/use our demo apps.

**Closed as completed by rohitjoins** 2022-11-29 17:10 UTC
Labels: enhancement

**Comment by vanniktech** [comment] 2022-11-29 19:15
I know how to build it, it's just that I haven't cloned the repository and neither have I probably downloaded all of the depenendencies that are used, plus building does take quite a long time. So it'll probably take 10-15 minutes and having a downloading option beats that in every single case.

Any chance you can reconsider?

**Comment by marcbaechinger** [comment] 2022-11-29 20:31
An idea would be to consider to make sure that the gradle build tasks for the demo app are well-known and documented/self-explanatory. Then it is easy to make something like this for devs:

```
git clone https://github.com/androidx/media.git
cd media/
export ANDROID_HOME=~/Android/Sdk/
./gradlew :demo:assembleNoDecoderExtensionsDebug
adb install demos/main/buildout/outputs/apk/noDecoderExtensions/debug/demo-noDecoderExtensions-debug.apk
rm -rf media/
```

Agreed you still need to have the SDK installed but when downloading the APK you need `adb` or something as well for installing.

I suggest, we could add something like this to the [demo app page](https://exoplayer.dev/demo-application.html) of the developer guide. With this we enable developers and everyone can quickly get the demo app, customize the gradle build command or checkout the `main` branch.
