### ISSUE TITLE
NoSuchMethodError on Amazon AFTT

### ISSUE THREAD

**Issue by gkoeglbauer** [androidx/media#1394] opened 2024-05-24 07:24 UTC
### Version

Media3 1.3.1

### Devices that reproduce the issue

Amazon AFTT (Fire OS 5.2.9.5)

### Reproducible in the demo app?

Not tested

### Reproduction steps

Start Playback

### Expected result

Stream is playing

### Actual result

App crashes

### Media

![NoSuchMethodError](https://github.com/androidx/media/assets/12326049/c35acaa1-ae85-455b-b2da-b168d2d58034)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by gkoeglbauer** [comment] 2024-05-24 07:28
Hello,

i got a Problem as shown in the Image above. This Problem does not occur with all Forms of Media. 

We are Playing Movies in our App which i can not provide because of legal reasons.

Seems that this Function is only usable from Android 7 and upwards.

Is there anything i can do about this?

**Comment by marcbaechinger** [comment] 2024-05-24 09:08
Duplicate of #1312.

**Closed by marcbaechinger** 2024-05-24 09:08 UTC
Labels: bug, needs triage
