### ISSUE TITLE
The exoplayer is in a paused state, the surface has been released. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error 

### ISSUE THREAD

**Issue by captain81** [androidx/media#699] opened 2023-10-05 03:30 UTC
The exoplayer is in a paused state, and the surface has been released at this time. ExoPlayer will still dequeue input buffer and output buffer from modiacodec. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error, then 
 playback error. Please tell me how to solve this problem

**Comment by microkatz** [comment] 2023-10-05 09:55
Duplicate of #698 and so closing this one.

**Closed by microkatz** 2023-10-05 09:55 UTC
Labels: question, needs triage
