### ISSUE TITLE
Next track doesn't play when skip silence is enabled

### ISSUE THREAD

**Issue by vfsfitvnm** [androidx/media#207] opened 2022-11-13 18:08 UTC
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

-

### Reproducible in the demo app?

Yes

### Reproduction steps

1 - Clone https://github.com/vfsfitvnm/media.git
2 - Launch app
3 - Play _Genre folder > Jazz & Blues > Jazz In Paris_
4 - Let it play or seek to the end
5 - The next track (_The Messenger_) won't play

From my understanding, it only occurs when silence skipping is enabled and the `minimumSilenceDurationUs` is higher than the silence occurring at the end of the song.

### Expected result

The media plays successfully

### Actual result

The media doesn't play

### Media

-

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-11-18 15:08
I can reproduce the problem you describe using the 1.0.0-beta02 release (in fact it looks like from the UI that the next track starts, but never advances past 3s, every time it gets there it jumps back to the beginning).

I tried reproducing on the tip of the main branch and it doesn't repro - so I suspect it's been fixed and should be fixed in the next release.

**Closed by icbaker** 2022-11-18 15:08 UTC
Labels: bug, needs triage

**Comment by vfsfitvnm** [comment] 2022-12-09 14:50
Although I cannot reproduce in the demo app after upgrading to `1.0.0-beta03`, I can still reproduce in my application, unfortunately. Let's see if I can set up a reproducible example in the demo app.
