### ISSUE TITLE
No Class Def Found Error

### ISSUE THREAD

**Issue by joh9911** [androidx/media#632] opened 2023-09-02 12:34 UTC
### Version

Media3 1.1.1

### Devices that reproduce the issue

Android 5,

Android 6

### Reproducible in the demo app?

No

### Reproduction steps

I put the initialize code into onCreate method in MediaSessionService.

`

override fun onCreate() {
        super.onCreate()

        exoPlayer = ExoPlayer.Builder(this)
            .setAudioAttributes(AudioAttributes.Builder()
                .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                .setUsage(C.USAGE_MEDIA)
                .build(), true)
            .setHandleAudioBecomingNoisy(true)
            .build()
        exoPlayer.playWhenReady = true
        addListener()

        val customCallback = CustomMediaSessionCallback()
        mediaSession = MediaSession.Builder(this, exoPlayer)
            .setCallback(customCallback)
            .build()

        mediaSession?.setCustomLayout(createCommandButton())
        val notificationIntent = Intent(this, Activity::class.java)
        val pendingIntent = PendingIntent.getActivity(applicationContext, 0, notificationIntent, PendingIntent.FLAG_IMMUTABLE)
        mediaSession?.setSessionActivity(pendingIntent)
    }
`

### Expected result

.

### Actual result

Fatal Exception: java.lang.NoClassDefFoundError
androidx.media3.exoplayer.ExoPlayer$Builder$$ExternalSyntheticLambda17
androidx.media3.exoplayer.ExoPlayer$Builder.<init> (ExoPlayer.java:543)
com.myFile.transpose.service.MediaService.onCreate (MediaService.kt:54)
android.app.ActivityThread.handleCreateService (ActivityThread.java:3692)
android.app.ActivityThread.access$2000 (ActivityThread.java:219)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1818)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6939)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

### Media

.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2023-09-04 08:54
Duplicate of https://github.com/google/ExoPlayer/issues/10602

**Closed by icbaker** 2023-09-04 08:54 UTC
Labels: bug, needs triage

**Comment by joh9911** [comment] 2023-09-06 01:00
I don't use any Guava Library, do I have to add it `implementation 'com.google.guava:guava:30.1-android'` ?
