### ISSUE TITLE
SessionCommand equals ignores the extras

### ISSUE THREAD

**Issue by JureSencar** [androidx/media#556] opened 2023-08-01 18:18 UTC
### Version

Media3 1.1.0

### Reproduction steps

Set the same command with different extras bundle via `mediaSession.setAvailableCommands()`.

### Expected result

`onAvailableSessionCommandsChanged` in `MediaBrowser.Listener` fires with the updated commands.

### Actual result

The event `onAvailableSessionCommandsChanged` in `MediaBrowser.Listener` does not fire.

The reason is that the `SessionCommand::equals` ignores the `extras` bundle.
https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/session/src/main/java/androidx/media3/session/SessionCommand.java#L161-L167

**Comment by rohitjoins** [comment] 2023-08-03 19:46
Hi @JureSencar,

`SessionCommand` utilizes `Bundleable` for lazy loading of properties. We can safely apply equals to `extras` only when we are certain of its type, which is not the case here. Pulling remote lazy properties just for the purpose of equals is unnecessary.

You should do a different custom command with a different action instead of differentiating with extras only.

**Comment by rohitjoins** [comment] 2023-08-04 09:46
I'm closing this issue as it is an intended behaviour. Please feel free to reopen this issue if you have any further questions. Thanks!

**Closed by rohitjoins** 2023-08-04 09:46 UTC
Labels: wont fix: intended behavior
