### ISSUE TITLE
Media includes audio tracks, but none are playable by this device Problem

### ISSUE THREAD

**Issue by Devloperimran** [androidx/media#825] opened 2023-11-19 10:03 UTC
Video is play,but show this error  
```
 if (tracks.containsType(C.TRACK_TYPE_AUDIO)
                    && !tracks.isTypeSupported(C.TRACK_TYPE_AUDIO, /* allowExceedsCapabilities= */ true)) {
                showToast(R.string.error_unsupported_audio);
            }
```

```
public class MainActivity extends AppCompatActivity {
    @Nullable
    ExoPlayer player;
    @Nullable
    PlayerView playerView;
    private @Nullable Tracks lastSeenTracks;
    String ur = "https://ddy4.hlsjs.ru/ddy4/premium61/tracks-v1a1/mono.m3u8";
    String referer = "https://weblivehdplay.ru/";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        playerView = findViewById(R.id.player_view);
        SetPlayer();
    }

    private void SetPlayer() {

        ExoPlayer.Builder playerBuilder = new ExoPlayer
                .Builder(this)
                .setMediaSourceFactory(new DefaultMediaSourceFactory(this)
                        .setDataSourceFactory(dataSourceFactory())
                );
        MediaItem mediaItem = MediaItem.fromUri(Uri.parse(ur));
        player = playerBuilder.build();
        player.setMediaItem(mediaItem);
        if (playerView != null) playerView.setPlayer(player);
        player.addListener(new PlayerEventListener());
        player.setPlayWhenReady(true);
        player.prepare();
        player.play();

    }

    @NonNull
    @OptIn(markerClass = UnstableApi.class)
    private DefaultHttpDataSource.Factory dataSourceFactory() {
        Map<String, String> headers = new HashMap<>();
        headers.put("Referer", referer);
        return new DefaultHttpDataSource.Factory().setUserAgent(
                "Mozilla/5.0 " +
                        "(Linux; Android 10; Pixel 4) AppleWebKit/537.36 (KHTML, like Gecko)" +
                        " Chrome/91.0.4472.120 Mobile Safari/537.36"
        ).setDefaultRequestProperties(headers);
    }

    private class PlayerEventListener implements Player.Listener {

        @Override
        public void onPlaybackStateChanged(@Player.State int playbackState) {

        }

        @Override
        public void onPlayerError(@NonNull PlaybackException error) {
            if (error.errorCode == PlaybackException.ERROR_CODE_BEHIND_LIVE_WINDOW) {
                assert player != null;
                player.seekToDefaultPosition();
                player.prepare();
            }
        }

        @Override
        @SuppressWarnings("ReferenceEquality")
        public void onTracksChanged(@NonNull Tracks tracks) {

            if (tracks == lastSeenTracks) {
                return;
            }
            if (tracks.containsType(C.TRACK_TYPE_VIDEO)
                    && !tracks.isTypeSupported(C.TRACK_TYPE_VIDEO, /* allowExceedsCapabilities= */ true)) {
                showToast(R.string.error_unsupported_video);
            }
            if (tracks.containsType(C.TRACK_TYPE_AUDIO)
                    && !tracks.isTypeSupported(C.TRACK_TYPE_AUDIO, /* allowExceedsCapabilities= */ true)) {
                showToast(R.string.error_unsupported_audio);
            }
            lastSeenTracks = tracks;
        }
    }

    private void showToast(int messageId) {
        Toast.makeText(getApplicationContext(), getString(messageId), Toast.LENGTH_LONG).show();
    }

}
```

**Comment by tianyif** [comment] 2023-11-20 10:05
Hi @Devloperimran,

With the given information, I'm hard to tell if this is a library issue, and to me it is more like an issue that the audio tracks of the content are not supported by the device, however, I was not able to reproduce it from my end as I got 403 for your URL - https://ddy4.hlsjs.ru/ddy4/premium61/tracks-v1a1/mono.m3u8. 

I'm going to close this issue for now, but you're welcome to create a new issue with more details as requested in the issue template. The issue template can be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to android-media-github@google.com with the subject `Issue #1234`. Please also update this issue to indicate you've done this.

**Closed by tianyif** 2023-11-20 10:05 UTC
Labels: question, needs triage
