### ISSUE TITLE
Demo session app crashes when  adb shell media dispatch command is executed

### ISSUE THREAD

**Issue by jpgpuyo** [androidx/media#1648] opened 2024-08-22 18:18 UTC
### Version

Media3 1.4.0

### More version details

I have detected a crash when following command is executed
``
 adb shell media dispatch pause
``

The crash is happening in demo app and it is also reproducible in version 1.4.1.

If I use the following commands, everything is working as expected:
``
adb shell media monitor androidx.media3.session.id.
``
``
pause
``

### Devices that reproduce the issue

Sony Bravia VH1 2020 (Android TV OS Version 10)

### Devices that do not reproduce the issue

I will try in more devices. 

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Open demo-session app
2. Click on Album Folder
3. Click on Mango Movie Project
4. Click on Play
5. Connect with adb
6. Execute command 
``
 adb shell media dispatch pause
``

### Expected result

Playback is paused

### Actual result

Demo session app crashes:

```
FATAL EXCEPTION: main
Process: androidx.media3.demo.session, PID: 18206
java.lang.IllegalArgumentException: packageName should be nonempty
	at androidx.media3.session.legacy.MediaSessionManager$RemoteUserInfo.<init>(MediaSessionManager.java:185)
	at androidx.media3.session.legacy.MediaSessionCompat$MediaSessionImplApi28.getCurrentControllerInfo(MediaSessionCompat.java:4616)
	at androidx.media3.session.legacy.MediaSessionCompat.getCurrentControllerInfo(MediaSessionCompat.java:862)
	at androidx.media3.session.MediaSessionLegacyStub.onMediaButtonEvent(MediaSessionLegacyStub.java:318)
	at androidx.media3.session.legacy.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1433)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

```
### Media

Album Folder -> Mango Movie Project (crash will happen in any media)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment] 2024-08-22 19:22
Thanks for your report!

The [assertion throws because the remote user info has no package name](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/legacy/MediaSessionManager.java#L185) defined that would indicate from what application or system actor the command was issued.

That's a fundamental property and having a null value is suspicious at least and for Media3 a good reason to throw and even crash I think. It's worth checking whether it is possible to set the package name to use for the controller with an adb cmd line arg. If this isn't possible, I'd say this issue is better addressed with a feature request for adb to either add such a cmd line arg, or then identify with an adb package name.

I'm closing this as intended behavior. Feel free to re-open if you know about a use case on a productive user device that requires a remote user info with a null package name to pass safely.

**Closed by marcbaechinger** 2024-08-22 19:22 UTC
Labels: wont fix: intended behavior

**Comment by jpgpuyo** [comment] 2024-09-01 12:53
Thanks a lot for your clear explanation!
