### ISSUE TITLE
How to Add subtitle files or url during playing  ?

### ISSUE THREAD

**Issue by rahuldvrn** [androidx/media#1063] opened 2024-02-04 08:15 UTC
How do you add subtitle files or URLs while playing?

it is working fine when we give the subtitle before playing.

**Comment by FongMi** [comment] 2024-02-06 02:29
Reset mediaItem again

**Comment by icbaker** [comment] 2024-02-07 18:22
Duplicate of https://github.com/google/ExoPlayer/issues/1649

**Closed by icbaker** 2024-02-07 18:22 UTC
Labels: question, needs triage
