### ISSUE TITLE
[Transformer] The color of BitmapOverlay is a little off

### ISSUE THREAD

**Issue by DeweyReed** [androidx/media#1050] opened 2024-01-30 11:05 UTC
Hi, thank you for the excellent work!

I'm using media3(1.3.0-alpha01) to add a bitmap overlay to a video. However, the resulting overlay slightly differs from the original file. For example, the blue is a little dark, and the green gets lighter. Does this problem have anything to do with [the color space](https://github.com/androidx/media/blob/03d35e3f43e4648b78ee68d8b1dc6939c16e72e1/libraries/effect/src/main/java/androidx/media3/effect/OverlayShaderProgram.java#L199)? How to solve it?

**Comment by droid-girl** [comment] 2024-01-30 11:11
Hi @DeweyReed, thank you for reporting. If it is possible, could you share the input files? Or a screenshot with the input bitmap compared with the output overlay

**Comment by DeweyReed** [comment] 2024-01-30 14:05
Thank you for replying so quickly!

Overlay image(It's a LUT image, but I'm using it as an overlay to validate my custom effect shader):

![lut](https://github.com/androidx/media/assets/32358486/d939f067-94a1-4541-af34-d61191561f11)

Result(The left is the overlay preview in Android Studio, and the right is the generated video):
![Screenshot 2024-01-30 215627](https://github.com/androidx/media/assets/32358486/3d6fb9e5-b504-4646-b571-a9a52f832d06)

The difference is subtle. You can observe the top-left corner of each grid as it's darker in the video than in the image.

I noticed the difference when I tried to apply the LUT with my custom shader program, and it had an unexpected effect.

**Comment by kleiren** [comment] 2024-02-09 11:08
I have a somewhat related issue. The result of the shaders applied through the Transformer and applied to a GLSurfaceView is different: https://github.com/androidx/media/issues/1080

Maybe the texture colors are modified when applying a shader? No idea what is happening.

**Comment by dway123** [comment] 2024-02-09 15:15
You mention that the this may have to do with the color space. What color space is your input media expecting? The input colors expected by overlays is sRGB, per the [code you linked](https://github.com/androidx/media/blob/03d35e3f43e4648b78ee68d8b1dc6939c16e72e1/libraries/effect/src/main/java/androidx/media3/effect/OverlayShaderProgram.java#L199).

Also, to make sure I'm understanding correctly, am I right that the main video's colors are correct, and the overlay is experiencing some color shift.

**Comment by DeweyReed** [comment] 2024-02-10 01:13
@dway123 The color space of my overlays is sRGB. I get bitmaps from drawable resources and use them as bitmap overlays.
I don't know if the color space is involved in this situation. After comparing the original and the output videos with a screen color picker, there seems to be a color shift, but I'm not 100% sure.

The code I use is pretty simple:

```Kotlin
Transformer.Builder(this).build().start(
    EditedMediaItem.Builder(
        MediaItem.Builder()
            .setUri(getResourceUri(R.raw.video))
            .build()
    ).setEffects(
        Effects(
            emptyList(),
            buildList {
                this += OverlayEffect(
                    ImmutableList.of(
                        BitmapOverlay.createStaticBitmapOverlay(
                            drawable(R.drawable.lut).toBitmap(),
                        ),
                    )
                )
            },
        )
    ).build(),
    File(filesDir, "output.mp4").canonicalPath
)
```

I tried to adjust `getMixColor` in `OverlayShaderProgram` because the current implementation doesn't work well for my other custom effect, but I failed this time.

**Comment by dway123** [comment] 2024-04-05 14:58
Oops sorry I missed this issue.

Does this improve if you replace [fragment_shader_transformation_sdr_oetf_es2, L71 here](https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/effect/src/main/assets/shaders/fragment_shader_transformation_sdr_oetf_es2.glsl#L71) with `return gamma22Oetf(linearColor);`?

I wonder if the issue is that we're using an incorrect color transfer for video display here

**Comment by DeweyReed** [comment] 2024-04-06 01:51
@dway123 Thanks for your response.

After changing the output color transfer to 10 using the debugging mode, there are some subtle color changes, but it's still different from the original image.

The video is an SDR video. It's a low-resolution and clipped version of [Big Buck Bunny](https://www.youtube.com/watch?v=aqz-KE-bpKQ).

I can reproduce the situation with any video. Overlaying the image mentioned above on top of the resulting video makes the difference clearer.

**Comment by dway123** [comment] 2024-04-09 16:07
Hmm thanks, I think @tof-tof is more knowledgeable about overlays, so I'll defer to them here.

**Comment by tof-tof** [comment] 2024-04-10 15:58
hmmm... we are going to undergoing a project this quarter that effects how we will process colors in the pipeline. I'll check with this image after and see if it fixes the issue.

An aside: we currently have [`DrawableOverlay`](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/effect/src/main/java/androidx/media3/effect/DrawableOverlay.java#L35) as well as BitmapOverlay, so you can input drawables directly

**Comment by DeweyReed** [comment] 2024-04-13 10:12
Hi, I created a reproducible repo. <https://github.com/DeweyReed/TransformerOverlay>

**Comment by tof-tof** [comment] 2024-04-26 11:57
Hi, thanks for the repo and your patience. I tried out your lut image with our new changes in the pipeline (moving away from linear colors in effect shaders by default and the colors look much better.
![Screenshot 2024-04-26 at 12 54 48](https://github.com/androidx/media/assets/42352357/cec545a2-fa3a-49cf-a0a5-50f93cedb5fb)

The change is still in staging, but I'll link this github issue to it so that when it is submitted you can see it on the main branch. I hope to have the changes in in time for the 1.4.0-beta01 release.

**Comment by droid-girl** [comment] 2024-05-02 15:22
@DeweyReed could you let us know when you verify, so we can close the issue

**Comment by DeweyReed** [comment] 2024-05-03 01:10
Thank you! @droid-girl 

It's better than before, but there is still a tiny difference. However, I'm unsure if it is a problem with my monitor or a lack of required modification to my code.

**Comment by droid-girl** [comment] 2024-05-09 14:26
I am closing this issue for now. Please reopen for any follow up work

**Closed by droid-girl** 2024-05-09 14:26 UTC
Labels: question, needs triage, editing

**Comment by DeweyReed** [comment] 2024-05-27 02:38
Recently, I finally found some time to continue the work on video editing. The result has been improved a lot after using `setSdrWorkingColorSpace`. I'll put my code below for anybody interested.

Thank you very much for your patience and excellent work!

```Kotlin
Transformer.Builder(this)
    .setVideoFrameProcessorFactory(
        DefaultVideoFrameProcessor.Factory.Builder()
            .setSdrWorkingColorSpace(
                DefaultVideoFrameProcessor.WORKING_COLOR_SPACE_ORIGINAL
            )
            .build()
    )
```

**Comment by yuriikonovalov** [comment] 2024-05-28 15:16
Hi @DeweyReed! Has it improved colors of a BitmapOverlay for you? I tried the same settings for VideoFrameProcessorFactory and it changed nothing for my BitmapOverlays 😐 

> Recently, I finally found some time to continue the work on video editing. The result has been improved a lot after using `setSdrWorkingColorSpace`. I'll put my code below for anybody interested.
> 
> Thank you very much for your patience and excellent work!
> 
> ```kotlin
> Transformer.Builder(this)
>     .setVideoFrameProcessorFactory(
>         DefaultVideoFrameProcessor.Factory.Builder()
>             .setSdrWorkingColorSpace(
>                 DefaultVideoFrameProcessor.WORKING_COLOR_SPACE_ORIGINAL
>             )
>             .build()
>     )
> ```

**Comment by DeweyReed** [comment] 2024-05-29 23:02
@yuriikonovalov I used a custom shader, but a BitmapOverlay made the issue more noticeable. You may want to open a new issue if the change of color spaces doesn't work.
