### ISSUE TITLE
FragmentedMp4Muxer writeSampleData  make CPU scheduling can increase significantly at a certain time

### ISSUE THREAD

**Issue by FreestyleDDCoder** [androidx/media#1706] opened 2024-09-06 12:47 UTC
hi，I used FragmentedMp4Muxer to muxer FMP4 files and found that when writing data continuously, the CPU scheduling would be high in a certain period of time. It was normal to use MediaMuxer to muxer MP4 files. I don't know if this is the problem. I hope to be able to reduce the CPU scheduling while using FragmentedMp4Muxer.
[cpu-simpleperf-trace.zip](https://github.com/user-attachments/files/16908095/cpu-simpleperf-trace.zip)
It looks like it was caused by GC.
![cpu-use40%](https://github.com/user-attachments/assets/abd2f482-fb8c-4423-8623-062e411e94f7)
CPU scheduling can increase significantly at a certain time，how to make CPU scheduling runs smoothly?

Reproduction steps:
FragmentedMp4Muxer keeps calling writeSampleData.
Version：
1.4.0-beta01
device:
Auto Qualcomm8255 
Android 14

**Comment by FreestyleDDCoder** [comment] 2024-09-06 13:05
![image](https://github.com/user-attachments/assets/bd92b229-336b-4855-83ed-7aa7b6bcf132)
When the current frame is a keyframe, there is a double foreach call...

**Comment by SheenaChhabra** [comment] 2024-09-09 10:54
Hey @FreestyleDDCoder, Thanks for reaching out.
I will give you a bit of background context here.
When you write samples continuously, muxer does not write them immediately. It keeps caching the samples and then write them in batch.
In fragmented MP4, a fragment is created after a regular interval and that is when you must be seeing CPU usage.
By default muxer will attempt to create a fragment every 2 seconds (this is not fixed as a complete GOP (group of pictures) is required to write a fragment).
You can reduce this frequency by setting the fragment duration [1] but the actual fragment duration depends on the position of I-frames as explained before.

The double loop you see is for writing all the samples of all the tracks. The first loop is for tracks and the seconds is for their samples.

Please let me know if you find something different from the expected behavior.

[1] https://developer.android.com/reference/androidx/media3/muxer/FragmentedMp4Muxer.Builder?_gl=1*piem0g*_up*MQ..*_ga*ODQwMDk1NDQuMTcyNTg3ODU2Ng..*_ga_6HH9YJMN9M*MTcyNTg3ODU2NS4xLjAuMTcyNTg3ODU2NS4wLjAuMA..#setFragmentDurationMs(long)

**Comment by FreestyleDDCoder** [comment] 2024-09-10 02:51
> Hey @FreestyleDDCoder, Thanks for reaching out. I will give you a bit of background context here. When you write samples continuously, muxer does not write them immediately. It keeps caching the samples and then write them in batch. In fragmented MP4, a fragment is created after a regular interval and that is when you must be seeing CPU usage. By default muxer will attempt to create a fragment every 2 seconds (this is not fixed as a complete GOP (group of pictures) is required to write a fragment). You can reduce this frequency by setting the fragment duration [1] but the actual fragment duration depends on the position of I-frames as explained before.
> 
> The double loop you see is for writing all the samples of all the tracks. The first loop is for tracks and the seconds is for their samples.
> 
> Please let me know if you find something different from the expected behavior.
> 
> [1] https://developer.android.com/reference/androidx/media3/muxer/FragmentedMp4Muxer.Builder?_gl=1*piem0g*_up*MQ..*_ga*ODQwMDk1NDQuMTcyNTg3ODU2Ng..*_ga_6HH9YJMN9M*MTcyNTg3ODU2NS4xLjAuMTcyNTg3ODU2NS4wLjAuMA..#setFragmentDurationMs(long)

Thanks for your reply. I understand that fragmented MP4 is implemented according to (ISO/IEC 14496-12). In createFragment, processAllTracks, createTrafBoxes, and writeMdatBox use a lot of foreach. What I want to know is whether it is possible to reuse the fragment value and increase the change of this value for each frame instead of calculating it from scratch each time. Is this possible?

**Comment by SheenaChhabra** [comment] 2024-09-10 10:23
Sorry I don't understand your point here. 
We are not doing any additional computations here.
For example, muxer receives 30 video and 30 audio samples. Now when it writes a fragment, it will run a loop on both audio and video track and will writes these samples. Now these samples will not be processed again. Next time when muxer creates a fragment, it will write the new samples that it has received.

**Comment by SheenaChhabra** [comment] 2024-09-19 17:40
Closing the issue as its working as intended. Please feel free to reopen if you find any issues.

**Closed by SheenaChhabra** 2024-09-19 17:40 UTC
Labels: question, needs triage, editing
