### ISSUE TITLE
Playback resumption service dont start

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#1009] opened 2024-01-21 20:17 UTC
```
override fun onPlaybackResumption(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
    ): ListenableFuture<MediaSession.MediaItemsWithStartPosition> {
        job?.cancel()

        val tracks = scope.async(dispatchersList.io()) {
            playbackResumptionRepository.fetchLastQueue()
        }.asCompletableFuture().get()
        lastQueue.addAll(tracks)

        val position = scope.async(dispatchersList.io()) {
            playbackResumptionRepository.fetchLastPosition()
        }.asCompletableFuture().get()

        return if (tracks.isNotEmpty() && position in 0..tracks.lastIndex) {
            playerCommunication.map(PlayerCommunicationState.PlaybackResumption(tracks, position))
            playingTrackIdCommunication.map(tracks[position].mediaId)
            trackPlaybackPositionCommunication.clearPosition()
            Futures.immediateFuture(
                MediaSession.MediaItemsWithStartPosition(
                    tracks,
                    position,
                    0
                )
            ).apply { lastQueue.clear() }
        } else Futures.immediateCancelledFuture()// super.onPlaybackResumption(mediaSession, controller)


    }
```

is it better to use Futures.immediateCancelledFuture() insted of super.onPlaybackResumption(mediaSession, controller) to reduce chanche of getting  this 

```
Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.kamancho.melisma/.player.presentation.PlayerService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3364)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
       at android.os.Parcel.createException(Parcel.java:2440)
       at android.os.Parcel.readException(Parcel.java:2423)
       at android.os.Parcel.readException(Parcel.java:2365)
       at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6781)
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1969)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1935)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:796)
       at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1)
       at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:48)
       at androidx.media3.session.MediaNotificationManager.startForeground(MediaNotificationManager.java:48)
       at androidx.media3.session.MediaNotificationManager.updateNotificationInternal(MediaNotificationManager.java:48)
       at androidx.media3.session.MediaNotificationManager.onNotificationUpdated(MediaNotificationManager.java:276)
       at androidx.media3.session.MediaNotificationManager.lambda$updateNotification$4(MediaNotificationManager.java:276)
       at androidx.media3.common.util.Util.postOrRun(Util.java:1)
       at androidx.media3.session.MediaNotificationManager.lambda$new$0(MediaNotificationManager.java:16)

or this  Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{40a30dd u0 com.kamancho.melisma/.player.presentation.PlayerService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7700)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

```

**Comment by marcbaechinger** [comment] 2024-01-22 09:03
If playback resumption is called you need to play something. You can't cancel because the service is already started and needs to start playback.

**Comment by BoikoIlya** [comment] 2024-01-22 16:40
if it is case when my track list is empty?

**Comment by marcbaechinger** [comment] 2024-01-22 23:22
There isn't an API to dynamically opt-out when a `MediaButtonReceiver` is declared in the manifest.

For now, there isn't a technical solution. As a workaround, an app can never store an empty playlist, but instead keep the last playlist before the users clears it. Admittedly, this still leaves an app with a last corner case, when the user starts the app for the very first time and closes without starting playback. This requires a dynamic API to be resolved I think.

I'm closing as a duplicate of #770

**Closed by marcbaechinger** 2024-01-22 23:22 UTC
Labels: question
