### ISSUE TITLE
Provide Option to read unsynced lyrics using Metadata or ID3Tags

### ISSUE THREAD

**Issue by pawaom** [androidx/media#1435] opened 2024-06-09 09:05 UTC
Replace the content in the sections below.

### [REQUIRED] Use case description
 Provide Option to read unsynced lyrics using Metadata or ID3Tags

Currently I Am trying to read unsynced lyrics  

Using the below code

```
override fun onTracksChanged(tracks: Tracks) {
                    //https://github.com/androidx/media/issues/922
                    //https://github.com/androidx/media/issues/1305
                    tracks.groups.forEach { group ->
                        for (i in 0 until group.length) {
                            group.mediaTrackGroup.getFormat(i).metadata?.let { metadata ->
                                for (j in 0 until metadata.length()) {
                                    metadata.get(j).let {


                                        if (it is CommentFrame) {
                                            println("${it.id} ${it.text}") // COMM <value>
                                        }
                                        if (it is BinaryFrame) {
                                            Log.e(
                                                "Metadata",
                                                "id3 BinaryFrame key: " + it.id + " data: " + it.data.size
                                            )
                                            if ("USLT".equals(
                                                    it.id,
                                                    ignoreCase = true
                                                )
                                            ) {
                                                Log.e(
                                                    "Metadata",
                                                    "id3 UNSYNCEDLYRICS onTracksChanged: " + String(
                                                        it.data
                                                    )
                                                )
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }


                }
```
This code is able to read synced Lyrics like below

![Screenshot 2024-06-09 142733](https://github.com/androidx/media/assets/28686824/52d1bf2b-c66f-40ae-b101-148cc7a56107)

How ever when we try to read unsynced Lyrics it is not able to read them like below 

 
![Screenshot 2024-06-09 142814](https://github.com/androidx/media/assets/28686824/df34a573-e0ba-4608-bd81-dc88edf9b4f6)

### Proposed solution
 It would be better if we are able to read it as metadata using

 ```
override fun onMediaMetadataChanged(mediaMetadata: MediaMetadata) {
                    super.onMediaMetadataChanged(mediaMetadata)
                    mediaMetadata.title?.let( { println(it) } )

                }
```
Which provides various options like Title, composer , Artist , Album etc

### Alternatives considered
there are options to use Third party alternativos like .

[jaudiotagger](https://github.com/Kaned1as/jaudiotagger)

Or  [mp3agic](https://github.com/mpatric/mp3agic)

How ever they can be unreliable and an inbuilt solution will be helpful.

**Comment by icbaker** [comment] 2024-06-12 11:03
This looks like a duplicate of https://github.com/androidx/media/issues/922

**Closed by icbaker** 2024-06-12 11:03 UTC
Labels: enhancement, needs triage
