### ISSUE TITLE
rare bandwitdh updates with low-latency content

### ISSUE THREAD

**Issue by TeaFather** [androidx/media#1813] opened 2024-10-18 07:48 UTC
### Version

Media3 1.4.1

### Devices that reproduce the issue

All
samsung s20 fe
samsung s22

### Devices that do not reproduce the issue

none

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play low-latency DASH content. Sample manifest attached. In regular dash content bandwidth is update every few seconds and representations are changed smoothly. While playing low-latency there are updates of bandwidth once per few minutes which is causing player to change representations after few minutes. 

### Expected result

Low-latency DASH reps are changed and bandwidth is updated the same way as in regular DASH content.

### Actual result

Representations are changed when network is better the same way as for DASH content.
Bug report attached:
[bugreport-Amigo7xcCN-SC-2024-10-18-10-09-21.zip](https://github.com/user-attachments/files/17430303/bugreport-Amigo7xcCN-SC-2024-10-18-10-09-21.zip)

### Media

Attaching manifest
[index(12).mpd.zip](https://github.com/user-attachments/files/17430381/index.12.mpd.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment] 2024-10-18 14:43
I think this is a duplicate of https://github.com/google/ExoPlayer/issues/10630. Switching resolutions while in the low-latency range is often hard because we don't get any reliable updated bandwidth estimates.

**Closed by tonihei** 2024-10-18 14:43 UTC
Labels: bug, needs triage
