### ISSUE TITLE
ImageOutput consecutive images

### ISSUE THREAD

**Issue by rigor789** [androidx/media#1260] opened 2024-04-10 13:18 UTC
### Version

Media3 1.3.1

### Devices that reproduce the issue

Android TV Emulator - API34

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. add 2 or more consecutive images, with something like
    ```java
    androidx.media3.common.MediaItem.Builder()
      .setUri("https://some-image-url")
      .setMimeType(androidx.media3.common.MimeTypes.IMAGE_JPEG)
      .setImageDurationMs(10000)
    ```
2. call `setImageOutput` on the player instance and implement `onImageAvailable`, `onDisabled`
3. prepare/play media

### Expected result

- onImageAvailable (image1)
- wait 10 seconds
- onImageAvailable (image2)
- wait 10 seconds
- onDisabled

### Actual result

- onImageAvailable (image1)
- wait 10 seconds
- onImageAvailabel (image2)
- onDisabled

### Media

Not applicable (any image media)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment] 2024-04-12 10:50
Hi @rigor789,

Thanks for reporting your issue. This is a known issue that was presented in this Github ticket as well, https://github.com/androidx/media/issues/1017 and so I will close as duplicate. Feel free to ask your questions in that thread if you need additional help while we figure out a solution to onDisabled problem.

**Comment by microkatz** [comment] 2024-04-12 10:51
Duplicate of https://github.com/androidx/media/issues/1017

**Closed** 2024-04-12 10:51 UTC
Labels: bug, duplicate, needs triage

**Comment by rigor789** [comment] 2024-04-12 11:05
Hi @microkatz, sure thing! I have seen that issue but didn't realize it was describing the same scenario, your suggestion to use the `onMediaItemTransition` is something we'll try next, thank you 👍
