### ISSUE TITLE
How to show AlbumArt in Lock Screen Controls 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#203] opened 2022-11-06 11:44 UTC
How to show AlbumArt in Lock Screen Controls .

We want to show album art in Lock Screen Control **And also show Artist name instead of Album or vice versa**  how can we achieve this.

What we get is 

 
![198814018-366c4ecf-6609-4d02-a2b0-05e119556fe2](https://user-images.githubusercontent.com/28686824/200168500-9ff1fca0-0a50-415b-b2a9-d8c9260de3d5.jpg)

What we want is this

![Screenshot_20221106-170303_Music Player](https://user-images.githubusercontent.com/28686824/200168505-323fdc77-198b-48f7-807f-8e27032ef8ba.jpg)

Steps to Reproduce the problem

Using the media session demo code, play any song say for example  --  the music is you

We want to show the Album art which is shown in the notification , in the lock screen control also.

**Comment by marcbaechinger** [comment] 2022-11-06 12:53
This is a duplicate of #199. Thanks for reporting this again but I think one issue for this problem should be sufficient.

**Closed by marcbaechinger** 2022-11-06 12:53 UTC
Labels: question, needs triage

**Comment by pawaom** [comment] 2022-11-06 13:45
Hi , thanks for the reply ,   I am talking specifically of showing album art in lock screen control, which even the media session demo app doesnot support, please consider this aspect aswell.
