### ISSUE TITLE
Exoplayer cannot be constructed with a specification for "surface_type" programmatically? Why not?

### ISSUE THREAD

**Issue by jonmdev** [androidx/media#1375] opened 2024-05-15 02:33 UTC
### Version

Media3 main branch

### More version details

As noted here:

- https://github.com/androidx/media/issues/1360
- https://github.com/CommunityToolkit/Maui/issues/1730
- https://github.com/CommunityToolkit/Maui/issues/1773
- https://stackoverflow.com/questions/78446498/how-to-create-textureview-programmatically-with-exoplayer-in-net-maui
- https://stackoverflow.com/questions/78457606/how-to-create-iattributeset-from-xml-string-using-xmlreader-in-net-android

There exists no way to create an ExoPlayer programmatically while declaring the surface type in the constructor in C#/.NET. The only proposed way to do this in Android is explained [here](https://github.com/androidx/media/issues/1360) but even this is extremely clumsy and illogical.

No equivalent to this Android code exists in C#/.NET. No one is able to propose a method to make this possible in C#/.NET.

It seems obvious then the simplest solution is to simply add a constructor (which should exist either way) where we can declare the surface type on construction.

For example, we could have a simple enum:
```
enum ExoPlayerSurfaceType {
    surfaceView,
    textureView,
    none
}
```
We have the currently unhelpful constructor:

```
public unsafe StyledPlayerView (global::Android.Content.Context? context, global::Android.Util.IAttributeSet? attrs)
```

We could add the following option:
```
public unsafe StyledPlayerView (global::Android.Content.Context context, ExoPlayerSurfaceType surfaceType)
```

Or we could have an entire new class for `ExoPlayerConstructorAttributes` which we could create an object of and set the surface type inside (along with any other "only available on construction" parameters if they exist).

Why is this not the case already? If you agree this is a logical solution, how can we add it? 

Thanks.

### Devices that reproduce the issue

All ExoPlayer developments

### Devices that do not reproduce the issue

n/a

### Reproducible in the demo app?

Yes

### Reproduction steps

See demo code and the problems this issue is causing in links above, or again, at:

- https://github.com/androidx/media/issues/1360
- https://github.com/CommunityToolkit/Maui/issues/1730
- https://github.com/CommunityToolkit/Maui/issues/1773
- https://stackoverflow.com/questions/78446498/how-to-create-textureview-programmatically-with-exoplayer-in-net-maui
- https://stackoverflow.com/questions/78457606/how-to-create-iattributeset-from-xml-string-using-xmlreader-in-net-android

### Expected result

One should be able to easily create an ExoPlayer with any type of surface (TextureView, SurfaceView, none) easily from a simple constructor in Android or C#/.NET. 

### Actual result

It is currently very circuitous to do this in native Android code and completely impossible in C#/.NET. No solutions or answers are available anywhere.

### Media

Open Visual Studio 2022. Go File > New > Android Application. Copy and paste the code here into MainActivity.cs:

```
protected override void OnCreate(Bundle? savedInstanceState) {
    base.OnCreate(savedInstanceState);
    
    string xmlString =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
        "<Com.Google.Android.Exoplayer2.UI.PlayerView " +           
        "android:id=\"@+id/player_view\" " +
        "app:surface_type=\"texture_view\" " + //KEY NEEDED LINE FOR GOAL
        "android:layout_width=\"match_parent\" " +
        "android:layout_height=\"match_parent\"/>";
    
    XmlReader xmlReader = XmlReader.Create(new StringReader(xmlString));
    xmlReader.Read();
    System.Diagnostics.Debug.WriteLine("XML READER " + xmlReader.AttributeCount);
            
    Android.Util.IAttributeSet attributes = Android.Util.Xml.AsAttributeSet(xmlReader);
    System.Diagnostics.Debug.WriteLine("ATTRIBUTES " + attributes.AttributeCount);
    
    Com.Google.Android.Exoplayer2.UI.StyledPlayerView styledPlayerView = new(this, attributes);            
```

Receive errors as there is no current working workflow available to do this.

**Comment by andrewlewis** [comment] 2024-05-15 09:33
Providing support for usage from C# is not really in scope for this tracker, but have you tried storing a layout file as a resource like what's described [here](https://learn.microsoft.com/en-us/dotnet/android/features/layout-code-behind/), instead of trying to construct and read the XML file programmatically?

Is this issue a duplicate of #1360?

**Comment by jonmdev** [comment] 2024-05-15 23:27
> Providing support for usage from C# is not really in scope for this tracker, but have you tried storing a layout file as a resource like what's described [here](https://learn.microsoft.com/en-us/dotnet/android/features/layout-code-behind/), instead of trying to construct and read the XML file programmatically?

Thanks, but would you say it is a likely intentional design choice that we cannot directly construct the ExoPlayer (in any language) with an obvious constructor that specifies the surface type?

Why would this be an intentional choice if so? It seems like an oversight to me and we can improve it by filling that gap with a simple extra constructor added.

Any other parameterization I believe can be made after building but we must give the surface type on construction.

Ie. Even in native Android code the only way I have seen is to artificially create an XML file or load it, then convert it obtusely into an Attribute file, then pass that into the construction.

Is that logical? It does not seem so to me. It seems like someone just forgot to make a useful constructor or never got around to it. Why not fix that?

Re: .NET, I understand that the interplay between .NET and Android creates a grey zone. But obviously Microsoft cannot add a new constructor to Android code. That is up to Android only. (Furthermore from what I have seen the .NET team is mostly focused on patching the thousands of bugs in MAUI now and are not even remotely keeping up with that, though that is not Android's problem of course.)

**Comment by jonmdev** [comment] 2024-05-16 06:56
After adding a .NET discussion (linked above) which has also been unhelpful, and reviewing further, I again believe this is an Android issue not a .NET issue.

The proposed Android solution here: https://stackoverflow.com/questions/68629114/use-textureview-programmatically-with-exoplayer/75302312#75302312

Requires one to save an XML file to resources, load it, parse it, and then pass it into the ExoPlayer constructor.

This makes no sense at all. If an `AttributeSet` is the intended way to pass in the constructor commands, why is there no way to create one programmatically? Or if there is a way, what is it?

**Comment by andrewlewis** [comment] 2024-05-16 07:31
I think setting attributes in the XML file is a conventional way to specify properties for a custom view -- see [Define custom attributes](https://developer.android.com/develop/ui/views/layout/custom-views/create-view#customattr). There are a bunch of these for `PlayerView` defined around [here](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/ui/src/main/res/values/attrs.xml#L99).

As documented [here](https://developer.android.com/reference/androidx/media3/ui/PlayerView#attributes) the intended way to use this is to set them in your layout XML file.

> After adding a .NET discussion (linked above) which has also been unhelpful, and reviewing further, I again believe this is an Android issue not a .NET issue.

Based on your reply just now, did you get this to work in the end? If not, please could you describe what didn't work in case that's useful to someone else in future?

**Comment by jonmdev** [comment] 2024-05-16 08:38
I did post the working code one reply above yours.

The problem as I see it however (which is clearly a Google Android design flaw is):

1) You cannot create XML from string (ie. programmatically) and convert it to a AttributeSet.
2) You can only convert XML that is loaded from Resources to AttributeSet.

This is absurd because it means you need to save a bunch of small snippets of XML to your resources folder in order to characterize your objects.

It reduces portability and flexibility of code. Android should have a working method to create the needed AttributeSet **WITHOUT** having to save and load a five line XML snippet from the resources folder.

**Closed** 2024-05-16 09:27 UTC
Labels: question, needs triage
