### ISSUE TITLE
Demo app is terminated, but process remains

### ISSUE THREAD

**Issue by leejooheon** [androidx/media#1042] opened 2024-01-29 10:06 UTC
I'm testing with demo-session app.
demo app onDestroy is called (both service and activity), but the process remains.

It can be reproduced with the steps below.

1. play something
2. swipe away from recent app (Activity destroyed)
3. pause from notification
4. wait 120 seconds (Service destroyed)
5. command in terminal `adb shell ps | grep androidx.media3.demo.session`
6. demo-session app printed

Is this behavior intended?

**Comment by leejooheon** [comment] 2024-01-31 01:23
Device: Galaxy s23, os 14

It's probably related to the issues below.
* https://github.com/androidx/media/issues/370
* https://github.com/androidx/media/issues/976

**Comment by marcbaechinger** [comment] 2024-02-05 16:19
Duplicate of [805](https://github.com/androidx/media/issues/805).

**Closed by marcbaechinger** 2024-02-05 16:19 UTC
Labels: question, needs triage
