### ISSUE TITLE
Fire stick 4k max 1st gen and 2nd gen BUG with DV + HDR content (split screen OR only blackscreen with audio)

### ISSUE THREAD

**Issue by nreis96** [androidx/media#957] opened 2024-01-09 14:28 UTC
### Version

Media3 1.2.0

### More version details

Hi, I am unsure of the version but default exoPlayer used in Stremio software will have this issue.

I was hoping there could be a fix from your side since for example it works properly with Vimu Media player being used as external player. However users don't have so many integrated features as they have in Stremio with exoPlayer, such as addons for subtitles.

Here's more details of this bug:

https://github.com/jellyfin/jellyfin-androidtv/issues/2630
https://github.com/google/ExoPlayer/issues/11096
https://www.reddit.com/r/Stremio/comments/191lvr7/firestick_4k_max_2nd_gen_dv_content_bug/

### Devices that reproduce the issue

Fire stick 4k Max 1st generation
Fire stick 4k Max 2nd generation

### Devices that do not reproduce the issue

Xiaomi Mi10T pro
TCL C635 55" with Google TV

### Reproducible in the demo app?

Not tested

### Reproduction steps

Open any source in stremio that has DV+HDR flag and use a firestick 4k max

1st gen: Only audio and a black screen
2nd gen: Split screen

### Expected result

Normal playing behaviour

### Actual result

Split screen or black screen

### Media

https://github.com/jellyfin/jellyfin-androidtv/issues/2630
https://www.reddit.com/r/Stremio/comments/191lvr7/firestick_4k_max_2nd_gen_dv_content_bug/

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by nreis96** [comment] 2024-01-09 15:01
Seems like this issue was already present before and still not solved/fixed: https://github.com/google/ExoPlayer/issues/11096

please investigate and release a hotfix if possible.

**Comment by christosts** [comment] 2024-01-10 13:44
this is a duplicate of https://github.com/google/ExoPlayer/issues/11096, up to @tonihei who handles the other issue to decide which one to keep open

**Comment by tonihei** [comment] 2024-01-10 16:16
It's enough to keep one issue open. Let's keep the existing one because of the history.

@nreis96 Please note that this is an issue in the decoder provided by Amazon on the Fire stick and Dolby investigated it already (see https://github.com/jellyfin/jellyfin-androidtv/issues/2630) and couldn't see a workaround other than fixing the actual device. The only other known workaround in the player is to actively change the bitstream of the media to remove certain fields, which is probably too invasive and it would be much better if Amazon could fix the decoders instead.

**Closed by tonihei** 2024-01-10 16:16 UTC
Labels: bug, needs triage
