### ISSUE TITLE
Transformer m3u8 to mp4 size issue

### ISSUE THREAD

**Issue by krishnasen2401** [androidx/media#897] opened 2023-12-15 07:12 UTC
### Version

Media3 1.2.0

### More version details

I am trying to convert a m3u8 vod file to mp4 

related note [https://www.xda-developers.com/android-11-unlimited-video-recording-file-size/#:~:text=Basically%2C%20Google%20decided%20that%20Android%27s,bytes%2C%20which%20is%20approximately%204GB.](url)

I have written a basic transformer code 
 `String Url = "https://yot.gnicirp.com/_v10/3d17db43edef4ec5e8e5b86b462ef47f3ac4054c526db5ff64ee5f9789a51556a8fd3b3996e3cc956d7ca9994fc00cc82497fa7c4107f2cf78007008baf3c86e9313e5e249e4213d0bec285c8f0010907ce707a2bbdd9d0ab8d5e675fa4da0a8128d2efba7b2a714454b51b70d78725ebec8a2f3c510bb29b829d10c9881ce3c2c6783d2f615455c3808f020362e97e3/1080/index.m3u8";
        Uri uri =  Uri.parse( Url );
        MediaItem mediaItem = MediaItem.fromUri(uri);
        File path = Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_DOWNLOADS);
        File output=new File(path ,"test.mp4");
        Transformer transformer = new Transformer.Builder(context)
                .addListener(new Transformer.Listener() {
                    @Override
                    public void onTransformationError(MediaItem inputMediaItem, Exception exception) {
                        exception.printStackTrace();
                    }
                }).build();
        String filePath = output.getAbsolutePath();
        Log.d("exportpath",filePath);
        transformer.start(mediaItem, filePath);` 
it works for small size video like of 1min but it crash issue for these my gradle is
 `implementation 'androidx.media3:media3-transformer:1.2.0'
    implementation 'androidx.media3:media3-common:1.2.0'
    implementation 'androidx.media3:media3-effect:1.2.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.2.0'` 

and the stacktrace it printed was 
`2023-12-15 12:37:32.770 29902-30817 MPEG4Writer             com.lingamworks.socialdownloaderv2   D  PreAllocation enabled
2023-12-15 12:37:32.787 29902-30817 MPEG4Writer             com.lingamworks.socialdownloaderv2   D  fpathconf _PC_FILESIZEBITS:64
2023-12-15 12:37:32.787 29902-30817 MPEG4Writer             com.lingamworks.socialdownloaderv2   D  File size limit set to 4503599627370495 bytes implicitly
2023-12-15 12:37:32.787 29902-30817 MPEG4Writer             com.lingamworks.socialdownloaderv2   D  MP4WtrCtrlHlpLooper Started
2023-12-15 12:37:32.789 29902-30851 MPEG4Writer             com.lingamworks.socialdownloaderv2   I  setStartTimestampUs: 0 from Audio track
2023-12-15 12:37:32.789 29902-30851 MPEG4Writer             com.lingamworks.socialdownloaderv2   I  Earliest track starting time: 0
2023-12-15 12:37:32.802 29902-30850 MPEG4Writer             com.lingamworks.socialdownloaderv2   I  setStartTimestampUs: 83333 from Video track
2023-12-15 12:37:32.839 29902-30847 libc                    com.lingamworks.socialdownloaderv2   A  FORTIFY: write: count 18446744073709551615 > SSIZE_MAX
2023-12-15 12:37:33.015 29902-30847 libc                    com.lingamworks.socialdownloaderv2   A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30847 (MPEG4Writer), pid 29902 (ialdownloaderv2)
2023-12-15 12:37:33.430 30855-30855 DEBUG                   pid-30855                            A  Cmdline: com.lingamworks.socialdownloaderv2
2023-12-15 12:37:33.430 30855-30855 DEBUG                   pid-30855                            A  pid: 29902, tid: 30847, name: MPEG4Writer  >>> com.lingamworks.socialdownloaderv2 <<<`
 is there anyway to change the limit or any idea what is cause the issue the FFmpeg library is able convert it successfully but in turn it increases the app size more

### Devices that reproduce the issue

All Device based on vod size
tested on Samsung S21 Ultra Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

Use the function in activity or fragment

### Expected result

convert and the file in the background and close

### Actual result

it crashes after 5 sec

### Media

https://yot.gnicirp.com/_v10/3d17db43edef4ec5e8e5b86b462ef47f3ac4054c526db5ff64ee5f9789a51556a8fd3b3996e3cc956d7ca9994fc00cc82497fa7c4107f2cf78007008baf3c86e9313e5e249e4213d0bec285c8f0010907ce707a2bbdd9d0ab8d5e675fa4da0a8128d2efba7b2a714454b51b70d78725ebec8a2f3c510bb29b829d10c9881ce3c2c6783d2f615455c3808f020362e97e3/1080/index.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by droid-girl** [comment] 2023-12-15 11:20
I reproduced the issue in our demo app. 
After the investigation, the conclusion is this issue is a duplicate of #725. I am closing this one.

**Comment by droid-girl** [comment] 2023-12-15 11:21
a duplicate of https://github.com/androidx/media/issues/725

**Closed by droid-girl** 2023-12-15 11:21 UTC
Labels: bug, needs triage, editing

**Comment by krishnasen2401** [comment] 2023-12-15 11:28
This issue link is different than one assigned 
1. The code doesn't use any custom mixer
2. The cause printed in logcat mention the size issue
3. The runtime error is code is would say the same even when hls library is not added and if we print the cause it would mention no factory found or added

**Comment by droid-girl** [comment] 2023-12-15 11:31
we looked at logs on our side and the root cause of the issue is the same
