### ISSUE TITLE
MediaController.releaseFuture() cancellation race

### ISSUE THREAD

**Issue by bubenheimer** [androidx/media#345] opened 2023-04-20 14:45 UTC
### Media3 Version

Media3 1.0.1

### Devices that reproduce the issue

N/A

### Reproducible in the demo app?

Not tested

### Reproduction steps

`MediaController.releaseFuture()` seems to have a cancellation race that could leak the controller when the future gets done between `isDone()` and `cancel()`:

https://github.com/androidx/media/blob/3c01488f8d478caaa54038431ee6339444ea6e04/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L520-L532

### Expected result

N/A

### Actual result

N/A

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-04-20 15:03
All of the methods of `MediaController` are supposed to be called from the specified application thread (see https://developer.android.com/reference/androidx/media3/session/MediaController#threading-model), including `releaseFuture`. The `Future` itself is also only marked as done on the same thread... so the case you describe shouldn't happen? Did you see this happen somehow and was it caused by using a different thread for calling `releaseFuture`? If so, I'd be curious to hear if the different thread was needed or more natural to use in your app.

**Comment by bubenheimer** [comment] 2023-04-20 15:31
Ah, right, I think I looked at that earlier and decided to go with it for that reason (release() must be called on the right thread). The intended contract is not obvious, though, as `releaseFuture()` is static and not directly tied to the specified `applicationLooper`. If it does get a hold of the controller without cancelling first, it would check if it's on the right thread, otherwise it would not. To validate correctness I'd need to find the internals of where the future is marked done.

Perhaps the javadoc could clarify the contract. Also, can't you skip the `isDone()' check and just test the return value of `cancel()? This would seem to address the unclear correctness part.

**Comment by bubenheimer** [comment] 2023-04-20 16:34
The reason I tripped over this was my MediaSessionService leaking, so I did a code inspection.

**Comment by tonihei** [comment] 2023-04-21 09:42
Thanks for the suggestion - we can mention it in the docs (and use `future.cancel` only without the additional `isDone` check)

**Closed** 2023-04-25 10:58 UTC
Labels: question
