### ISSUE TITLE
HLS stream cannot be played from the beginning. Need to seek forward a little to be able to play it.

### ISSUE THREAD

**Issue by ThorAsgardDev** [androidx/media#1357] opened 2024-05-09 12:55 UTC
### Version

Media3 1.3.1

### Devices that reproduce the issue

NVIDIA Shield TV and Android Virtual Device (Android TV - API Level 26)

### Devices that do not reproduce the issue

The file can be played by other players like this one:
https://livepush.io/hls-player/index.html

### Reproducible in the demo app?

Yes

### Reproduction steps

In media.exolist.json file, replace:
```
{
  "name": "Apple 4x3 basic stream (TS)",
  "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"
},
```
by:
```
{
  "name": "Apple 4x3 basic stream (TS)",
  "uri": "https://stream.kick.com/ivs/v1/196233775518/tSMwjQ5tWBFF/2024/4/16/15/39/4CyLhNtx5X2v/media/hls/master.m3u8"
}
```
Then run the app and play HLS Apple 4x3 basic stream (TS)

### Expected result

Stream start and play

### Actual result

Got the error "Playback failed"
Click play button and still get error "Playback failed"

Click on button "seek forward 15sec"
Click play button and stream start without any problem

### Media

https://stream.kick.com/ivs/v1/196233775518/tSMwjQ5tWBFF/2024/4/16/15/39/4CyLhNtx5X2v/media/hls/master.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2024-05-09 14:58
I can reproduce the symptoms you describe.

I see this in logcat when playback fails:

```
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:733)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:709)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loopOnce(Looper.java:232)
      at android.os.Looper.loop(Looper.java:317)
      at android.os.HandlerThread.run(HandlerThread.java:68)
  Caused by: androidx.media3.exoplayer.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with MIME type video/avc.
      at androidx.media3.exoplayer.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:62)
      at androidx.media3.exoplayer.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:182)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1144)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:560)
      at android.os.Handler.dispatchMessage(Handler.java:103) 
      at android.os.Looper.loopOnce(Looper.java:232) 
      at android.os.Looper.loop(Looper.java:317) 
      at android.os.HandlerThread.run(HandlerThread.java:68) 
```

I then tried playing it again with chunkless preparation disabled. In this case playback progresses but no audio or video tracks are found.

@tianyif please can you take a look to understand what it is about this stream that ExoPlayer doesn't like?

**Comment by icbaker** [comment] 2024-05-09 15:18
I see this logged in the chunkfull case:

```
Unmapped track with id 27 of type 2  
Unmapped track with id 8219 of type 3
```

Which sounds like it's related to the error logged when using chunkless preparation.

**Comment by tianyif** [comment] 2024-05-10 15:53
Thanks @ThorAsgardDev and @icbaker for the initial investigations!

I was able to reproduce the same scenarios for both "chunkless" and "chunkfull" preparations. Also, I found that the first segment `0.ts` in each media playlist (eg. https://stream.kick.com/ivs/v1/196233775518/tSMwjQ5tWBFF/2024/4/16/15/39/4CyLhNtx5X2v/media/hls/720p30/0.ts), if played separately without HLS, also doesn't have video but playback still progressed. This was even reproducible when playing with VLC (File -> Open Network -> put the above URL in the URL input box), however not reproducible on QuickTime player.

When playing the above `0.ts` file, it looks like the `TsExtractor` didn't create an `H264Reader` which will further create a video `SampleQueue`. Thus, in the case of "chunkless" preparation, while the multivariant playlist declares that there is video track and tries to map the video `TrackGroup` to a `SampleQueue`, it fails `Unable to bind a sample queue to TrackGroup with MIME type video/avc`, which seems to be expected to me at this point.

@icbaker, would it be something wrong with the `0.ts` or our `TsExtractor`?

**Comment by icbaker** [comment] 2024-05-10 16:03
Ah, I thought I checked the TS file, but I wrongly downloaded `1.ts` not `0.ts` - oops. I see no video track in `0.ts`:

```
$ mediainfo 0.ts
General
ID                                       : 1 (0x1)
Complete name                            : 0.ts
Format                                   : MPEG-TS
File size                                : 2.38 MiB
Duration                                 : 10 s 837 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 833 kb/s

Audio
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 10 s 901 ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy

Menu
ID                                       : 4096 (0x1000)
Menu ID                                  : 1 (0x1)
Format                                   : AAC /
Duration                                 : 10 s 837 ms
List                                     : 256 (0x100) (AAC) / 258 (0x102) ()
```

Which makes this a duplicate of https://github.com/google/ExoPlayer/issues/8101, specifically https://github.com/google/ExoPlayer/issues/8101#issuecomment-715304174

**Comment by tianyif** [comment] 2024-05-10 16:26
Thanks @icbaker! 

@ThorAsgardDev, if you're expecting your stream to always contain video track, you may want to replace it with a correct segment `.ts` file.

**Closed** 2024-05-10 16:27 UTC
Labels: duplicate, bad media

**Comment by ThorAsgardDev** [comment] 2024-05-10 16:45
Thanks @tianyif  and @icbaker for investigation.
I'm using Exoplayer to play some media files found on the internet. This video is not mine so I can't modify it to fix the problem.
I opened this issue because this video can be played with some players and not using Exoplayer.
