### ISSUE TITLE
How to Update Metadata of Already Added MediaItems?

### ISSUE THREAD

**Issue by XuQK** [androidx/media#337] opened 2023-04-19 11:28 UTC
After setting the playlist using controller.setMediaItems(), is there a way to directly modify the already set MediaItem?
My project plays local audio files, and I use MediaMetadataRetriever in the onAddMediaItems callback of the Service to parse the files to obtain the actual music name, duration, and other information. When there are a lot of audio files (1k+), the parsing speed is very slow.
So, is it possible to set temporary information in onAddMediaItems, then parse it in the background using MediaMetadataRetriever, and replace the parsed information in the already added MediaItem after parsing is complete? Or is there a better approach?

**Comment by christosts** [comment] 2023-04-19 15:14
This looks like a duplicate of #33, so I'll close this. Please re-open you think #33 does not address your use-case.

**Closed by christosts** 2023-04-19 15:14 UTC
Labels: question, needs triage

**Comment by tonihei** [comment] 2023-04-19 15:21
One more note/question: ExoPlayer and most other players will parse the media metadata when trying to play a file at the latest. So unless you need to know all metadata in advance (e.g. to display it to a user), there is actually no need to do any of the background service logic you describe here.

**Comment by tonihei** [comment] 2023-04-20 07:59
Thanks for the clarification. Just for completeness: Once we get around to fix https://github.com/google/ExoPlayer/issues/4727, you really don't need your workaround anymore because ExoPlayer would take care of reading all metadata initially if requested.
