### ISSUE TITLE
Apply `Metadata` information to an `AudioProcessor` before it starts processing audio?

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1351] opened 2024-05-07 18:16 UTC
My app applies ReplayGain Volume Normalization with a custom `AudioProcessor` that is updated with `Metadata` whenever a `Player.Listener` is notified that the current `MediaItem` changed. As I've increasingly noticed though, there is some level of delay between when audio begins to be processed, and when the normalization is applied. All of the metadata is pre-loaded and applied instantly, so it must be a delay between when my `AudioProcessor` starts processing audio and when it is updated from the `Player.Listener`. I believe this is is because `Player.Listener` is called once all commands have been fully processed. This leads to a strange user experience where for around 0.25s to 0.5s the volume will not be properly normalized.

Is there any way I can try to configure the `AudioProcessor` with the required metadata before it starts processing audio? I would think that before audio is processed that there is some `MediaItem` or `MediaSource` that is being read from that I could attach the metadata to, but it is not exposed to the `AudioProcessor` in favor of an `AudioFormat` that obviously can't contain that kind of information.

**Comment by tonihei** [comment] 2024-05-08 09:45
I think this is a duplicate of #418

**Closed by tonihei** 2024-05-08 09:45 UTC
Labels: question, needs triage
