### ISSUE TITLE
Buffer size and quality setting for audio streams

### ISSUE THREAD

**Issue by MrBzik** [androidx/media#297] opened 2023-04-05 10:16 UTC
Hi. I have noticed there might be some recent changes to how buffer size can be set in ExoPlayer? I need to add functinality so that users can choose buffer size. I only found old posts that loadcontroller can be added in ExoPlayer build. Is there a way to change buffer size on fly? Or I should recreate the whole player with new settings. 
Also, I don't find information on how audio quality can be set (lower it, for example, for less traffic consumption). Is there a way to do that? 
Thank you.

**Comment by tonihei** [comment] 2023-04-06 15:55
`DefaultLoadControl` can be reconfigured at the moment. However, you can provide your own `LoadControl` implementation to forwards to `DefaultLoadControl` and whenever you want to change the configuration, you can recreate the wrapped instance with the new parameters.

> find information on how audio quality can be set

Please have a look at https://developer.android.com/guide/topics/media/exoplayer/track-selection for track selection questions.

**Comment by MrBzik** [comment] 2023-04-07 11:40
Thanks for your answer. Did you mean DefaultLoadControl can not be reconfigured as for now? 
As for lowering audio quality. I should constraint bitrate (in track-selector), or there is something else?

**Comment by MrBzik** [comment] 2023-04-08 12:50
Also, as for enabling float output, am I setting it correctly?: 


`@Provides
    @ServiceScoped
    fun providesAudioAttributes() = AudioAttributes.Builder()
        .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
        .setUsage(C.USAGE_MEDIA)
        .build()
`


`    



    @Provides
    @ServiceScoped
    fun providesExoPlayer (
        @ApplicationContext app : Context,
        audioAttributes: AudioAttributes,
        renderersFactory: DefaultRenderersFactory
    ) = ExoPlayer.Builder(app, renderersFactory)
        .setAudioAttributes(audioAttributes, true)
        .setHandleAudioBecomingNoisy(true)
        .build()

    @Provides
    @ServiceScoped
    fun providesDataSourceFactory (
        @ApplicationContext app : Context
    ) = DefaultDataSource.Factory(app)

    @Provides
    @ServiceScoped
    fun providesRendersFactory(
        @ApplicationContext app : Context
    ) = object : DefaultRenderersFactory(app){
        override fun buildAudioSink(
            context: Context,
            enableFloatOutput: Boolean,
            enableAudioTrackPlaybackParams: Boolean,
            enableOffload: Boolean
        ): AudioSink? {
            return DefaultAudioSink.Builder()
                .setAudioCapabilities(getCapabilities(app))
                .setEnableFloatOutput(true)
                .setEnableAudioTrackPlaybackParams(enableAudioTrackPlaybackParams)
                .build()
        }
    }`

I don't notice any difference, and I still can change playback speed like this : 

`val params = PlaybackParameters(playbackSpeed, playbackPitch)
         exoPlayer.playbackParameters = params`

Though it says playback setting is disabled if float output is on.

**Comment by tonihei** [comment] 2023-04-11 11:18
> Result - zero effect. It still plays for like ~ 10 sec

This is likely caused by `ProgessiveMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES` that only checks if loading should continue every 1MB of loaded data. If your stream is very low bitrate, it may as well load 10 seconds worth of data before even checking. You can change the value as you like by calling `ProgressiveMediaSource.Factory.setContinueLoadingCheckIntervalBytes`, but note that loading becomes less efficient if it needs to check more often. 

> I was looking into enabling float output.

This only works if the input media is also float PCM or (24/32bit integer PCM). See the javadoc of `setEnableFloatOutput` that explains this as well.

**Comment by MrBzik** [comment] 2023-04-12 10:14
The issue is I don't queit understand how I am supposed to controll buffer size, whatever setting will be. 
The streams urls I provided before. Depending on bitrate, network profiler shows they indeed send different amount of data. So that must have some effect on buffer, if I am to calculate it? 

Also, I would really like to make sure my setup of exoplayer is not making those streams sound the same.

**Comment by MrBzik** [comment] 2023-04-16 16:12
I think I figured most of the issues with buffering. One that remains is it seems exoplayer topping up buffer only while paused. If not, regardless of internet conditions and bitrate of the stream (which can be very light) it gets some buffer (about 10 seconds) and then just maintains it on that level. Is that normal?

**Comment by tonihei** [comment] 2023-07-10 08:45
Closing because the question about loading check intervals was solved.

**Closed by tonihei** 2023-07-10 08:45 UTC
Labels: question
