### ISSUE TITLE
FFmpeg decoder module building error

### ISSUE THREAD

**Issue by LSDsl** [androidx/media#808] opened 2023-11-13 06:46 UTC
### Version

Media3 1.1.1

### Devices that reproduce the issue

NDK r21e and r21
Ubuntu 20.04.2 LTS

### Reproducible in the demo app?

Not tested

### Reproduction steps

https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg#readme

### Expected result

Success build

### Actual result

Using 64 jobs for make
~/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang is unable to create an executable file.
**C compiler test failed.**

### Media

none

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment] 2023-11-15 18:12
Hi @LSDsl,

The error you're encountering suggests that there is an issue with the C compiler (armv7a-linux-androideabi16-clang) being unable to create an executable file. Can you please ensure that the user running the build process has the necessary permissions to create executable files in the specified directories?

If there is no permission issue, I would request you to attach the full log dump here for me to look further into this.

**Comment by LSDsl** [comment] 2023-11-15 18:49
script running from root. how I can create full log dump?

**Comment by rohitjoins** [comment] 2023-11-15 19:42
Just add `set -x` at the beginning of the script. Although I'm not sure if the logs generated will help me debug it any further. 

I'm able to run the same script without any issues, you'll probably need to try this on another system. The error above is not specific to setting up ffmpeg decoder or ExoPlayer.

**Comment by rohitjoins** [comment] 2023-11-15 19:44
Closing this issue as we are unable to assist with this issue as it relates to a generic Linux error, which is outside our area of expertise.

**Comment by rohitjoins** [comment] 2023-11-23 03:51
Hi @LSDsl,

I was able to reproduce the error when trying to build ffmpeg. 

You can find the actual reason for the failure when you go to the end of config log file in ffbuild. From the `jni` folder where you're executing the command, you can check the log file at `ffmpeg/ffbuild/config.log`.

Please let me know the error you see there and may be we can debug this further. Thank you for your patience.

**Comment by davidwonghk** [comment] 2023-12-17 20:43
I got the error with another root cause.

I have downloaded the latest Android NDK from Android Studio as of the time writing this (version 26.1.10909125), and in my ndk directory (Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin) there is no armv7a-linux-androideabi16-clang. The earliest version it has is "armv7a-linux-androideabi21-clang".

I tried to modify the build_ffmpeg.sh to use the binary "armv7a-linux-androideabi21-clang" instead of "armv7a-linux-androideabi16-clang" and it seems working.

**Comment by rohitjoins** [comment] 2023-12-20 17:50
Hi @davidwonghk,

https://github.com/androidx/media/pull/867 already allows setting `ANDROID_ABI` version, please note that this is still in the `main` branch.

Also note that the `README` in the release branch says its only been tested with r23c and doesn't support the latest NDK.

**Closed by rohitjoins** 2023-12-20 17:50 UTC
Labels: bug, need more info
