### ISSUE TITLE
Infinite buffering with with some MPEG-TS streams

### ISSUE THREAD

**Issue by equeim** [androidx/media#442] opened 2023-06-06 21:10 UTC
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

Mi Stick

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play bbbad.ts

This video is a bit special, to replicate conditions that trigger the issue:
1. PTS of its first audio packet is ~660 ms less than PTS of its first video packet
3. First audio packets appears _after_ first video packet (despite having "earlier" PTS)

I suspect that this is caused by following:

1. MediaCodecAudioRenderer sets current position to the value that is less than initial position:
https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/MediaCodecAudioRenderer.java#L664

3. This causes first frame to be never rendered because following condition evaluates to false:
https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/video/MediaCodecVideoRenderer.java#L1086

positionUs that was altered by MediaCodecAudioRenderer is less than outputStreamOffsetUs and never increases because rendering is not started.

### Expected result

Video is playing

### Actual result

Infinite buffering (for some reason not always, but in 90% of cases)

### Media

[bbbad.zip](https://github.com/androidx/media/files/11669199/bbbad.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by oceanjules** [comment] 2023-06-06 21:23
Did you mean to swap expected and actual results? Expected = playing, actual = infinite buffering?

**Comment by equeim** [comment] 2023-06-06 21:24
> Did you mean to swap expected and actual results? Expected = playing, actual = infinite buffering?

Oops, fixed.

**Comment by christosts** [comment] 2023-11-24 12:06
I'm sorry for the late response. I believe this issue a duplicate of https://github.com/androidx/media/issues/291 which is now fixed. I tested the file with the 1.2.0 release and it plays fine.

**Closed by christosts** 2023-11-24 12:06 UTC
Labels: bug, needs triage
