### ISSUE TITLE
Use DatabaseProvider with Room

### ISSUE THREAD

**Issue by dabluck** [androidx/media#783] opened 2023-10-31 16:41 UTC
If I want to use [SimpleCache](https://developer.android.com/reference/kotlin/androidx/media3/datasource/cache/SimpleCache?hl=en) for a [CacheDataSource](https://developer.android.com/reference/androidx/media3/datasource/cache/CacheDataSource), it requires a database provider. [DatabaseProvider](https://developer.android.com/reference/androidx/media3/database/DatabaseProvider) only takes an Android SQLiteDatabase. 

If we're using Room, we only have a [RoomDatabase](https://developer.android.com/reference/kotlin/androidx/room/RoomDatabase) which is built on the androidx sql libraries, and we only have a [SupportSqliteHelper](https://developer.android.com/reference/kotlin/androidx/sqlite/db/SupportSQLiteOpenHelper) which gives only a [SupportSQLiteDatabase](https://developer.android.com/reference/kotlin/androidx/sqlite/db/SupportSQLiteDatabase).

As far as can tell, the only workaround is to write your own [Cache](https://developer.android.com/reference/androidx/media3/datasource/cache/Cache). Duplicating all the logic in SimpleCache to simply switch out a support library is a lot of work. 

Is there any alternative I'm missing?

**Comment by tonihei** [comment] 2023-10-31 17:00
I think this is a duplicate of https://github.com/google/ExoPlayer/issues/5933. If you are motivated, feel free to send a PR to make this update. We haven't got around to do this ourselves yet.

**Closed by tonihei** 2023-10-31 17:00 UTC
Labels: enhancement, needs triage

**Comment by dabluck** [comment] 2023-10-31 17:11
@tonihei if I sent a PR are you okay with the hard dependency on the sqlite support lib?

**Comment by tonihei** [comment] 2023-11-01 09:47
Yes, you are right, this is a potential concern with this approach that wasn't immediately clear when I suggested to write a PR. I'll have a look at #784 and leave further comments there.
