### ISSUE TITLE
ANR Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by tobyworks** [androidx/media#299] opened 2023-04-06 08:10 UTC
### Media3 Version

Media3 1.0.0 , target and compile sdk 33

### Devices that reproduce the issue

Galaxy S20 FE 5G - Android 13
Pixel 6 - Android 13 
Pixel 7 - Android 13 

### Devices that do not reproduce the issue

Unknown

### Reproducible in the demo app?

Yes. in UAMP when targetting compile sdk 33 and media3 1.0.0

### Reproduction steps

- Open App
- Kill App
- Press play/pause on bluetooth headset OR `adb shell input keyevent 126`
- observe crash after some seconds 

What i notice is that the service gets recreated when i press the bluetooth controls. How do i circumvent this?

https://user-images.githubusercontent.com/2817395/230439631-2847b028-a8e1-4167-b7cb-0ff6ddbb978b.mp4

download project: https://transfer.sh/vEey0M/uamp.zip

### Expected result

ANR Shouldn't happen

- we are getting ANR's in crashlytics since using Media3 but we cant determine the root cause of this issue maybe you have an idea what might cause these issues.

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e7bf2a3 u0 .....Redacted....../.....MediaLibraryService}
android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2245)
android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2216)
android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2508)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)



android.app.ActivityThread.main (ActivityThread.java:8757)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

### Actual result

ANR happens

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e7bf2a3 u0 .....Redacted....../.....MediaLibraryService}
android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2245)
android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2216)
android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2508)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8757)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/2817395/230324739-144e9692-5b25-4186-ba9c-b3205cd614ec.png">

### Media

any media

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-04-06 15:53
@marcbaechinger  Do we have some existing GH issue comment thread that explains potential reasons for this and what could go wrong? It interesting to see that more or less of these issues happened on Samsung and Android 13.

**Comment by tobyworks** [comment] 2023-04-06 16:12
After some additional testing. this is 100% reproducable on UAMP when targeting SDK 33 and 1.0.0 media3

**Comment by tobyworks** [comment] 2023-04-06 16:12
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2817395/230436650-c6d97d54-7959-4ece-82c2-9f2891ce20dc.png">

**Comment by tobyworks** [comment] 2023-04-06 16:14
> @marcbaechinger Do we have some existing GH issue comment thread that explains potential reasons for this and what could go wrong? It interesting to see that more or less of these issues happened on Samsung and Android 13.

It is explainable why it happens on Samsung mostly. it's because some users remap the bixby button to play pause. So this 'edgecase' is way more likely to happen on those devices.

**Comment by marcbaechinger** [comment] 2023-04-06 16:14
We have #167 that is about `ForegroundServiceDidNotStartInTimeException`.

On a Pixel device the above repro steps can not happen if they are correct:

```
1 - Open App
2 - Kill App
3 - Press play/pause on bluetooth headset
4 - observe crash after some seconds
```

The report says it is reproducible with the demo app. The demo app does not have a `MediaButtonReceiver` configured. so unless someone modified the demo app. Step 3 should just do nothing on a Pixel phone.

So if this is only happening on Samsung devices and it happens with Samsung devices only, then Samsung is doing something differently to vanilla Android. This can be that the system tries to restart the service without a `MediaButtonReceiver`. If this is the case, then the above bug report shows why this isn't a good idea in my opinion.

@tobyworks Is the comment above reproducible with the demo app intended to be `true`? How is the demo app service started once the app is killed?

**Comment by marcbaechinger** [comment] 2023-04-06 16:16
How does the bixby button start the service and how is an app supposed to prepare the player with which media in this case? How does the bixby button know whether an app supports starting this way?

Does Samsung document this somewhere?

**Comment by tobyworks** [comment] 2023-04-06 16:17
@marcbaechinger I advise you to check UAMP targetting sdk 33 and media3 1.0.0
```
com.example.android.uamp.next        E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.android.uamp.next, PID: 21384
                                                                                                    android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{62a17b u0 com.example.android.uamp.next/com.example.android.uamp.media.MusicService}
                                                                                                    	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2001)
                                                                                                    	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1975)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2237)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	```

**Comment by tobyworks** [comment] 2023-04-06 16:47
Have you tried it in UAMP project that i sent you? it is 100% reproducable in that configuration. Nothing has been changed. besides the bump in target sdk and media 3

**Comment by eXaLy** [comment] 2023-04-06 16:51
On the `media3` branch

**Comment by marcbaechinger** [comment] 2023-04-06 16:52
I haven't. I just saw there is actually a second manifest in UAMP that has a receiver.

Thanks for the logs:

```
Last MediaButtonReceiver: MBR {pi=PendingIntent{c9283b3: PendingIntentRecord{df4cd70 com.example.android.uamp.next startForegroundService}}, type=3}
```

Let me flash my device. I'm currently on UDC and need to flash to Android 13.

You still need to implement this in your app. If we can show it's not working with UAMP, what would it tell us? That the app needs to implement starting playback. Your app would need to do the same.

**Comment by tobyworks** [comment] 2023-04-06 16:56
> I haven't. I just saw there is actually a second manifest in UAMP that has a receiver.

It also happens without the Manifest Entry. It the button receiver is only used for pre API 21 afaik.

> You still need to implement this in your app. If we can show it's not working with UAMP, what would it tell us? That the app needs to implement starting playback. Your app would need to do the same.

But we can't right now because implicitly the service get's started by `MediaLibraryService`. And we dont have full control over that.

**Comment by marcbaechinger** [comment] 2023-04-06 17:22
I will look into this and make sure that we put this into the session demo and UAMP.

> the button receiver is only used for pre API 21 afaik.

I think you are correct that for API 21 and lower, the `MediaButtonReceiver` is also required when the app is running. 

If the app is not running and the session is correctly destroyed, then this doc https://developer.android.com/guide/topics/media-apps/mediabuttons says you are not entirely correct.

"If you are running Android 8.0 (API level 26) or later, the system tries to find the last app with a MediaSession that played audio locally. If the session is still active Android sends the event directly to it. **Otherwise, if the session is not active and it has a mediabutton receiver, Android sends the event to the receiver, which will restart the session and so it can receive the event.**"

**Comment by tobyworks** [comment] 2023-04-06 18:48
Do you have an idea how you will or your colleagues will fix this in UAMP so we can do it aswell asap. Right now our users are not happy with the update we did and are giving 1 star reviews because of it.

**Comment by marcbaechinger** [comment] 2023-04-07 12:22
I have added some sample code in #167 I think it's best to keep the discussion around `ForegroundServiceDidNotStartInTimeException` in one place. I close this issue as a duplicate. Lets continue the conversation in the other bug. Thanks for your report!

**Closed by marcbaechinger** 2023-04-07 12:22 UTC
Labels: bug
