### ISSUE TITLE
How to listen to notification bar clicks using Media3. Instead of opening an Activity

### ISSUE THREAD

**Issue by wangya123456789** [androidx/media#1916] opened 2024-11-25 16:23 UTC
Previously, you could listen to click events through broadcasting. But now it seems that you can only open Activity

**Comment by marcbaechinger** [comment] 2024-11-25 18:11
Thanks for your question!

I can confirm that since Android 13, the media notification has changed to not be the actual notification, but instead uses information from the media session instead of the actions in the notification: https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls

So starting with Android 13 you probably can't do not anymore what you did before. This is a restriction of the Android system rather a change in the media session legacy library or ours.

So if `previously` means `before Android 13` then you are correct with the statement above. So would still be able to do that on Android 12 and older, but the behavior would be different to Android 13 and above. If you want to do that, you can probably achieve this by using a custom `MeidaNotificationProvider`, but actually, I'd leave the behavior some what consistents for your user that may experience migrating their phone from 12 to 13 and then have a different behaviou. Up to you of course.

I'm closing this issue as we can't really help and I explained why. Sorry for not having a better answer. Please re-open if you think this is needed. If I interpreted your `previously` wrongly, then sorry, please elaborate on that a bit.

**Closed by marcbaechinger** 2024-11-25 18:11 UTC
Labels: question, needs triage
