### ISSUE TITLE
pause play button not working on android 13

### ISSUE THREAD

**Issue by anooravk** [androidx/media#398] opened 2023-05-16 20:37 UTC
### Media3 Version

ExoPlayer 2.18.6

### Devices that reproduce the issue

android version 13 keeps reproducing the issue were the pause button play button full screen button just doesn't work while in lower versions of android like 11 they work perfectly fine??
below is attached video of android version 13 pixel 6 api 33
https://github.com/androidx/media/assets/93789339/5609ca76-c3b5-459c-9a3f-f1e3ad8c4df7

### Devices that do not reproduce the issue

below is attached video of android version 11 pixel 4 api 30 in which all the buttons works perfectly fine 

https://github.com/androidx/media/assets/93789339/379eb94f-fa8a-4e6e-bad7-e331987b00e7

### Reproducible in the demo app?

Yes

### Reproduction steps

im trying to implement exoplayer and then taking its view to flutter via method channel, the player seems to be working perfectly fine with android version 11 but with version 13 the buttons stop working for some reason and shows no error logs

### Expected result

works on android 11 
fails on android 13

### Actual result

it does crash the video auto plays but you just cant handle anything since none of the buttons work in android 13

### Media

its a normal mp4 video im trying to play

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by anooravk** [comment] 2023-05-16 20:39
i have attached videos of both version 11 and 13

**Comment by tianyif** [comment] 2023-05-18 14:12
Hi @anooravk, I didn't reproduce the issue on the demo app with my pixel 6 on Android 13, thus I cannot tell if it is a ExoPlayer problem. I would suggest you to try such things:

1. Try different medias to filter out the cause in the media itself.
2. I noticed that in the videos you sent me, you were testing on the emulator. Could you please test the same thing on an actual Android device?
3. It's hard to say if the problem is coming from the ExoPlayer or your app or Flutter. Could you please use [`EventLogger`](https://exoplayer.dev/debug-logging.html) to check the events that the player logs?

**Comment by anooravk** [comment] 2023-05-18 14:23
i tried on physical device too but the issue still persist

**Comment by anooravk** [comment] 2023-05-18 14:41
> Hi @anooravk, I couldn't reproduce the issue on the demo app with my pixel 6 on Android 13, thus I cannot tell if it is a ExoPlayer problem. I would suggest you to try such things:
> 
> 1. Try different medias to filter out the cause in the media itself.
> 2. I noticed that in the videos you uploaded, you were testing on the emulator. Could you please test the same thing on an actual Android device?
> 3. It's hard to say if the problem is coming from the ExoPlayer or your app or Flutter. Could you please use [`EventLogger`](https://exoplayer.dev/debug-logging.html) to check the events that the player logs?

hi i am attaching the repo which have all the code im using for rendering exoplayer view in flutter which keeps giving me issues with android 13, can you please give it a look and see if the issue reproduce with you https://github.com/anooravk/native-player/tree/main

**Comment by tianyif** [comment] 2023-05-18 15:17
@anooravk Sorry we cannot give 1:1 support for solving app integration specific issues. You can test the same media with our [demo app](https://exoplayer.dev/demo-application.html). If that media works on our demo app, I think it is very likely to be a problem on how Flutter is using the ExoPlayer, which should be consulted with Flutter.

**Comment by anooravk** [comment] 2023-05-18 18:01
> @anooravk Sorry we cannot give 1:1 support for solving app integration specific issues. You can test the same media with our [demo app](https://exoplayer.dev/demo-application.html). If that media works on our demo app, I think it is very likely to be a problem on how Flutter is using the ExoPlayer, which should be consulted with Flutter.

thank you for assisting me, i'll surely look into the demo app. thank you :)

**Comment by tianyif** [comment] 2023-11-17 13:31
I'm closing this issue for now as there is no more information added. Please feel free to open an new issue if more discussion needed.

**Closed by tianyif** 2023-11-17 13:31 UTC
Labels: question

**Comment by numankaraaslan** [comment] 2024-01-12 17:22
This is happening to me to, i followed original documentation and my phone is android 13. Skip buttons are working but play and pause is just unresponsive and don't cause any player state listener triggers. It must be an interface issue. It is a serious issue that should be addressed.
