### ISSUE TITLE
Long running HLS live stream randomly produces an IndexOutOfBoundsException

### ISSUE THREAD

**Issue by etanmtv** [androidx/media#1203] opened 2024-03-20 13:24 UTC
### Version

Media3 1.3.0

Issue introduced in: Media3 1.1.0
Not reproducable with: Media3 1.0.0

### Devices that reproduce the issue

Telia TV STB + many others

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a long running live HLS stream with a 2 minute live window (the issue is very randomly reproduced)

### Expected result

Playback continues without errors

### Actual result

ExoPlayer produces a playback error:

```
java.lang.IndexOutOfBoundsException: off=-274, len=91 out of bounds (size=65536)
                                                                                                    	at java.nio.Buffer.checkBounds(Buffer.java:587)
                                                                                                    	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:162)
                                                                                                    	at androidx.media3.exoplayer.source.SampleDataQueue.readData(SampleDataQueue.java:408)
                                                                                                    	at androidx.media3.exoplayer.source.SampleDataQueue.readSampleData(SampleDataQueue.java:294)
                                                                                                    	at androidx.media3.exoplayer.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:130)
                                                                                                    	at androidx.media3.exoplayer.source.SampleQueue.read(SampleQueue.java:440)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:676)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsSampleStream.readData(HlsSampleStream.java:78)
                                                                                                    	at androidx.media3.exoplayer.BaseRenderer.readSource(BaseRenderer.java:524)
                                                                                                    	at androidx.media3.exoplayer.metadata.MetadataRenderer.readMetadata(MetadataRenderer.java:237)
                                                                                                    	at androidx.media3.exoplayer.metadata.MetadataRenderer.render(MetadataRenderer.java:169)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1102)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:541)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Media

This stream reproduces the issue:

https://csm-e-tv4se2-eb.tls1.yospace.com/csm/live/581556538.m3u8?vimondId=20315823&yo.ap=https%3A%2F%2Flive.streaming.a2d.tv%2Fysproxy%2Fhttps%3A%2F%2Fvod.streaming.a2d.tv%2Fys%2F&yo.asd=true&yo.av=3&yo.br=false&yo.fr=true&yo.me=true&yo.pdt=true&yo.t.jt=750&yo.up=https%3A%2F%2Flive.streaming.a2d.tv%2Fcmaf%2Fhttp%3A%2F%2Fvarnish-live-director.a2d.tv%2Fgroup02%2Fyospace%2Fdvrtest%2Fys.isml%2F&project=freewheel&yo.lpa=dur&t=long_form%2CTV4Play%2CNyheter+%26+debatt%2CCastens+h%C3%B6rna%2Clive%2CLive+cmaf+test+TV4%2Ctekniktest%2Csub_svod%2Cdt_mms_target_1_v3_30_days%2CSEG9791%2Cdt_mms_target_3_v3_30_days%2Cdt_mms_target_1_v3_aggressive%2Cdt_mms_target_3_v3_base%2CSEG2662%2Cdt_mms_target_1_v3_base%2Cdt_mms_target_3_v3_aggressive%2Cns_st_mv-dev%2Ctv4play.se&s=TV4Play%2FNyheter+%26+debatt%2FCastens+h%C3%B6rna%2Flive&dcid=d918a1f3-0bcc-438b-a205-b2a87ad0daf6&pid=1153490&st=0%3A0%2C20%3A1&gdpr=1&gdpr_consent=CP1YjVgP1YjVgAcABBENAaEgAAAAAAAAAChQAAAAAAGBIBgACAAFgAVAA8ACCAGQAaABEAFKAP0AxQC8wHLhAAIAGQwAIAIgAcxAAIAIgAcxwAgABAAFwAMgBfAIQAREArICkx0A8ABYAFQAQQAyADQAIgAYgBSgDRAH6ARYAxQCZAF5gMsAcuQACgAIAAyAF8ArICkyEAMABYAYgDFEoAwACAAFgBEADEAYoBeZIAMABcADIAXwCsgKTAZYUgGgALAAqACCAGQAaABEADEAKUAaIA_QCLAGKAXmA5coAFAAuABkAL4BWQDtgAAA.YAAAAAAAAAAA

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by etanmtv** [comment] 2024-04-04 12:10
This error also seems to occur on long running HLS live streams:

`androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:689)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException
                                                                                                    	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:442)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.IllegalArgumentException
                                                                                                    	at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:40)
                                                                                                    	at androidx.media3.exoplayer.source.SampleQueue.commitSample(SampleQueue.java:816)
                                                                                                    	at androidx.media3.exoplayer.source.SampleQueue.sampleMetadata(SampleQueue.java:655)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsSampleStreamWrapper$HlsSampleQueue.sampleMetadata(HlsSampleStreamWrapper.java:1781)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsSampleStreamWrapper$EmsgUnwrappingTrackOutput.sampleMetadata(HlsSampleStreamWrapper.java:1884)
                                                                                                    	at androidx.media3.extractor.mp4.FragmentedMp4Extractor.outputPendingMetadataSamples(FragmentedMp4Extractor.java:1634)
                                                                                                    	at androidx.media3.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1606)
                                                                                                    	at androidx.media3.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:463)
                                                                                                    	at androidx.media3.exoplayer.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:102)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:503)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:467)
                                                                                                    	at androidx.media3.exoplayer.hls.HlsMediaChunk.load(HlsMediaChunk.java:424)
                                                                                                    	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) `

**Comment by etanmtv** [comment] 2024-04-04 15:05
Added media URL for a stream which reproduces the issue

**Comment by etanmtv** [comment] 2024-04-04 15:09
Could be the same issue as: https://github.com/androidx/media/issues/1002

**Comment by etanmtv** [comment] 2024-04-04 15:18
Issue introduced in: Media3 1.1.0
Not reproducable with: Media3 1.0.0

**Comment by marcbaechinger** [comment] 2024-04-05 08:19
Thanks for reporting and the test stream! We will investigate this issue. As you mention it seems to be a duplicate of #1002. I will close this bug as a duplicate to have everything together in one issue. We have two streams from the same stitcher service for repro/testing.

**Closed by marcbaechinger** 2024-04-05 08:19 UTC
Labels: bug, needs triage
