### ISSUE TITLE
Communicate with Underlying MediaSessionService

### ISSUE THREAD

**Issue by dcvz** [androidx/media#664] opened 2023-09-20 20:22 UTC
I've created a Service based on `MediaSessionService` that has an instance of ExoPlayer. In my app I create `MediaController` which lets me use player methods. The question is is there any way I can from the MediaController have access to the backing PlaybackService so I can call custom methods on that instance?

Some of the preparation work I need to do for the media is not part of the standard player API exposed

**Comment by marcbaechinger** [comment] 2023-09-20 22:52
>  is is there any way I can from the MediaController have access to the backing PlaybackService
> so I can call custom methods on that instance

No, I think by design, there isn't really such a way. It would probably technically be possible, but you would probably fork the service in a way that you wouldn't be able to upgrade to another version. We also wouldn't be able to support you 1:1 for such an endeavor.

> Some of the preparation work I need to do for the media is not part of the standard player API exposed

There are quite some extension points provided by the API that possibly are useful for your case:

There is [`Callback.onAddMediaItems()/onSetMediaItems()`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)) that allow you to intercept/augment the addition of a media item. When intercepting you can also call some methods on the player before the library sets the media item.

Further you can [build your player with a custom `MediaSource.Factrory`](https://developer.android.com/guide/topics/media/exoplayer/media-sources#customizing-media-source-creation). I'm not sure what custom setup you require, but if this is on the `MediaSource` level, you can create your own factory and inject it. You can then create and return a media source that is configured in a custom way and the player would use it.

Else, you can resort to [send a custom command from the controller to the  session](https://developer.android.com/guide/topics/media/session/mediasession#adding-custom). You can receive the custom command on the session side and prepare the player how ever you like.

Besides, can you let us know what specific preparation you require? You would please my curiosity, possibly make me give you a more specific recommendation or make us think about whether your requirement is of a general value that potentially could make us change or extend the API in a useful way.

**Comment by marcbaechinger** [comment] 2023-09-21 11:55
Thanks for the details. If you want to build a new player and use it in the session, the using [Callback.onAddMediaItems()/onSetMediaItems()](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)) should IMO work. 

I haven't tried, but I can't see a reason why something like this wouldn't work. So it's worth a try:

```kotlin
override fun onAddMediaItems(
  mediaSession: MediaSession,
  controller: MediaSession.ControllerInfo,
  mediaItems: List<MediaItem>
): ListenableFuture<List<MediaItem>> {

  if (needToRebuildPlayer(mediaItems)) {
    mediaSession.player = buildForwardingPlayer();
  }
  // Let the library set the items to the player.
  return Futures.immediateFuture(updatedMediaItems)
}
```

**Comment by marcbaechinger** [comment] 2023-09-21 12:06
Ah, I see. 3rd party apps are accessing the service that is provided by a library.

From your initial suggestion of providing an additional service method to controllers, it looks like you trust the controllers. What would be the circumstances under which you have envisioned  the controller would call this extra method on the service?

Can the service know from the type of media item that is sent whether the player needs a special setup? And if not, can the controller mark the media item somehow so that `needToRebuildPlayer` can take this decision? They could use `MediaItem.requestMetadata.extras` to send some context info to the service?

**Comment by marcbaechinger** [comment] 2023-09-24 14:34
> I was hoping to offload some of that work over to the new APIs 

Yeah, this is the idea of the services of Media3. You should build and inovate within your app domain, not tinker around with service infrastructure.

I think if you want to get happy with Media3 services, then it is worth moving a bit into the direction of the design of these services. That makes it most likely you can benefit from it. Else it can be you struggle a bit inbetween your design ideas and what Media3 is doing.

What I mean is that you move your clients to use a `MediaController`. If they should start the service, this is the official way to start the service. I think if you don't do a change in your approach, you should probably not try to bend `MediaSessionService` too much. 

If you want to have a hard way, then you can use `MediaSessionService` and for instance override it's `onBind` method. Totally possible, and totally not recommended. This lets you change everything, but mostly it also will create you probably as much effort as you have with your own service except that you do not own it. :) I wouldn't go that route.

> but how do you tell the service your user changed their settings 

I think if you want to stick with a custom method on a binder interface that you share with your client, you probably want to stick with what you are doing already with your custom service implementation. Media3 will never offer a two-way binder API for instance. If you are fine to use the existing extension points provided with Media3 and you are easy to wrap some of your logic around a generic interface like custom commands and help here in the community to bring the services to closer what you intend to do with them, then I think you can save lots of time with using `MediaSessionService`/`MediaLibraryService` and have influence here. You have quite some service know-how that allows you to yell and tell, and make us push Media3 services forward to make then better. This post was a good start already. Thank you for your input.

You can easily build a typed API around a custom command so that your users still think they are using your API, but under the hood you leverage Media3 infra instead of coding your own.

I don't see a reason why you can't do what you want with Media3 APIs except that you need to say good by to some design decisions and approaches you have stick with for probably a while.

I'd be glad to see you become a happy Media3 users of course! I'm closing this issue for now as it seems like answered.
Please open a new issue if you have some further questions or want to suggest a change.

**Closed by marcbaechinger** 2023-09-24 14:34 UTC
Labels: question
