### ISSUE TITLE
Sometimes generate TransactionTooLargeException

### ISSUE THREAD

**Issue by XuQK** [androidx/media#94] opened 2022-06-23 07:37 UTC
### Media3 Version

1.0.0-beta01

### Devices that reproduce the issue

Samsung galaxy note 10 5G running Android 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

Just call `MediaController.setMediaItems(List<MediaItem> mediaItems, int startIndex, long startPositionMs)`

### Expected result

normal set

### Actual result

```
2022-06-23 15:29:51.717 24213-24213/
 W/MSImplBase: Exception in ControllerInfo {pkg=, uid=10526})
      android.os.TransactionTooLargeException: data parcel size 443252 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:605)
        at androidx.media3.session.IMediaController$Stub$Proxy.onPlayerInfoChanged(IMediaController.java:491)
        at androidx.media3.session.MediaSessionStub$Controller2Cb.onPlayerInfoChanged(MediaSessionStub.java:1723)
        at androidx.media3.session.MediaSessionImpl.dispatchOnPlayerInfoChanged(MediaSessionImpl.java:400)
        at androidx.media3.session.MediaSessionImpl.access$600(MediaSessionImpl.java:79)
        at androidx.media3.session.MediaSessionImpl$PlayerInfoChangedHandler.handleMessage(MediaSessionImpl.java:1193)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-06-23 09:15
Can you shed some light on what you are doing when this happens? How many media items are you setting? What properties of the media items/metadata do you set?

**Comment by XuQK** [comment] 2022-06-30 03:36
I found something new.
when this happens, `controller.isConnected` is true, but `controller.isPlaying` is false, actually the song is playing, and `controller.currentPosition` is continued to increase.
The player service is Running another process, not default process.

**Comment by XuQK** [comment] 2022-07-04 09:25
I may have found the reason, maybe the notification bitmap from SimpleBitmapLoader is too big.
I added a sampling process at the end of `SimpleBitmapLoader.decode(bitmap: Bitmap)` method, the error I described above has never appeared so far.

**Comment by marcbaechinger** [comment] 2022-09-30 18:53
I'm not aware that the bitmap loaded by the `SimpleBitmapLoader` is put into the metadata by the library. I would avoid doing that as an app given the problem above. 

We have #168 that is about providing a high-res bitmap for the notification. After this is fixed, there should be no need to put binary data into the metadata which seems to avoid the problems described here. I'm closing this as a duplicate of #168.

**Closed by marcbaechinger** 2022-09-30 18:53 UTC
Labels: bug
