### ISSUE TITLE
Crash when changing media item in background

### ISSUE THREAD

**Issue by AndrazP** [androidx/media#240] opened 2023-01-06 16:25 UTC
There are already open issues regarding`ForegroundServiceDidNotStartInTimeException`  https://github.com/androidx/media/issues/167 https://github.com/androidx/media/issues/111

I'm creating a new issue because we have clear steps to reproduce the crash, 100% of the time.
Our implementation has NO custom media button receiver or audio focus logic, what other issues suggest.

### Reproduction steps:
- Use Android device running Android 12 or newer
- Start playback
- Move app to the background. Go to device home screen, turning screen off is not enough.
- When first audio file ends, start playing a new file.

### Expected result
The new audio file continues playing.

### Actual result
Crash.
```
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.example.debug/com.example.player.service.PlayerService
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
at android.os.Parcel.readParcelable(Parcel.java:3346)
at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
at android.os.Parcel.createException(Parcel.java:2422)
at android.os.Parcel.readException(Parcel.java:2405)
at android.os.Parcel.readException(Parcel.java:2347)
at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6969)
at java.lang.reflect.Method.invoke(Native Method)
at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy3.startService(Unknown Source)
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1927)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1893)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:798)
at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1091)
at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:749)
at androidx.media3.session.MediaNotificationManager.updateNotificationInternal(MediaNotificationManager.java:206)
at androidx.media3.session.MediaNotificationManager.updateNotification(MediaNotificationManager.java:182)
at androidx.media3.session.MediaSessionService.onUpdateNotification(MediaSessionService.java:411)
at androidx.media3.session.MediaNotificationManager$MediaControllerListener.onEvents(MediaNotificationManager.java:299)
at androidx.media3.session.MediaControllerImplBase.lambda$new$0$androidx-media3-session-MediaControllerImplBase(MediaControllerImplBase.java:151)
at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda60.invoke(Unknown Source:4)
at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:295)
at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:246)
at androidx.media3.common.util.ListenerSet.$r8$lambda$bio3pd12v5B_9b5UeFaPn9XBQ90(Unknown Source:0)
at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:771)
at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:679)
at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:14102)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2960)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3036)
```

### Code
Unfortunately, I'm not able to share a working demo. 
Here are all the important [code snippets](https://gist.github.com/AndrazP/9e3e70942900f418884dd5b2de705655).
When one audio file ends, we on the fly decide which is next and play it by calling.
`PlayerController.play(mediaItem: MediaItem, startFromBeginning: Boolean)`

### Media3 Version
1.0.0-beta02, 1.0.0-beta03

### Devices that reproduce the issue
Android 12 and newer.
- Google Pixel 6, 7 running Android 13
- Samsung a52s running Android 12

### Devices that do not reproduce the issue
Android 11 and older.
- Nexus 5x running Android 8.1

**Comment by marcbaechinger** [comment] 2023-01-06 17:17
Thanks for reporting.

```
1. Use Android device running Android 12 or newer
2. Start playback
3. Move app to the background. Go to device home screen, turning screen off is not enough.
4. When first audio file ends, start playing a new file.
```

In general when the activity goes to the background, the controller should be released. 

I assume `PlayerController.play(mediaItem: MediaItem, startFromBeginning: Boolean)` is called from the activity when in the background and this is generally not a good idea. I think that's the reason why we have foreground services. Your user wants to know when something is going on when the app is not visible - the foreground service needs a notification for this reason. I recommend moving this code of `deciding on the fly` to the service. You may want to do that decision when the activity has been terminated too, and the service is running 'standalone' (I see you prevent this in `onTaskRemove` but still :)).

However, this wouldn't work either as you would run into the same `ForegroundServiceStartNotAllowedException` when doing this in the service the way it is done now.

I think you can solve this by doing:

1. Move the code that sets the newly selected item to the service. You should in general never call code in an activity when the activity is in the background. In media specific term, you should [release the `MediaController` in `onStop` of the activity](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/PlayerActivity.kt#L101).
2. The when you set the new media item you need to be careful to not pause the player but instead keep it playing. The service is taken off the foreground when `pause()` or `setPlayWhenReady(false)` is called and put into the foreground again when playback is resumed. Because resuming is only allowed when you are in the foreground you should set your new item without pausing and you should be able to work around this problem.

**Comment by AndrazP** [comment] 2023-01-11 09:52
Thanks for your quick reply.

> Move the code that sets the newly selected item to the service. ....

We are already keeping this logic and `MediaController` out of the activity because [MediaController documentation states](https://github.com/androidx/media/blob/c2cbb6370a265efc93661b659e70b2679506e995/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L204) :
`The controller will bind to the service as long as it's connected to wake up and keep the service process running.`

> Then when you set the new media item you need to be careful to not pause the player but instead keep it playing.

We are not stopping or pausing, we immediately set and play a new `MediaItem`.

I took a look at Media3 internals and found [MediaNotificationManager.updateNotificationInternal](https://github.com/androidx/media/blob/c2cbb6370a265efc93661b659e70b2679506e995/libraries/session/src/main/java/androidx/media3/session/MediaNotificationManager.java#L192)
Pausing and playing playback from notification controls executes the same code as setting a new media item when one is finished, without a crash:
- `Api24.stopForeground`
- `ContextCompat.startForegroundService` and `Api29.startForeground`

But in our case `ContextCompat.startForegroundService` crashes with `ForegroundServiceStartNotAllowedException`
Why? Is there another piece of code I missed?

**Comment by marcbaechinger** [comment] 2023-01-11 10:26
> For example pausing and playing playback from notification controls executes the same code as setting a 
> new media item when one is finished, without a crash:
> Why? Is there another piece of code I missed?

Because you need to be in the foreground when the service is put into the foreground.

The notification (SystemUI) gets an exemption by the system either by `PendingIntent` (Android 12  or targetSdk below 33) or by the media session call (Android 13 with target SDK 33). When you grep your logcat for what `ActivivtyManager` says on Android 12 you'll find a log telling about the exemption:

```
2022-10-24 18:05:17.131  1775-1812  ActivityManager         system_process                       I  Background started 
FGS: Allowed [callingPackage: androidx.media3.demo.session; callingUid: 10317; uidState: FGS ; intent: Intent { cmp=androidx.media3.demo.session/.PlaybackService }; code:PROC_STATE_FGS; tempAllowListReason:<null>; targetSdkVersion:30; callerTargetSdkVersion:30; startForegroundCount:0; bindFromPackage:null]
```

You app does not get such an exemption. 

> We are already keeping this logic and MediaController out of the activity because [MediaController documentation states](https://github.com/androidx/media/blob/c2cbb6370a265efc93661b659e70b2679506e995/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L204) :
The controller will bind to the service as long as it's connected to wake up and keep the service process running.

Being bound to the service prevents the service from being terminated when idle only. That's true but the restriction regarding putting the service in the foreground still exists whether you are bound to it or not doesn't make a difference. 

> I took a look at Media3 internals and found [MediaNotificationManager.updateNotificationInternal](https://github.com/androidx/media/blob/c2cbb6370a265efc93661b659e70b2679506e995/libraries/session/src/main/java/androidx/media3/session/MediaNotificationManager.java#L192)

You are digging at the right place. You may have found the method `shouldRunInForeground` which defines the condition when the service is taken off the foreground or put into the foreground. If you make sure that the player does not fall into `STATE_ENDED` or `STATE_IDLE` and if you do not pause the player, the service is kept in the foreground and you don't run into this issue.

```
  private static boolean shouldRunInForeground(Player player) {
    return player.getPlayWhenReady()
        && (player.getPlaybackState() == Player.STATE_READY
            || player.getPlaybackState() == Player.STATE_BUFFERING);
  }
```

I can't see a library issue here I'm afraid and I don't this this is a new case when looking at other reports we had here on the issue tracker. I appreciate it's a tricky beast, but I think your issue is not caused by a bug in the library, but is behaving as expected. Your app somehow causes the service to get off and back into the foreground as per the condition in the above method.

I'm closing this issue because we already have #111 and this is either an app issue or a duplicate of #111. I think it makes sense to keep things together. If you think your issue is a bug in the library or in the framework, please continue posting to the other issue. You can also re-open this issue if you think I'm wrong.

**Closed by marcbaechinger** 2023-01-11 10:26 UTC
Labels: question

**Comment by AndrazP** [comment] 2023-01-11 10:42
Thanks for the detailed explanation. All clear, it's intended behavior. I see some ways around it.
I just suggest documenting it better, for example in [Play media in the background](https://developer.android.com/guide/topics/media/media3/getting-started/playing-in-background) article.
