### ISSUE TITLE
how to cancel notification when player is paused and you close the app?

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#269] opened 2023-03-14 12:41 UTC
when i press pause and close the app, notification still visible but controls isnt working. how to cancel notification in code in this situation.

**Comment by marcbaechinger** [comment] 2023-03-14 16:54
> notification still visible but controls isnt working

I think this is a duplicate of #175. You have probably the same issue as the demo app had. 
[This comment](https://github.com/androidx/media/issues/175#issuecomment-1262025281) let's you verify whether you have the same problem.

There are several ways to cancel the notification. One of it is stopping the player. I think in your case you want to stop the service when the app is terminated. You can do this like what we added to the service of the demo app with [this commit](https://github.com/androidx/media/commit/868e86cd3f6e13d1ef033956f6deab9c4e46c8c1). Please make sure that all your controllers than are bound to the service are released. If this is not the case, `stopSelf` will not work. In such a case you have to release the session first.

I'm closing this issue as a duplicate.

Please let me know if this is not the case and then please reopen this issue. If you do that please also add some more info to your question which is mostly about on what API level you see this problem and what version of the library you are using. That's useful for us and is included in the bug report the template you removed is mentioning.

**Closed by marcbaechinger** 2023-03-14 16:54 UTC
Labels: question

**Comment by graymind75** [comment] 2023-05-02 00:31
@marcbaechinger
Hi, I'm facing the same problem with Android 13 and It's driving me crazy!
The strange thing is, If I let player to play, the `onTaskRemoved` called on app being killed
But If I pause the player, `onTaskRemoved` or `onDestroy` never called from the `PlaybackService`
I've sent logcat output to the `dev.exoplayer@gmail.com` with my `PlaybackService` titled `Issue #269`

I really appreciate for any solution.
Thanks.

**Comment by marcbaechinger** [comment] 2023-05-02 12:40
@graymind75

It looks like the app in question is having other services that crashes. Can you verify these services behave as expected and do not have side effects when they crash? 

I'd say `MediaSessionService` and the session demo app is fine and is working as intended. I also think that the implementation of your `PlaybackService` looks fine but it seems that another service  of the app interferes and crashes the app. 

In the log snipppets below I replaced your app package name with `com.example`. 

My guess is that the crash of the other service prevents `onTaskRemoved` to be called correctly. In general, a crash seems to cause the app not being terminated as intended (`onDestroy()` not called). I have no indications that this is related to `MediaSessionService/MediaLibraryService` or the session demo implementation though.

The entire log file has four lines for the service in question and it shows that there is a problem with starting/stopping because it is not started/stopped in the same process as expected:

```
vendor.qti....2-service startService() is called for servicecom.example/.data.remote.ping.DomainPingService
---------------------------- PROCESS ENDED (22407) for package com.example ----------------------------
ActivityManager         Scheduling restart of crashed service com.example/.data.remote.ping.DomainPingService in 1000ms for start-requested
vendor.qti....2-service startService() is called for servicecom.example/.data.remote.ping.DomainPingService
---------------------------- PROCESS STARTED (23905) for package com.example ----------------------------
vendor.qti....2-service destroyService is called for service : com.example/.data.remote.ping.DomainPingService
```

These are the logs for the failed termination of your app. A crashed service causes problems, but I doubt its the media service.

```
[...]
ActivityManager         Killing 22407:com.example/u0a559 (adj 0): SwipeUpClean
[...]
---------------------------- PROCESS ENDED (22407) for package com.example ----------------------------
ActivityManager         Scheduling restart of crashed service com.example/.data.remote.ping.DomainPingService in 1000ms for start-requested
ActivityManager         Cancel FGS notification userId: 0 definingUid: 10559 packageName: com.example processName:com.example ChannelId:default_channel_id foregroundNotiWhen:-9223372036854775807 Notiflags:8
ActivityManager         Scheduling restart of crashed service com.example/.player.PlaybackService in 10998ms for start-requested
UsageStatsService       Unexpected activity event reported! (com.example/com.example.ui.views.activity_main.MainActivity event : 23 instanceId : 33400148)
[...]
ActivityManager         Start proc 23905:com.example/u0a559 for service {com.example/androidx.work.impl.background.systemjob.SystemJobService} caller=android
vendor.qti....2-service startService() is called for servicecom.example/.data.remote.ping.DomainPingService
vendor.qti....2-service startService() is called for servicecom.example/.player.PlaybackService
```

This is the log of the demo app on API 33. When everything works fine, these lines come before the ` PROCESS ENDED `  marker in logcat.

```
2023-05-02 13:02:38.178 21249-21249 ExoPlayerImpl           androidx.media3.demo.session         I  Init 5edb41b [AndroidXMedia3/1.0.1] [emu64x, sdk_gphone64_x86_64, Google, 33]
[...]
2023-05-02 13:03:20.491 21249-21249 ExoPlayerImpl           androidx.media3.demo.session         I  Release 5edb41b [AndroidXMedia3/1.0.1] [emu64x, sdk_gphone64_x86_64, Google, 33] [media3.common, media3.exoplayer, media3.decoder, media3.session, media3.datasource, media3.ui, media3.extractor]
2023-05-02 13:03:20.652   644-2503  ActivityManager         system_process                       I  Killing 21249:androidx.media3.demo.session/u0a159 (adj 1001): remove task
```

**Comment by graymind75** [comment] 2023-05-02 19:11
@marcbaechinger 
Yes, Android still tries to restart the service.
Could you explain what you mean by a full bug report? Do I have to create a new Issue?

Thank you for being so supportive.

**Comment by graymind75** [comment] 2023-05-04 20:45
@marcbaechinger 
I sent an email with the bug report attached.

**Comment by marcbaechinger** [comment] 2023-05-05 10:59
I see only the email from May 2nd, I'm afraid. Can you send it again?

**Comment by graymind75** [comment] 2023-05-05 12:42
@marcbaechinger 
Sorry, I've sent it again.
