### ISSUE TITLE
NullPointerException in AudioPortEventHandler$1.handleMessage

### ISSUE THREAD

**Issue by hakonschia** [androidx/media#749] opened 2023-10-20 06:23 UTC
### Version

Media3 1.1.1

### Devices that reproduce the issue

Only on Android TV. 99 % is Android 10, the rest is Android 9.

This is mostly happening on set-top boxes that might be somewhat local to Norway, and 88 % is on one specific box. I've attempted to reproduce it on that box without any luck.

![chrome_2a0RTAlw2N](https://github.com/androidx/media/assets/33124564/de15d032-0f77-4d0f-8bcd-75df3a78e198)

### Reproducible in the demo app?

Not tested

### Reproduction steps

I can't reproduce this myself, only seeing crashes through Firebase

I'm not sure if this issue belongs to media3 or not, but this crash started happening when migrating from ExoPlayer (2.18.6) to media3 (1.1.0, and still happening on 1.1.1), and there isn't anything else related to media that we changed in that release. If you can tell that this is clearly not related to media3 then closing the issue is OK.

### Expected result

Media plays without crashing

### Actual result

App sometimes crashes with the stack trace (I realise that this might not be a lot to go off):

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.media.AudioManager$OnAudioPortUpdateListener.onAudioPatchListUpdate(android.media.AudioPatch[])' on a null object reference
       at android.media.AudioPortEventHandler$1.handleMessage(AudioPortEventHandler.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

It's happening a decent amount:

![chrome_IUzHovVUxW](https://github.com/androidx/media/assets/33124564/f27147bf-2ab3-4cd7-ae1b-273924ef746c)

### Media

I'm not sure if there are specific conditions for what media causes a crash.

Here is a URL to a HLS playlist that has crashed: https://nrk-od2.telenorcdn.net/open/ps/muhh/muhh26000918/17dbf731-1.smil/cmaf.m3u8?adap=large

This URL might not be available forever, but here's the content of it as of writing:

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS

# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud4",LANGUAGE="un",NAME="Unknown",CHANNELS="2",AUTOSELECT=YES,DEFAULT=YES,URI="sc-gaFEQg/A3_index.m3u8?adap=large"

# SUBTITLES groups
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="sub1",LANGUAGE="no",NAME="Norsk",AUTOSELECT=YES,DEFAULT=YES,URI="sc-gaFEQg/s0_index.m3u8?adap=large"

# Variants
#EXT-X-STREAM-INF:BANDWIDTH=2979537,AVERAGE-BANDWIDTH=2373451,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000,AUDIO="aud4",SUBTITLES="sub1"
sc-gaFEQg/V4_index.m3u8?adap=large
#EXT-X-STREAM-INF:BANDWIDTH=1749537,AVERAGE-BANDWIDTH=1410362,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=25.000,AUDIO="aud4",SUBTITLES="sub1"
sc-gaFEQg/V3_index.m3u8?adap=large
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2023-10-20 09:12
This looks like a duplicate of internal b/169729472. The non-TV fix is here: https://cs.android.com/android/_/android/platform/frameworks/base/+/f3a10cd2445ed535e519abb0206b47028dcf8ae2

This was cherry-picked into TV specific branch in internal ag/12736435.

I'm afraid there's nothing we can do about this at the library level so I'm going to close this.

**Closed by icbaker** 2023-10-20 09:12 UTC
Labels: bug, needs triage
