### ISSUE TITLE
Crash issue when trying to use PlayerView

### ISSUE THREAD

**Issue by openxcellpooja** [androidx/media#1926] opened 2024-11-29 07:09 UTC
### Version

Media3 1.4.1

### Devices that reproduce the issue

Pixel 6 Pro Android 12
Model:Galaxy S20+ 5G Android 9

### Devices that do not reproduce the issue

Pixel 8 Pro Android 15

### Reproducible in the demo app?

No

### Reproduction steps

It's happening in Live build.

![Screenshot 2024-11-29 at 12 36 00 PM](https://github.com/user-attachments/assets/58b76e6d-c5eb-4947-a15f-26eb358f1125)

![Screenshot 2024-11-29 at 12 34 12 PM](https://github.com/user-attachments/assets/8eeef1f5-0ac2-415d-8921-75349922c8a1)

<androidx.media3.ui.PlayerView
                        android:id="@+id/playerView"
                        android:layout_width="@dimen/_300sdp"
                        android:layout_height="@dimen/_300sdp"
                        android:layout_marginTop="@dimen/_10sdp"
                        android:layout_marginBottom="@dimen/_10sdp"
                        android:keepScreenOn="true"
                        android:visibility="visible"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/icTagLine"
                        app:show_subtitle_button="true"
                        app:surface_type="texture_view"
                        app:use_controller="false" />

### Expected result

App should play video

### Actual result

App crash

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2024-11-29 09:31
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/10409, which is caused by partial sideloading of app bundles. This would explain why you're only seeing it in telemetry from the field and are unable to reproduce it locally.

**Closed by icbaker** 2024-11-29 09:31 UTC
Labels: bug, needs triage
