### ISSUE TITLE
Unexpected error occurred when play Ad

### ISSUE THREAD

**Issue by chladto1** [androidx/media#537] opened 2023-07-21 06:05 UTC
### Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

Any

### Reproducible in the demo app?

Yes

### Reproduction steps

Replace line 532 in `DefaultMediaSourceFactory` with the following.

```
        new DataSpec(Util.getDataUriForString("text/xml", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><vmap:VMAP xmlns:vmap=\"http://www.iab.net/videosuite/vmap\" version=\"1.0\">\n"
            + "  <vmap:AdBreak timeOffset=\"start\" breakType=\"linear\" breakId=\"preroll\">\n"
            + "    <vmap:AdSource id=\"preroll-ad-0\" allowMultipleAds=\"true\" followRedirects=\"true\">\n"
            + "      <vmap:AdTagURI templateType=\"vast3\">https://ad.doubleclick.net/ddm/pfadx/N703922.1534589IPRIMA.CZ/B30145407.369534207;sz=0x0;ord=%%VIEWID%%;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dc_tdv=1;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER];dc_vast=4;dc_mpos=[BREAKPOSITION];ltd=</vmap:AdTagURI>\n"
            + "    </vmap:AdSource>\n"
            + "  </vmap:AdBreak>\n"
            + "</vmap:VMAP>")),
```

### Expected result

Play ad.

### Actual result

Ad is skipped with error 900 and IMA extension failed on internal error.

Stacktrace:
```
2023-07-21 07:52:13.686 ActivityThread           W  handleWindowVisibility: no activity for token android.os.BinderProxy@521941
2023-07-21 07:52:13.839 ExoPlayerImpl            I  Init 8a180f2 [ExoPlayerLib/2.18.4] [generic_x86, Android SDK built for x86, Google, 29]
2023-07-21 07:52:13.847 EventLogger              D  playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
2023-07-21 07:52:13.850 EventLogger              D  surfaceSize [eventTime=0.00, mediaPos=0.00, window=0, 0, 0]
2023-07-21 07:52:13.857 EventLogger              D  timeline [eventTime=0.01, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2023-07-21 07:52:13.857 EventLogger              D    period [?]
2023-07-21 07:52:13.857 EventLogger              D    window [?, seekable=false, dynamic=true]
2023-07-21 07:52:13.857 EventLogger              D  ]
2023-07-21 07:52:13.858 EventLogger              D  mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
2023-07-21 07:52:13.862 EventLogger              D  state [eventTime=0.02, mediaPos=0.00, window=0, BUFFERING]
2023-07-21 07:52:13.917 EventLogger              D  surfaceSize [eventTime=0.07, mediaPos=0.00, window=0, 1080, 1731]
2023-07-21 07:52:13.935 EGL_emulation            D  eglMakeCurrent: 0xf7053680: ver 2 0 (tinfo 0xf7089a30)
2023-07-21 07:52:13.962 EGL_emulation            D  eglMakeCurrent: 0xf7053680: ver 2 0 (tinfo 0xf7089a30)
2023-07-21 07:52:14.013 exoplayer2.dem           W  Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
2023-07-21 07:52:14.019 GASS                     D  Clearcut logging disabled
2023-07-21 07:52:14.020 EventLogger              D  loading [eventTime=0.17, mediaPos=0.00, window=0, period=0, true]
2023-07-21 07:52:14.055 EGL_emulation            D  eglMakeCurrent: 0xf7053680: ver 2 0 (tinfo 0xf7089a30)
2023-07-21 07:52:14.173 eglCodecCommon           D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-07-21 07:52:14.173 EGL_emulation            D  eglCreateContext: 0xc66c14e0: maj 2 min 0 rcv 2
2023-07-21 07:52:14.174 EGL_emulation            D  eglMakeCurrent: 0xc66c14e0: ver 2 0 (tinfo 0xc8683af0)
2023-07-21 07:52:14.178 eglCodecCommon           D  setVertexArrayObject: set vao to 1 (1) 0 0
2023-07-21 07:52:14.187 EGL_emulation            D  eglMakeCurrent: 0xe07c3c80: ver 2 0 (tinfo 0xc8683af0)
2023-07-21 07:52:14.253 chromium                 I  [INFO:CONSOLE(1141)] " [  0.001s] [ima.NativeBridge] OMID measurement with OM SDK SessionClient version 1.4.5-google_20230606 is ready. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.290 chromium                 I  [INFO:CONSOLE(1141)] " [  0.041s] [ima.loader.AdsLoaderImpl] Requesting ads using new ads loader. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.290 chromium                 I  [INFO:CONSOLE(1141)] " [  0.041s] [ima.loader.AdsLoaderImpl] requestAds, processing external request. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.290 chromium                 I  [INFO:CONSOLE(1141)] " [  0.042s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.290 chromium                 I  [INFO:CONSOLE(1141)] " [  0.042s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.293 chromium                 I  [INFO:CONSOLE(1141)] " [  0.042s] [ima.loader.AdXmlFetcher] Using adsRequest.adsResponse for ad load. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.295 chromium                 I  [INFO:CONSOLE(1141)] " [  0.047s] [ima.loader.AdXmlFetcher] Creating AdsRequestsMap. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.298 chromium                 I  [INFO:CONSOLE(1141)] " [  0.050s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.341 AdTagLoader              D  Content progress: not ready
2023-07-21 07:52:14.350 EventLogger              D  timeline [eventTime=0.50, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2023-07-21 07:52:14.350 EventLogger              D    period [?]
2023-07-21 07:52:14.350 EventLogger              D    window [?, seekable=false, dynamic=false]
2023-07-21 07:52:14.350 EventLogger              D  ]
2023-07-21 07:52:14.351 AdTagLoader              D  Content progress: not ready
2023-07-21 07:52:14.352 AdTagLoader              D  Initialized with ads rendering settings: com.google.ads.interactivemedia.v3.impl.data.g@c1a74643
2023-07-21 07:52:14.361 EventLogger              D  timeline [eventTime=0.52, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2023-07-21 07:52:14.361 EventLogger              D    period [?]
2023-07-21 07:52:14.362 EventLogger              D    window [?, seekable=false, dynamic=false]
2023-07-21 07:52:14.362 EventLogger              D  ]
2023-07-21 07:52:14.368 chromium                 I  [INFO:CONSOLE(1141)] " [  0.120s] [ima.loader.AdsLoaderImpl] requestAds, processing internal request. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.368 chromium                 I  [INFO:CONSOLE(1141)] " [  0.120s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.369 chromium                 I  [INFO:CONSOLE(1141)] " [  0.120s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.371 chromium                 I  [INFO:CONSOLE(1141)] " [  0.122s] [ima.loader.AdsManagerChannel] Error while processing a message URIError: URI malformed
                                                        at decodeURI (<anonymous>)
                                                        at aA (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:393:178)
                                                        at new L (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:388:518)
                                                        at YT (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:781:611)
                                                        at Pba (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1340:44)
                                                        at https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1339:725
                                                        at i$ (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1340:9)
                                                        at j$ (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1339:772)
                                                        at Caa (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1341:385)
                                                        at A7 (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1174:64) ", source: https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js (1141)
2023-07-21 07:52:14.391 IMASDK                   E  JsMessage (ima.loader.AdsManagerChannel): Error while processing a message URIError: URI malformed
                                                        at decodeURI (<anonymous>)
                                                        at aA (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:393:178)
                                                        at new L (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:388:518)
                                                        at YT (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:781:611)
                                                        at Pba (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1340:44)
                                                        at https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1339:725
                                                        at i$ (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1340:9)
                                                        at j$ (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1339:772)
                                                        at Caa (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1341:385)
                                                        at A7 (https://imasdk.googleapis.com/native/core/3.363.4/native_bridge_debug__en.js:1174:64)
2023-07-21 07:52:14.403 AdTagLoader              D  onAdError
                                                      AdError [errorType: PLAY, errorCode: AdErrorCode [name: UNKNOWN_ERROR, number: 900], message: An unexpected error occurred and the cause is not known. Refer to the inner error for more info. Caused by: URIError: URI malformed]
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.f(IMASDK:1)
                                                          at com.google.ads.interactivemedia.v3.internal.ajx.k(IMASDK:52)
                                                          at com.google.ads.interactivemedia.v3.internal.ake.f(IMASDK:6)
                                                          at com.google.ads.interactivemedia.v3.internal.aka.onPostMessage(IMASDK:2)
                                                          at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:54)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                          at $Proxy2.onPostMessage(Unknown Source)
                                                          at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(Unknown Source:50)
                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                          at android.os.MessageQueue.next(MessageQueue.java:336)
                                                          at android.os.Looper.loop(Looper.java:174)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2023-07-21 07:52:14.403 AdTagLoader              D  Removing ad 0 in ad group 0
2023-07-21 07:52:14.405 AdTagLoader              D  onAdEvent: ALL_ADS_COMPLETED
2023-07-21 07:52:14.413 EventLogger              E  internalError [eventTime=0.56, mediaPos=0.00, window=0, loadError
                                                      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: java.io.IOException: Failed to load ad group 0
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.handleAdGroupLoadError(AdTagLoader.java:1092)
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.access$1000(AdTagLoader.java:81)
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader$ComponentListener.onAdError(AdTagLoader.java:1422)
                                                          at com.google.ads.interactivemedia.v3.internal.ajj.c(IMASDK:2)
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.o(IMASDK:1)
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.f(IMASDK:2)
                                                          at com.google.ads.interactivemedia.v3.internal.ajx.k(IMASDK:52)
                                                          at com.google.ads.interactivemedia.v3.internal.ake.f(IMASDK:6)
                                                          at com.google.ads.interactivemedia.v3.internal.aka.onPostMessage(IMASDK:2)
                                                          at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:54)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                          at $Proxy2.onPostMessage(Unknown Source)
                                                          at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(Unknown Source:50)
                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                          at android.os.MessageQueue.next(MessageQueue.java:336)
                                                          at android.os.Looper.loop(Looper.java:174)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                                                      Caused by: java.io.IOException: Failed to load ad group 0
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.handleAdGroupLoadError(AdTagLoader.java:1092) 
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.access$1000(AdTagLoader.java:81) 
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader$ComponentListener.onAdError(AdTagLoader.java:1422) 
                                                          at com.google.ads.interactivemedia.v3.internal.ajj.c(IMASDK:2) 
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.o(IMASDK:1) 
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.f(IMASDK:2) 
                                                          at com.google.ads.interactivemedia.v3.internal.ajx.k(IMASDK:52) 
                                                          at com.google.ads.interactivemedia.v3.internal.ake.f(IMASDK:6) 
                                                          at com.google.ads.interactivemedia.v3.internal.aka.onPostMessage(IMASDK:2) 
                                                          at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:54) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162) 
                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
                                                          at $Proxy2.onPostMessage(Unknown Source) 
                                                          at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(Unknown Source:50) 
                                                          at android.os.MessageQueue.nativePollOnce(Native Method) 
                                                          at android.os.MessageQueue.next(MessageQueue.java:336) 
                                                          at android.os.Looper.loop(Looper.java:174) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:7356) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
                                                      Caused by: AdError [errorType: PLAY, errorCode: AdErrorCode [name: UNKNOWN_ERROR, number: 900], message: An unexpected error occurred and the cause is not known. Refer to the inner error for more info. Caused by: URIError: URI malformed]
                                                          at com.google.ads.interactivemedia.v3.internal.ajc.f(IMASDK:1)
                                                          at com.google.ads.interactivemedia.v3.internal.ajx.k(IMASDK:52) 
                                                          at com.google.ads.interactivemedia.v3.internal.ake.f(IMASDK:6) 
                                                          at com.google.ads.interactivemedia.v3.internal.aka.onPostMessage(IMASDK:2) 
                                                          at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:54) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162) 
                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
                                                          at $Proxy2.onPostMessage(Unknown Source) 
                                                          at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(Unknown Source:50) 
                                                          at android.os.MessageQueue.nativePollOnce(Native Method) 
                                                          at android.os.MessageQueue.next(MessageQueue.java:336) 
                                                          at android.os.Looper.loop(Looper.java:174) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:7356) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
                                                    ]
2023-07-21 07:52:14.416 EventLogger              D  timeline [eventTime=0.57, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2023-07-21 07:52:14.416 EventLogger              D    period [?]
2023-07-21 07:52:14.416 EventLogger              D    window [?, seekable=false, dynamic=false]
2023-07-21 07:52:14.416 EventLogger              D  ]
2023-07-21 07:52:14.416 AdTagLoader              W  onEnded without ad media info
2023-07-21 07:52:14.863 EventLogger              D  timeline [eventTime=1.02, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2023-07-21 07:52:14.863 EventLogger              D    period [128.27]
2023-07-21 07:52:14.864 EventLogger              D    window [128.27, seekable=true, dynamic=false]
2023-07-21 07:52:14.864 EventLogger              D  ]
2023-07-21 07:52:14.867 EventLogger              D  videoEnabled [eventTime=1.02, mediaPos=0.00, window=0, period=0]
2023-07-21 07:52:14.868 EventLogger              D  audioEnabled [eventTime=1.02, mediaPos=0.00, window=0, period=0]
2023-07-21 07:52:14.870 EventLogger              D  tracks [eventTime=1.02, mediaPos=0.00, window=0, period=0
2023-07-21 07:52:14.870 EventLogger              D    group [
2023-07-21 07:52:14.870 EventLogger              D      [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720, language=en, selectionFlags=[default], supported=YES
2023-07-21 07:52:14.870 EventLogger              D    ]
2023-07-21 07:52:14.870 EventLogger              D    group [
2023-07-21 07:52:14.870 EventLogger              D      [X] Track:0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=und, selectionFlags=[default], supported=YES
2023-07-21 07:52:14.870 EventLogger              D    ]
2023-07-21 07:52:14.870 EventLogger              D  ]
2023-07-21 07:52:14.871 OMXClient                I  IOmx service obtained
2023-07-21 07:52:14.873 SurfaceUtils             D  connecting to surface 0xc8c47808, reason connectToSurface
2023-07-21 07:52:14.873 MediaCodec               I  [OMX.google.h264.decoder] setting surface generation to 11167747
2023-07-21 07:52:14.874 SurfaceUtils             D  disconnecting from surface 0xc8c47808, reason connectToSurface(reconnect)
2023-07-21 07:52:14.874 SurfaceUtils             D  connecting to surface 0xc8c47808, reason connectToSurface(reconnect)
2023-07-21 07:52:14.874 ACodec                   E  [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2023-07-21 07:52:14.875 ACodec                   I  codec does not support config priority (err -1010)
2023-07-21 07:52:14.876 EventLogger              D  timeline [eventTime=1.03, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2023-07-21 07:52:14.876 EventLogger              D    period [128.27]
2023-07-21 07:52:14.877 EventLogger              D    window [128.27, seekable=true, dynamic=false]
2023-07-21 07:52:14.877 EventLogger              D  ]
2023-07-21 07:52:14.879 EventLogger              D  downstreamFormat [eventTime=1.03, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720, language=en, selectionFlags=[default]]
2023-07-21 07:52:14.885 EventLogger              D  videoDecoderInitialized [eventTime=1.04, mediaPos=0.00, window=0, period=0, OMX.google.h264.decoder]
2023-07-21 07:52:14.886 EventLogger              D  videoInputFormat [eventTime=1.04, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720, language=en, selectionFlags=[default]]
2023-07-21 07:52:14.886 OMXClient                I  IOmx service obtained
2023-07-21 07:52:14.887 EventLogger              D  downstreamFormat [eventTime=1.04, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=und, selectionFlags=[default]]
2023-07-21 07:52:14.888 ACodec                   I  codec does not support config priority (err -2147483648)
2023-07-21 07:52:14.894 EventLogger              D  audioDecoderInitialized [eventTime=1.05, mediaPos=0.00, window=0, period=0, OMX.google.aac.decoder]
2023-07-21 07:52:14.895 EventLogger              D  audioInputFormat [eventTime=1.05, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=und, selectionFlags=[default]]
2023-07-21 07:52:15.123 MediaCodec               D  [OMX.google.h264.decoder] setting dataspace on output surface to #104
2023-07-21 07:52:15.126 EventLogger              D  videoSize [eventTime=1.28, mediaPos=0.00, window=0, period=0, 1280, 720]
2023-07-21 07:52:15.140 EventLogger              D  surfaceSize [eventTime=1.29, mediaPos=0.00, window=0, period=0, 1080, 607]
2023-07-21 07:52:15.141 SoftwareRenderer         D  setting dataspace on output surface to #104
2023-07-21 07:52:15.159 EventLogger              D  renderedFirstFrame [eventTime=1.31, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0x5c5d8b9]
2023-07-21 07:52:15.455 EventLogger              D  state [eventTime=1.61, mediaPos=0.00, window=0, period=0, READY]
2023-07-21 07:52:15.458 EventLogger              D  isPlaying [eventTime=1.61, mediaPos=0.00, window=0, period=0, true]
2023-07-21 07:52:15.472 AudioTrack               D  getTimestamp_l(10): device stall time corrected using current time 1558251130800
2023-07-21 07:52:15.504 AudioTrack               W  getTimestamp_l(10): retrograde timestamp time corrected, 1558266392300 < 1558273357000
2023-07-21 07:52:16.348 EventLogger              D  playWhenReady [eventTime=2.50, mediaPos=0.81, window=0, period=0, false, USER_REQUEST]
2023-07-21 07:52:16.353 EventLogger              D  isPlaying [eventTime=2.51, mediaPos=0.81, window=0, period=0, false]
2023-07-21 07:52:16.801 EventLogger              D  loading [eventTime=2.95, mediaPos=0.82, window=0, period=0, false]
2023-07-21 07:52:24.365 AdTagLoader              W  Unable to determine ad group index for ad group load error
                                                      java.io.IOException: Ad loading timed out
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.handleAdLoadTimeout(AdTagLoader.java:1098)
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader.$r8$lambda$O25GS4aeawxxlofO7DreAKW0930(Unknown Source:0)
                                                          at com.google.android.exoplayer2.ext.ima.AdTagLoader$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                          at android.os.Handler.handleCallback(Handler.java:883)
                                                          at android.os.Handler.dispatchMessage(Handler.java:100)
                                                          at android.os.Looper.loop(Looper.java:214)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

### Media

Any media and the following VAST URL in VMAP.

`https://ad.doubleclick.net/ddm/pfadx/N703922.1534589IPRIMA.CZ/B30145407.369534207;sz=0x0;ord=%%VIEWID%%;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dc_tdv=1;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER];dc_vast=4;dc_mpos=[BREAKPOSITION];ltd=`

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-07-25 14:32
I think that is something you'd need to ask your contact for the IMA integration. The URL gets resolved by the IMA SDK based on information I don't know. One thing I noticed is that your URL has placeholders (e.g. `[APIFRAMEWORKS]`, `[OMIDPARTNER]` and `[BREAKPOSITION]`) that need to be resolved to actual values before the request is made. I'm not sure if this is something the IMA SDK is meant to do or whether you need to resolve this before providing this URL.

**Comment by tonihei** [comment] 2023-07-25 14:33
Closing the issue because the problem is outside of our libraries (either the serving side or the IMA SDK)

**Closed by tonihei** 2023-07-25 14:33 UTC
Labels: wont fix: infeasible
