### ISSUE TITLE
Stale notification when service terminated without being started

### ISSUE THREAD

**Issue by Digipom** [androidx/media#843] opened 2023-11-27 17:40 UTC
### Version

Media3 1.2.0

### Devices that reproduce the issue

Pixel 7 running Android 14 (UP1A.231105.003)

### Reproducible in the demo app?

Not tested

### Reproduction steps

1) Open the application.
2) Without playing, exit it.
3) Swipe the app away from the background. Observe that the process is killed.
4) Try to check if notification is present even after killing the application.
5) Now tap on the play button from the notification.

Observe the behavior.

Expected: 

Audio playback should begin after tapping on the notification play button.

Actual:

Tapping on the play button doesn't do anything. No audio can be heard.

### Expected result

Audio playback starts.

### Actual result

Nothing appears to happen.

### Media

N/A

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Digipom** [comment] 2023-11-27 17:43
[Notifbug.zip](https://github.com/androidx/media/files/13478489/Notifbug.zip)

**Comment by marcbaechinger** [comment] 2023-11-27 19:49
Thanks for your report!

The test fixture app expects `onTaskRemoved` to be called when the service is only bound and never started. This is a duplicate of #817.

**Closed as completed by marcbaechinger** 2023-11-27 19:49 UTC
Labels: bug, duplicate

**Comment by Digipom** [comment] 2023-11-27 23:17
@marcbaechinger I don't really follow -- I checked the other issue but what is the fix that has to be implemented? Is it on my end or is it pending a library update? Thanks.

**Comment by marcbaechinger** [comment] 2023-11-28 12:00
Sorry to not be clear.

I don't think an app can do something. From my perspective this is either something I don't understand or this behavior isn't right. 

When I was testing the behavior was as follows:

1. Create the service by building a controller that binds to the service.
2. Release the controller to unbind from the service.
3. Swipe away the app from recent tasks.

Expected behaviour: 
`onTaskRemoved()` and `onDestroy()` of the service are according to the lifecycle of the service.

Observed behaviour:
Service terminates without calling `onTaskRemoved()` and/or `onDestroy()`.

The observed behavior doesn't leave a way for the library to properly terminate the service including cleaning up resources. If the observation or my interpretation are correct this is a bug in Android as we would always expect that `onDestroy()` is called for a service. I may be wrong though and the `MediaSessionService` is doing something wrong. I need to request assistance from OS people to check whether we can do something from the library side.

**Comment by Digipom** [comment] 2023-11-28 12:45
Thank you, that makes sense. Is there a reason that the media button receiver also doesn’t work though? I thought it was supposed to recreate the app and the service. Or is that also related to onDestroy not being called?

**Comment by marcbaechinger** [comment] 2023-11-28 13:02
If you have the MBR in you manifest then it should be registered as soon as the platform media session is created which is when your service creates the `MediaSession`. The library then checks whether you have the MBR in the manifest and registers it.

I don't see a reason why this shouldn't work.

Just to make sure we are on the same page: pressing the play notification above is not related with the MBR working or not. The MBR is only used if you try to restart the service with a media button event. This would be for instance when you press the play button on a Bluetooth device. 

What you actually see and which may be the reason for the confusion is a stale notification that has been posted by Media3 and that wasn't removed because the session wasn't release (I assume your app does this in `onDestroy()`). It's not supposed to be able to restart the service.

When you play and then pause before you dismiss the app from the recent apps, the app should terminate correctly and the service is terminated properly and then the session is released properly as well which also removes the Media3 notification. In this case and with [playback resumption enabled](https://developer.android.com/guide/topics/media/session/mediasessionservice#resumption) System UI post it's own resumption notification that looks quite similar but works differently than the notification posted by Media3 . I doubt the stale notification you see is the resumption notification.

**Comment by Digipom** [comment] 2023-11-28 14:17
Ok thanks, that helps to clarify the question about the MBR. Can we just fake what play/pause does in terms of state if that fixes the issue with the service?

**Comment by marcbaechinger** [comment] 2023-11-28 14:41
That's a possible workaround but sounds quite hacky.

**Comment by Digipom** [comment] 2023-11-28 14:53
Yes, it would be ideal if there was a non-hacky solution to the problem. As it is, non-functional notifications will tend to lead to negative store reviews and poor customer feedback. Hopefully a better fix will come. Thank you for the detailed explanations, it's much appreciated.

**Comment by Bwaim** [comment] 2023-12-18 13:51
As a workaround for this, i forced the notification with a `startInForegroundRequired` for the first display :

```
override fun onUpdateNotification(session: MediaSession, startInForegroundRequired: Boolean) {
        val startInForeground = forceServiceStart || startInForegroundRequired
        super.onUpdateNotification(session, startInForeground)
    }
```

**Comment by Digipom** [comment] 2023-12-18 14:01
@Bwaim Interesting -- would be good to see what the downsides are (if any).
I've noticed an unrelated issue where we actually want START_NON_STICKY so the notification doesn't keep coming back.
