### ISSUE TITLE
Video not playing after seeking (Pixel5 Android14 widevine)

### ISSUE THREAD

**Issue by pineapplevine** [androidx/media#1022] opened 2024-01-25 08:17 UTC
### Version

Media3 1.2.1

### More version details

b930b40a16c06318e43c81771fa2b1024bdb3f29

### Devices that reproduce the issue

Pixel5 
OS: 14
Build: UP1A.231105.001

### Devices that do not reproduce the issue

Pixel6a
OS:14
Build:UQ1A.240105.002

### Reproducible in the demo app?

Yes

### Reproduction steps

1. open demo app
2. select [Widevine Dash (policy tests)]->[HW secure all(L1)]
3. play for about 30s
4. seek forward 10m
5. seek backward 10m
repeat step 4~5 until the issue is reproduced. 

### Expected result

The media plays after seeking

### Actual result

The media stopped, and no responding after click [play] button.

### Media

Widevine Dash (policy tests)
->
HW secure all(L1)
in the demo app.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment] 2024-12-19 15:38
Duplicate of https://github.com/androidx/media/issues/1984. Closing this one as progress and diagnosis will be provided on that thread.

**Closed by microkatz** 2024-12-19 15:38 UTC
Labels: bug, duplicate
