### ISSUE TITLE
[CMCD] Too many buffer starvation reports

### ISSUE THREAD

**Issue by mikef-dk** [androidx/media#1124] opened 2024-02-22 12:58 UTC
### Version

Media3 1.2.1

### Devices that reproduce the issue

Reproducible on any device

### Reproducible in the demo app?

Yes

### Reproduction steps

Prerequisite: Add `CmcdConfiguration.Factory.DEFAULT` to `DefaultMediaSourceFactory` in `PlayerActivity` and optionally logs to `LoadingInfo#rebufferedSince`

1. Open App
2. Select UHD (cbcs)
3. Check CMCD data

### Expected result

One Buffer Starvation (bs) event in the CMCD data (video needs to load therefore I would expect only one)

### Actual result

Two Buffer Starvation (bs) CMCD events are reported

Looking at the logs I can see that `rebufferedSince` was called twice:
1st time: realtimeMs = 299910722
2nd time: realtimeMs = 299910780
In both cases the `lastRebufferRealtimeMs` was `299911159` so the method returned `true`. So in the end two buffer starvations are reported but in fact only one rebuffering happened.

### Media

UHD (cbcs)
HD (cbcs)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment] 2024-02-28 14:56
Hi @mikef-dk,

The behavior is actually working as intended. CMCD data is reported whenever a request is made to get a chunk. When starvation occurs, there are actually two requests made to fetch chunks i.e. one for audio and the other for video. 

If you observe closely, CMCD data reported also contains a field called `objectType` which is different (`a` and `v`) for these two reports.

**Comment by mikef-dk** [comment] 2024-02-29 08:36
Hi @rohitjoins,

thanks for looking into this and your explanation. Maybe my "expectation" as outlined in the issue description was a bit misleading: In fact I would expect 0 "buffer starvations". If the media didn't even start - so not a single chunk has been loaded before because it's the initial loading - why would you consider this as a "buffer starvation"? There was never any data in the buffer before. By doing this basically every stream would report 1-2 buffer starvations leading to faulty reports. 

As an additional note: Afaik, Shaka Player doesn't have this "issue" - they don't report any buffer starvation during the initial setup/loading.

**Comment by totallyunknown** [comment] 2024-04-14 18:20
Are there any updates on this? For us, the CMCD data is useless without the correct buffer starvations.

**Comment by rohitjoins** [comment] 2024-04-22 07:18
Hi @totallyunknown,

I'm working on this and will soon provide a fix for this.

**Comment by rohitjoins** [comment] 2024-05-01 15:37
A [fix](https://github.com/androidx/media/commit/feb512544a1e3848d6e9ddd5f545c1ac55cf9cff) has been submitted to the `main` branch for this issue and will be included in the next release. Thanks for reporting once again.

**Closed by rohitjoins** 2024-05-01 15:37 UTC
Labels: bug, needs triage

**Comment by mikef-dk** [comment] 2024-05-06 09:37
@rohitjoins Thanks for the fix - really appreciate it. 🙏 

Will there be another 1.3.x release with this fix or is it only coming to the 1.4.0 version that is currently in alpha?

**Comment by rohitjoins** [comment] 2024-05-09 11:45
@mikef-dk, I believe there won't be any further bug fix releases. The fix will be included in any new release related to version 1.4.0.
