### ISSUE TITLE
local storage video play normally but not Seekable.  When try to seek ,video starts from beginning everytime

### ISSUE THREAD

**Issue by rup-sarma** [androidx/media#1862] opened 2024-11-07 16:38 UTC
### Version

Media3 main branch

### Devices that reproduce the issue

Oneplus Nord CE lite 3 5G and also other brands like Redmi, Realme, samsung etc.

### Reproducible in the demo app?

Yes

### Reproduction steps

just Download video from this Google drive link https://drive.google.com/file/d/1iDVej49ELlstdxwxiLShy_5zM_5dzrJn/view?usp=drivesdk  and then try play it and seek 10 seconds. 

### Expected result

ExoPlayer needs to seek to 10 seconds forward or rewind successfully and  show default time bar thumb.

### Actual result

when try to seek to 10 sec video starts from 00.00 secs again (Beginning).

### Media

Download video from this link drive.go  and play it from local storage

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rup-sarma** [comment] 2024-11-07 16:43
here Is Media info of this file

General ----
Complete name : | Maharaja South Hindi Dubbed 2024.mp4
Format : | Matroska
Format version : | Version 4
File size : | 1.31 GiB
Duration : | 2 h 20 min
Overall bit rate : | 1 326 kb/s
Frame rate : | 24.000 FPS
Movie name : | www.Khatrimazafull.net / Downloaded From HDHub4u
Encoded date : | 2024-07-11 20:22:24 UTC
Writing application : | mkvmerge v85.0 ('Shame For You') 64-bit
Writing library : | libebml v1.4.5 + libmatroska v1.7.1
WEBSiTE : | HDHub4u.Tv
FileExtension_Invalid : | mkv mk3d mka mks


Video -----
ID : 1
Format : | AVC
Format/Info : | Advanced Video Codec
Format profile : | High
Format level : | 4
Format settings, CABAC : | Yes
Format settings, Reference frames : | 7 frames
Codec ID : | V_MPEG4/ISO/AVC
Duration : | 2 h 20 min
Nominal bit rate : | 1 100 kb/s
Width : | 1 280 pixels
Height : | 536 pixels
Display aspect ratio : | 2.39:1
Frame rate mode : | Constant
Frame rate : | 24.000 FPS
Color space : | YUV
Chroma subsampling : | 4:2:0
Bit depth : | 8 bits
Scan type : | Progressive
Bits/(Pixel*Frame) : | 0.067
Title : | www.Khatrimazafull.net
Writing library : | x264 core 142 r2479 dd79a61
Encoding settings : | cabac=1 / ref=7 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=96 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=2 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=1100 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=16500 / vbv_bufsize=14400 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default : | Yes
Forced : | No
Color range : | Limited
Color primaries : | BT.709
Transfer characteristics : | BT.709
Matrix coefficients : | BT.709

**Comment by tianyif** [comment] 2024-11-07 17:39
When I reproduced this with demo app, I saw the below line was hit, which makes seeking in this media impossible.

https://github.com/androidx/media/blob/91dfaab93ff9ac07afcc751e0e989946fd74a836/libraries/extractor/src/main/java/androidx/media3/extractor/mkv/MatroskaExtractor.java#L768

Over this issue to my colleague for more insights.

**Comment by rohitjoins** [comment] 2024-11-07 17:55
Hi @rup-sarma,

The media file you're working with doesn't contain cues that we can use to generate a `seekMap`, which is why it's marked as `Unseekable`. In the demo app, the seek bar is disabled, which is the intended behavior.

Please note that in your app, you should avoid trying to seek an `Unseekable` video, as this will trigger playback from the start (which is the intended behavior).

Let me know if you have any further questions or need more clarification!

**Closed by rohitjoins** 2024-11-07 17:55 UTC
Labels: bug, needs triage

**Comment by rup-sarma** [comment] 2024-11-07 18:02
But MX Player & Xplayer can play this video perfectly.
One more question how do i know that video isnot seekable at all.

**Comment by rohitjoins** [comment] 2024-11-07 18:16
To check if the current media is seekable, you can use `player.isCommandAvailable(COMMAND_SEEK_IN_CURRENT_MEDIA_ITEM)`.

> But MX Player & Xplayer can play this video perfectly.

Other players may have workarounds that allow seeking for this type of media, but we aim to follow the MKV spec for handling it.

**Comment by rup-sarma** [comment] 2024-11-07 18:22
Okay thanks.
In order resolved this my self, whaat types of Extractor method should i follow if you can give me any direction. That will be helpful

**Comment by rohitjoins** [comment] 2024-11-07 20:55
> In order to resolved this problem myself, what types of Extractor method should i follow if you can give me any direction.

As @tianyif pointed out earlier, the code [hits](https://github.com/androidx/media/issues/1862#issuecomment-2462857586). You'll need to find a workaround in this case to create a `seekMap` and set it in `ExtractorOutput`. 

Would be interesting to know the source of this media files and if this is a widespread issue in order for us to consider adding a workaround to the library.

**Comment by rup-sarma** [comment] 2024-11-08 02:32
This is a indian movie clip Downloaded from khatrimaza.net. most of the news film released in this year 2024 that i have downloaded from verious torrent website have this issue. Maybe it is a widespread issue. I don't know but but i am facing it every time.
