### ISSUE TITLE
media3.transformer fails during video compression(TransformerListeners onError() recieved).

### ISSUE THREAD

**Issue by Sach-24** [androidx/media#1672] opened 2024-08-30 06:12 UTC
### Version

Media3 main branch

### Devices that reproduce the issue

The issue was seen in Somin XP9900

### Devices that do not reproduce the issue

Tried in below devices and issue was not seen.
Samsung S9
Samsung S10

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Select any video that has a higher bitrate per second.
-Example: A video that is just 10 sec and is sized 60 MB.
2. Compress the video via media3.Transformer and add Transformer.Listener.
-Start compression  transformer.start(editedMediaItem, destination);

### Expected result

The video should be successfully compressed and onCompleted() of Transformer.Listener should be received.

### Actual result

Here, onError() of Transformer.Listener is received and the file compression did not happen.

Refer below Adb logs.

Logs-1
08-27 12:15:38.228 E/QC2V4l2Codec(  965): [avcE_118] INIT : Failed to set default resolution on input port
08-27 12:15:38.228 E/QC2Comp (  965): [avcE_118] failed to init codec !
08-27 12:15:38.030 I/msm_vidc(    0): err : 00000003: ....e: H/W is overloaded. needed: 490440 max: 489600
08-27 12:15:38.030 I/msm_vidc(    0): err : ffffffff: .....: Running instances:
08-27 12:15:38.244 E/MediaCodec(11246): Codec reported err 0xfffffff4, actionCode 0, while in state 5/STARTING
08-27 12:15:38.257 D/DefaultCodec(11246): MediaCodec error
08-27 12:15:38.257 D/DefaultCodec(11246):   android.media.MediaCodec$CodecException: start failed

Logs-2
08-20 12:31:51.164  8788 24258 W TransformerInternal: Export error after export ended
08-20 12:31:51.164  8788 24258 W TransformerInternal: obfuscated.y00: Video frame processing error
08-20 12:31:51.164  8788 24258 W TransformerInternal: Caused by: obfuscated.aj1: Release timed out. OpenGL resources may not be cleaned up properly.

### Media

I'm not able to upload the media it says "This video is too big.
 with a file size less than 10MB."
 media will be sent via mail.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Sach-24** [comment] 2024-08-30 06:15
Please check this below media where issue was observed.
https://drive.google.com/file/d/13A4Fi8xyEp9eJtZnAWX61T_u3cWd-8dX/view

**Comment by ychaparov** [comment] 2024-09-02 12:17
The numbers in the shared log `H/W is overloaded. needed: 490440 max: 489600` are macroblocks per second.

489600 corresponds to 1920x1080 at 60 fps. I wonder why `490440` was needed: the test video you shared is 1920x1080 at 30 fps and should need fewer macroblocks per second from the encoder.

Did you apply any effects to the `EdtiedMediaItem`?

Was there another video app running on the phone at the same time, and does a restart resolve the issue?

Are these the correct specs for the XP9900 that failed to process the video https://www.sonimtech.com/products/devices/xp10/#specifications ?
Is the chipset `Qualcomm SM4350 Pro,2xA76@2.2GHz, 6xA55@1.9GHz` (i.e. SM4350-AC)?

I was unable to reproduce this issue on a device with a similar (slightly under-clocked) `SM4350` chipset -- and running Transformer on the video shared was also successful while I was recording a video with the camera app.

**Comment by Sach-24** [comment] 2024-09-03 05:43
Hi ychaparov

> Did you apply any effects to the `EdtiedMediaItem`?
> No.

> Was there another video app running on the phone at the same time, and does a restart resolve the issue?
> No video app was running in BG. but need to check if restarting can solve the issue.

> Are these the correct specs for the XP9900 that failed to process the video 
>Yes.This is the device

**Comment by ychaparov** [comment] 2024-09-03 08:38
Can you please reproduce the issue, collect `adb bugreport` and send the resulting zip file to android-media-github@google.com as requested in the issue template above:

> You will email the zip file produced by adb bugreport to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue


How is Transformer configured?

Are you using [setRequestedVideoEncoderSettings](https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultEncoderFactory.java#L107)?

**Comment by Sach-24** [comment] 2024-09-04 12:27
Hi

>I have sent ADB logs via mail, Please check.


> How is Transformer configured?

                  MediaItem inputMediaItem = MediaItem.fromUri(source);
                   EditedMediaItem editedMediaItem = new EditedMediaItem.Builder(inputMediaItem)
                           .setEffects(new Effects(ImmutableList.of(),
                            ImmutableList.of(Presentation.createForHeight(getHeightForCompression(source)))))
                            .build();
                    
                  Transformer transformer =
                    new Transformer.Builder(DroidApiManager.getApplicationContext())
                            .addListener(transformerListener)
                            .build();
                            
                transformer.start(editedMediaItem, destination);
                
                




> Are you using [setRequestedVideoEncoderSettings]
No.

**Comment by ychaparov** [comment] 2024-09-04 13:32
You sent a text file, the output of `adb logcat`. We asked you to send a zip file, the output of `adb bugreport`.

The logs you sent ran on a different device from the original bug report:
`08-20 12:25:05.220  8788 22841 I ExoPlayerImpl: Release 6fb219c [AndroidXMedia3/1.3.0] [xcoverpro2, SM-G736U, samsung, 34]`

And a different Media3 version - 1.3.0 is not the main branch.

Did you send logs from August 20?

Can you reliably reproduce this issue or does it only happen rarely?

What is the height used in the code snippet above: `getHeightForCompression(source)`?

**Comment by Sach-24** [comment] 2024-09-11 05:26
Please wait while we send you the adb bug report.
Thanks.

**Comment by droid-girl** [comment] 2024-10-10 15:25
@Sach-24 did you send the bug report?

**Comment by Sach-24** [comment] 2024-11-05 03:50
HI 
Please wait
as the reporter of this issue is inactive .

**Comment by Sach-24** [comment] 2024-12-02 07:49
Hi.
The reporter did not provide any other information.
Hence there is no more information available on this issue.
Please do the needful.
Thanks

**Comment by droid-girl** [comment] 2024-12-02 11:20
I will be closing the issue. Please re-open when you get information needed to debug it.

**Closed by droid-girl** 2024-12-02 11:20 UTC
Labels: bug, needs triage, editing
