### ISSUE TITLE
Provide Transformer API to automatically downscale large images

### ISSUE THREAD

**Issue by calren** [androidx/media#1243] opened 2024-04-03 18:35 UTC
### Use case description
When using the Transformer Composition APIs, it seems there could be images that are too big to be processed. It would be useful to have an API that automatically handles downscaling images when appropriate.

More info:
This is currently happening with this image https://storage.googleapis.com/exoplayer-test-media-1/jpg/london.jpg on an emulator. (Error does not occur on a physical device, but I'm not sure if this can also happen on lower end physical devices.)

When using the Composition API to create a video with the image, I'm seeing an `ERROR_CODE_FAILED_RUNTIME_CHECK`.

It seems this error may be happening because the encoder on the emulator can't encode the large output size. 

### Proposed solution
It would be nice if I can do something like the code snippet below with `setAutomaticDownscalingTransformer(true)` to automatically have images downscaled when appropriate.

```
Composition.Builder(compositionSequences)
            .setAutomaticaDownscalingTransformer(true)
            .build()
```

### Alternatives considered
Alternatively, a more descriptive error code can be returned when an image is too large. (The current error code returned is `ERROR_CODE_FAILED_RUNTIME_CHECK`) However, this would still require the developer to handle downscaling of the image.

**Comment by droid-girl** [comment] 2024-04-04 15:56
@tof-tof I think this functionality is available now but require a complicated setup and might not be straight forward for developers. We can consider this path as proposed as one of the future improvements

**Comment by tof-tof** [comment] 2024-04-05 07:22
yes, this is possible by setting a custom bitmap loader. I have done this in a test on the main branch [here](https://github.com/androidx/media/blob/886764268154945052b8311ee8c103a9eff19468/libraries/transformer/src/androidTest/java/androidx/media3/transformer/TransformerUltraHdrTest.java#L175):

sadly we can't create top level api's or every feature that we have, the api would become too bloated and hard to read. Plus we'd want to give users more option over the size of the input they create, as well as other Bitmap options

**Comment by calren** [comment] 2024-04-05 17:20
Thanks @tof-tof ! That makes sense.

I wonder if it's possible to provide a more descriptive error than `ERROR_CODE_FAILED_RUNTIME_CHECK` when this issue is encountered then? Currently it's very difficult to debug why something went wrong.

For example, I was trying to use  https://storage.googleapis.com/exoplayer-test-media-1/jpg/london.jpg with the Composition APIs, and thought I was doing something wrong with the APIs itself. It was difficult to understand that the problem was the size of the image inputted.

**Comment by tof-tof** [comment] 2024-04-09 17:04
sure, sounds reasonable. Can i have an example stack trace please? when i repro the failure on my side it doesn't have a `ERROR_CODE_FAILED_RUNTIME_CHECK` error, but instead says `Caused by: java.lang.IllegalArgumentException: The requested video encoding format is not supported.`

**Comment by calren** [comment] 2024-04-12 03:37
aiming to revisit this next week! sorry for the delay

**Comment by tof-tof** [comment] 2024-04-19 17:29
Thanks @calren,

This is a very different stack trace to what I expect to be seeing. It looks like the file isn't being recognised as an image, so transformer has chosen the video asset loading path ( seen by `ExoPlayerAssetLoader` being in the stack trace) rather than the image loading path. This error is very quite different to the original error this issue was above, so I'll close this issue and ask you to create a new one (you can assign me to it straight away). I'll keep looking into it in the mean time to see if I can figure out what's gone wrong here

**Closed by tof-tof** 2024-04-19 17:29 UTC
Labels: enhancement, needs triage, editing

**Comment by calren** [comment] 2024-04-29 19:42
okay for some reason I can't seem to reproduce that error anymore. i don't really know what changed, but if i see it again i'll be sure to file a new bug.
