### ISSUE TITLE
Video Quality Track Selection Change Not Working As Expected

### ISSUE THREAD

**Issue by Kitta0812** [androidx/media#1938] opened 2024-12-02 13:02 UTC
Version
Media3 main branch

More version details
media3 version : 1.5.0

exoPlayer.trackSelectionParameters = exoPlayer.trackSelectionParameters.buildUpon().setOverrideForType(TrackSelectionOverride(trackGroup.mediaTrackGroup,trackIndex)).build()

after Selecting New Video Pixel Type for Example from 1080 p to 360 p 
A New Video Frame is Creating Under PlayerView Surface with Low Width and Height 

TrackGroup Info is being fetched from exoPlayer.currentTracks.groups

After Applying the Track Selection
Actual 
![image](https://github.com/user-attachments/assets/a16a6268-e4d0-4637-ab45-ca635c84d990)

Expected 
![image](https://github.com/user-attachments/assets/03e82724-9b9e-402a-90c0-4ac5450dc7d2)

**Comment by Kitta0812** [comment] 2024-12-05 04:32
More Info on this 

VideoUrl = "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8"

I'm following Same Way as TrackSelectionDialogBuilder does!!

1. Steps 1 Fetch Tracks Groups based on TrackType
2. Steps 2 Take ImmutableMap<TrackGroup, TrackSelectionOverride> from player.getTrackSelectionParameters().overrides
3. if Overrides is Null Then Append TrackGroup and TrackSelectionOverride in it as
   overrides.put(trackGroup.mediaTrackGroup,TrackSelectionOverride(trackGroup.mediaTrackGroup, listOf(trackIndex)))
4. Now We have One Override which need to be Selected 
5. Now Take TrackSelectionParameter from Player as val param = exoPlayer.trackSelectionParameters.buildUpon()
6. Next Clear All Existing Overrides and make this TrackTypeDisable as False 
    param.setTrackTypeDisabled(C.TRACK_TYPE_VIDEO, false);
    param.clearOverridesOfType(C.TRACK_TYPE_VIDEO);
7. Next take trackSelectionOverride from Override which we have inserted and add in Param   param.addOverride(trackSelectionOverride) 
8. Finally add these trackSelectionParameters to Player 

Once got added we'll get a listener of onTracksChanged in these on MediaTrackGroup inside Formats there will be N no of Format all of them will be made slected as false expect the one which we have overrided


After All This Process 

In Eixtsing Original Frame Old Resolution got stuck and not playing on top of that a new slected resoltion will be rended as Shown in Figure

**Sample Code** 				
	
	    val overrides = exoPlayer.trackSelectionParameters.overrides.toMutableMap()
             overrides.put( trackGroup.mediaTrackGroup,TrackSelectionOverride( trackGroup.mediaTrackGroup, listOf(trackIndex)));
             val trackSelectionOverride = overrides.get(trackGroup.mediaTrackGroup) ?: return@withContext
                           
              val param = exoPlayer.trackSelectionParameters.buildUpon()
              param.setTrackTypeDisabled(C.TRACK_TYPE_VIDEO, false);
              param.clearOverridesOfType(C.TRACK_TYPE_VIDEO);
              param.addOverride(trackSelectionOverride )
              exoPlayer.trackSelectionParameters = param.build()
              
       Thank You!!!

**Comment by icbaker** [comment] 2024-12-05 09:31
> **Once got added we'll get a listener of onTracksChanged in these on MediaTrackGroup inside Formats there will be N no of Format all of them will be made slected as false expect the one which we have overrided**
> 
> After All This Process
> 
> In Eixtsing Original Frame Old Resolution got stuck and not playing on top of that a new slected resoltion will be rended as Shown in Figure

Based on the bit I've bolded, this sounds like a UI issue, rather than a track selection one (since it sounds like you see the selection you intend being reflected programmatically in `onTracksChanged`) - possibly a duplicate of https://github.com/androidx/media/issues/1831 - are you observing this on an emulator or a real device?

**Comment by Kitta0812** [comment] 2024-12-06 04:47
Hi @icbaker 
Thanks for Pointing [https://github.com/androidx/media/issues/1831](url), Yep This one was working fine, But still during the Track Switch I can clear see there was a Lack for few second not sure whether I'm doing something wrong This is the Exact code which i have written.

LauchedEffect(Unit) {
   delay(5000)
   withContext(Dispatcher.Main) {
       val overrides = exoPlayer.trackSelectionParameters.overrides.toMutableMap()
       overrides.put( trackGroup.mediaTrackGroup,TrackSelectionOverride( trackGroup.mediaTrackGroup, listOf(trackIndex)));
       val trackSelectionOverride = overrides.get(trackGroup.mediaTrackGroup) ?: return@withContext
                       
       val param = exoPlayer.trackSelectionParameters.buildUpon()
       param.setTrackTypeDisabled(C.TRACK_TYPE_VIDEO, false);
       param.clearOverridesOfType(C.TRACK_TYPE_VIDEO);
       param.addOverride(trackSelectionOverride )
       exoPlayer.trackSelectionParameters = param.build()
       }


    
    for testing I made one more Delay with 5 seconds and switched to diufferent Track
    }


Example Video 

https://github.com/user-attachments/assets/32a0c4d2-6854-4c19-a5eb-543a4ba83d38

**Comment by icbaker** [comment] 2024-12-06 09:30
> I can clear see there was a Lack for few second not sure whether I'm doing something

From the video iIt looks like you're seeing a rebuffer. This seems expected after you trigger an explicit and immediate track change with an override, because we have to load the new track data immediately with no warning.

What are you expecting to see instead?

When the player switches bitrate automatically due to bandwidth or other constraints, we do it ahead of the playback position, and at a segment boundary, so the new track is already loaded when playback gets to the transition point, and it can continue seamlessly. If this is what you are trying to achieve, you need to select **all** the tracks you want to switch between in `TrackSelector`, and implement your sub-selection within the `TrackSelection` interface. You can see how we do this in `AdaptiveTrackSelection`: https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/trackselection/AdaptiveTrackSelection.java

**Comment by Kitta0812** [comment] 2024-12-06 09:54
Hi @icbaker Thanks for the reply, When switching the tracks I don't want user to see some Rebuffer of new content basically until the new Track data comes up I want to continue playing already fetched existing track video data how YouTube and other player where performing!!

**Comment by icbaker** [comment] 2024-12-06 10:00
If you want to automatically switch bitrate seamlessly based on network conditions you should use `DefaultTrackSelector` configured to select **all** the tracks you would like to switch between, and let the player handle the automatic switches (i.e. don't override the selection to pick specific tracks).

See more info here: https://developer.android.com/media/media3/exoplayer/track-selection

If you want to switch seamlessly based on something else, you need to write a lot of your own fiddly custom code as I hinted at above, which I'm afraid we don't have the capacity to support you with.

I'm going to close this issue because I think the bandwidth-based-switch case is covered, and as I said I'm afraid the custom case is too fiddly for us to help you with in detail.

**Closed by icbaker** 2024-12-06 10:00 UTC
Labels: question
