### ISSUE TITLE
How to set defaultPositionUs of a Window in the Timeline?

### ISSUE THREAD

**Issue by akshdeep-singh** [androidx/media#1129] opened 2024-02-24 16:37 UTC
I want to set default start positions of my playlist items (basically to resume from where the user left), to use when playlist item auto transitions to next item.

As per my understanding (I am not sure), the default start position is of the window in the timeline.

From Docs: [Timeline.Window.defaultPositionUs](https://developer.android.com/reference/androidx/media3/common/Timeline.Window#defaultPositionUs()). But, I can't find a way to set this defaultPositionUs parameter.

I use this function to set playlist items: [setMediaItems](https://developer.android.com/reference/androidx/media3/common/Player#setMediaItems(java.util.List%3Candroidx.media3.common.MediaItem%3E,int,long)). My playlist items are mp3 files (local and https source).

**Comment by marcbaechinger** [comment] 2024-02-27 11:09
I think you can do this only if you own the media. This is AFAIK used with live streams.

The feature is a duplicate of [#6373](https://github.com/google/ExoPlayer/issues/6373) and #1041 I think.

You can use `MediaItem.ClippingProperties` to clip a media item. However, this removes the part before the clipping start position. A user can't seek back beyond this because it's clipped. So this isn't exactly the same as a start position but about the same as a default position. :)

If this isn't helpful you need to use a seek for this. This was discussed in #1041

**Closed by marcbaechinger** 2024-02-27 11:09 UTC
Labels: duplicate, question
