### ISSUE TITLE
ExoPlayer - Volume become suddenly noisy when it's playing while watching something else

### ISSUE THREAD

**Issue by Wildyax** [androidx/media#516] opened 2023-07-12 17:43 UTC
### Version

Media3 1.1.0

### Devices that reproduce the issue

OnePlus Nord 2 5G
OnePlus 7

### Reproducible in the demo app?

Yes

### Reproduction steps

1 : Play a song with any app that use ExoPlayer as player (I tried with the vlc player for android and the problem only happen with ExoPlayer)
2 : Go out of the app while the song still playing (background playing)
3 : Go on YouTube for example and stay on the home page, wait than a video launch the preview (the preview has no sound by default) and the volume will become suddenly noisy
4 : Scroll to quit the preview and the volume will become normal again

. It does not only occurs with youtube, same problem if I launch some games like Subway Surfers
. Also the problem does not occur with some apps like on the video preview on twitter feed

### Expected result

Audio should stay at the same volume when a video preview with no sound is playing.

### Actual result

The volume become noisy and it can be scary sometimes.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-07-14 15:59
I cannot observe this when testing on a Pixel 7a.

 - Does it happen on the mentioned devices only or can you reproduce on other devices too?
 - Is using VLC required in the reproduction steps or does it happen with other apps as well (e.g. the Media3 session demo app)?

**Comment by Wildyax** [comment] 2023-07-15 08:08
Oh, I see. Maybe this bug only occurs with OnePlus smartphones 🤔
I actually tried it with my brother's Huawei P30 phone and the bug doesn't occur, so for now, it only happens with the mentioned devices.
Using VLC player is not required; I just wanted to make sure it doesn't happen with other players.
The bug only occurs with an application using exoPlayer (including the demo application).
I also tried looking into the logcat with android studio, and nothing seems to happens when the volume increase on my end.

**Comment by tonihei** [comment] 2023-07-17 07:44
Okay, thanks. Does the problem only occur with the YouTube preview? I wonder if either YouTube or the device is modifying the system volume automatically for some reason and then cause the issue you observe. It's also worth checking the system volume sliders for media to see if they change too. 

In any case, it sounds like the problem is outside of our libraries and there is no much we can do about it with our code.

**Comment by tonihei** [comment] 2023-12-13 13:47
Closing since there has been no further update.

**Closed by tonihei** 2023-12-13 13:47 UTC
Labels: bug, needs triage
