### ISSUE TITLE
Low-resolution artwork URI's in notification tray on Android 13

### ISSUE THREAD

**Issue by iTaysonLab** [androidx/media#168] opened 2022-09-19 23:26 UTC
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

* Pixel 4a (5G) running Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play any audio file in the demo app
2. Open the notification tray

### Expected result

The image is shown in normal quality

### Actual result

The image is shown in low-resolution

### Media

Any media file with artwork URI set in MediaMetadata, like:
Album Folder > Jazz & Blues
Album Folder > Youtube Audio Library Rock (2)

(The demo app is demo-session, not the main one, because it includes a background service)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-09-20 11:19
By default and in the demo session app, the [`SimpleBitmapLoader`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/SimpleBitmapLoader.java#L92) is used for downloading the image and it does not scale the image but instead decodes the bitmap from the exact byte array that has been downloaded. The bitmap is then passed to SystemUI by adding it to the notification as the large icon as a `Bitmap`.

I'm not quite sure what SystemUI is then doing with the bitmap, but I don't think the Media3 library is doing any scaling. If you think the Media3 library can somehow improve the quality of the bitmap please let me know. It's well possible I don't see something that you want to point out some further.

**Comment by robm92** [comment] 2022-09-20 11:32
Experiencing the same issue on both Android 12 & 13 - the image appears to be heavily compressed.
Android 12 still appears to be very pixelated but it is acceptable at the thumbnail size. Android 13 has exacerbated the compression used.

I am building a MediaMetadata object with `.setArtworkUri(imageUri)`

Original image uri - https://media.architecturaldigest.com/photos/5890e88033bd1de9129eab0a/4:3/w_960,h_720,c_limit/Artist-Designed%20Album%20Covers%202.jpg

Android 13
<img width="428" alt="Android13" src="https://user-images.githubusercontent.com/11296167/191245652-19b2f83c-703c-4e57-88cd-df2a804975df.png">

Android 12
![Android12](https://user-images.githubusercontent.com/11296167/191246231-d7ac0a03-d63d-4be1-8d38-12ea7f24dc5e.jpeg)

**Comment by robm92** [comment] 2022-09-20 11:51
I have tested downloading the bitmap data myself (using COIL) and providing with 
`.setArtworkData(imageData, MediaMetadata.PICTURE_TYPE_FRONT_COVER)`
This resolves the issue but is not ideal.
<img width="425" alt="Screenshot 2022-09-20 at 12 51 28" src="https://user-images.githubusercontent.com/11296167/191250373-82731277-dd8c-49b6-8ff2-456539ca200a.png">

**Comment by marcelpallares** [comment] 2022-09-22 10:38
I can confirm I'm facing the same issue and manually setting the image via `.setArtworkData()` solves it

**Comment by TStrothjohann** [comment] 2022-10-11 08:47
Hi @marcbaechinger ,
I don't want to stress. But I would like to ask what you recommend. We are having the described blurry thumbnail on Android 13 in the ZEIT ONLINE Android app. Should we try to find a workaround on our side or are you expecting to deploy some fix for the issue soon?
Thank you very much!

**Comment by marcbaechinger** [comment] 2022-10-12 11:26
We are working on a solution that provides the Bitmap in an efficient way to all places where it is required on all API levels. The icon being scaled down by the system that much on Android 13 caught us a bit on the wrong foot tbh.  We need to redesign the internal implementation and the API for this. It's likely that we need to change the API surface for this which means that the solution for the upcoming 1.0.0 release will be an @Unstable API. We certainly hope and believe that this API will stick, but we can't officially change the API for 1.0.0 because we are already in beta.

After this lengthy comment about rather unimportant things it's no surprise that I don't have a good answer for your actual question. We are working on it. It will be part of the stable 1.0.0 release, but I can't give you a concrete timeline for this I'm afraid. It will land on the `main`branch earlier at which point we will update the issue here with the commit number.

It will be rather December than earlier to give you a conservative guess that is my own and it's based a bit on sand as of now. I'm sorry for not being able to give you a better answer.

**Comment by TStrothjohann** [comment] 2022-10-13 08:50
Thank you Marc! I think we better live with the tiny thumbnails until December than wasting time in a hacky workaround.

**Comment by chvp** [comment] 2023-01-07 21:01
I think this was fixed, either by platform changes or beta-03? At least I can't reproduce this anymore with the same code as I had in november.

**Comment by marcbaechinger** [comment] 2023-01-09 10:17
Thanks for verifying! The Media3 has been changed to dance around the issue. I'm closing.

**Closed by marcbaechinger** 2023-01-09 10:17 UTC
Labels: bug
