### ISSUE TITLE
Add media item with start position

### ISSUE THREAD

**Issue by sampengilly** [androidx/media#895] opened 2023-12-14 22:30 UTC
### Use case description
A podcasting app, where listening position is remembered on individual episodes. If the user starts playback of an episode we queue up other episodes in the same program, if one of those episodes in the queue has been listened part way through, we should resume from that point when that episode is reached.

### Proposed solution
There's already an overload of `Player::setMediaItems` which takes a `startPositionMs` to apply to the first item in the list of media items. Would it be possible to associate a `startPositionMs` with the other items in the list, or to have an overload of `addMediaItem` which takes a `startPositionMs`? In our implementation we're already remembering the listening progress, we just need to command the player to resume from that point.

### Alternatives considered
The workaround I see would be to attach a listener to the player which intercepts `onMediaItemTransition` events, performs a lookup for the tracked progress and calls `seekTo`.

**Comment by icbaker** [comment] 2024-01-09 11:43
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/6373

**Closed by icbaker** 2024-01-09 11:43 UTC
Labels: enhancement, needs triage
