### ISSUE TITLE
Will getDeviceInfo() ever be supported for CastPlayer?

### ISSUE THREAD

**Issue by JaCobbMedia** [androidx/media#142] opened 2022-08-04 07:29 UTC
Describe your question in detail.

I'm developing a podcast app which supports chrome cast and we recently moved to media3. We are using MediaController to handle all playback and doing some UI changes regarding of what player is currently being used (exo/cast). For that we thought using `onDeviceInfoChanged()` in `Player.Listener` and doing changes according to playbackType would be a way to go, but it didn't seem to work so after some debugging I've noticed that CastPlayer doesn't support `getDeviceInfo()` method and always returns `DeviceInfo.UNKNOWN` with playbackType `DeviceInfo.PLAYBACK_TYPE_LOCAL`.

So my question is will `getDeviceInfo()` method ever be supported for CastPlayer and is there any other way to tell where playback is happening (exo/cast) from MediaController?

**Comment by marcbaechinger** [comment] 2022-08-15 16:03
I think it should be easy to provide a `DeviceInfo` with `PLAYBACK_TYPE_REMOTE` and min/maxVolume set to 0 (see `CastPlayer.getVolume()` that always returns 0 due to setting the volume not being supported with cast player). Marking as an enhancement.

If you are using `ExoPlayer` and `CastPlayer` only you should be able to do 

```
controller.getDeviceInfo().equals(DeviceInfo.UNKNOWN)
```

If it delivers true, playback is happening on the cast player. It's a bit hacky but should work. After the change you should be able to check for `PLAYBACK_TYPE_REMOTE` as you suggest.

**Comment by ziem** [comment] 2023-01-04 12:18
@JaCobbMedia does `onDeviceInfoChanged` work for you out of the box? When is it triggered?

**Comment by marcbaechinger** [comment] 2023-01-04 12:41
On what event would you expect the `onDeviceInfoChanged` to be called?

In the context of the `CastPlayer` this issue is about, the device info only changes if [`MediaSession.setPlayer()`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L576) is called and the player is changed for instance from `ExoPlayer` to `CastPlayer` (or vice versa). In this case the [`PlayerInfo` is updated and sent to the controller](https://github.com/androidx/media/blob/c2cbb6370a265efc93661b659e70b2679506e995/libraries/session/src/main/java/androidx/media3/session/MediaSessionImpl.java#L278). `MediaControllerImpl` would [then receive the new `PlayerInfo`, find that its `DeviceInfo`  is different and call `onDeviceInfoChanged`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplBase.java#L2430).

If this is not working for you can you add some more details about how you change the `DeviceInfo` of the session?

**Comment by ziem** [comment] 2023-01-05 07:11
> the device info only changes if [MediaSession.setPlayer()](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L576) is called and the player is changed for instance from ExoPlayer to CastPlayer (or vice versa).

@marcbaechinger thanks for the description you provided. Thanks to it, I think I know where my problem is. 
In my case `MediaSession.setPlayer()` is called once as I'm using a similar approach to the one described in https://github.com/androidx/media/issues/39. I implemented `Player` and the switch between `ExoPlayer` and `CastPlayer` happens internally without additional `MediaSession.setPlayer()` calls.

The composite player thing initialy seemsed like a good solution but do you see any other problems with it that I may encounter in the future?

**Comment by marcbaechinger** [comment] 2023-01-05 12:40
I think the `DeviceInfo` is a special case because it is kind of a static property of the player that actually never changes. 

The composite approach makes IMO sense if a player is replaced by another player and this new player should continue the playback of the former player. Like when you want to transfer the playlist, `mediaItemIndex` and `positionMs` from the old to the new player.  

For the special `DeviceInfo` case, you'd have to call the listeners from your composite `ForwardingPlayer`. Assumed you already have overridden `addListener`/`removeListener`, calling `onDeviceInfoChange()` should solve the issue. I can't think of a similar case where such a static property needs to be notified.

**Comment by JaCobbMedia** [comment] 2023-01-05 13:07
@ziem I went with [UAMP](https://github.com/android/uamp/tree/media3) approach with `ReplacableForwardingPlayer` (because I needed a bit more control rather than just fully rely on `MediaController`) and basically call `onDeviceInfoChange()` whenever I switch players. But as @marcbaechinger said `MediaController` now calls `onDeviceInfoChange()` when session player gets changed and `DeviceInfo` doesn't match with previous, so if you're using `MediaController` it should work out of the box

**Comment by ziem** [comment] 2023-01-09 08:11
This helps a lot. Thank you both @JaCobbMedia & @marcbaechinger for your answers and solutions.

**Comment by marcbaechinger** [comment] 2023-01-09 23:22
Ok, cool. I close again as this is working as intended.

**Closed by marcbaechinger** 2023-01-09 23:22 UTC
Labels: enhancement
