### ISSUE TITLE
PlayerControlView will show as minimal mode when height is set to wrap_content

### ISSUE THREAD

**Issue by buntupana** [androidx/media#1542] opened 2024-07-12 11:45 UTC
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### More version details

version 1.4.0-rc01

### Devices that reproduce the issue

Pixel 8 running android 14

### Devices that do not reproduce the issue

Not applicable

### Reproducible in the demo app?

Not tested

### Reproduction steps

1.- Add PlayerControlView to a xml file
2.- Set `layout_height` property to `wrap_content`
3.- Set it up to work with PlayerView

### Expected result

Show full Player Control

### Actual result

Shows just minimal mode, showing just progress bar and play/pause button. It hides all the rest of the buttons.

Just discovered that if I set `layout_height` to `200dp` it will shows the full PlayerControlView, less than that it will be shown as minimal mode

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment] 2024-07-12 16:20
I can reproduce the issue by following the reproduction steps. Assigning it to @icbaker who has more idea on this topic to look further.

**Comment by icbaker** [comment] 2024-07-12 17:23
I'm afraid `PlayerControlView` is not intended to be used a standalone component outside of `PlayerView` (due to issues like this).

**Closed by icbaker** 2024-07-12 17:23 UTC
Labels: bug, needs triage

**Comment by davecom** [comment] 2024-09-03 08:14
> I'm afraid PlayerControlView is not intended to be used a standalone component outside of PlayerView (due to issues like this).

Thanks for the clarification. This should be made clear in the documentation.

**Comment by oceanjules** [comment] 2024-09-04 14:02
@davecom, thank you for your suggestion - you are right, I've added it - https://github.com/androidx/media/commit/c851464063b591c6ffa435646d50222034794507
