### ISSUE TITLE
Player does not upscale LL Stream once it get to lowest resolution

### ISSUE THREAD

**Issue by MHrezdovic** [androidx/media#1122] opened 2024-02-22 12:05 UTC
Describe your question in detail:

Hello, im testing LL stream in exoplayer and i have stumbled on a problem i kind of cant explain.

I have a following stream:

`https://nea.ottlab.magio.tv/live/disk/TEST_LL_RTVS_sport/DASH_LL_test_2/TEST_LL_RTVS_sport.mpd`

the behaviour i am observing is that for some reason after certain time, stream falls of to lowest bitrate and since than player does not scale it back up. If i restart the stream it gets to highest bitrate. But if i just let it run it does not upscale back up when it falls down.

from what we tested it seems to be not related to bandwidth, even when we did some network throttling and stream fell to lowest bitrate, lifting off the bandwidth throttle did not help the player it remains in lowest bitrate untill playback is restarted...

Im also trying to understand what could cause this. In exoplayer demo am i able to expose some analytics data to see what causes the player downscale the stream, like bandwidth or whatever might help me better understand, as we belive the connection in lab is stable. 

One more thing, while i played with defaultLoadControl settings:

When i set DEFAULT_MAX_BUFFER_MS = 4000 it seems to work ok and holds the highest track, when i cnage it to default 50000 it downscales to lowest.... 

Thanks

**Comment by MHrezdovic** [comment] 2024-02-22 17:12
One more note, when i change defaultLoadControl DEFAULT_MAX_BUFFER_MS = 40000 stream tends to downscale despite bandwidth does not change.

When i set it to 4000 stream upscales back.

i dont realy understand the behaviour....as the stream have a target latency so buffer should have any impact on it....

**Comment by MHrezdovic** [comment] 2024-02-26 08:24
Update: we did some changes to stream and set the segment duration to 2 sec and set the service description to:

Latency min="1000" max="10000" target="2000"/>

With this setup it seem more stable but still we observe same behaviour, once the stream falls down its not really keen to go up again...im not sure what can be the problem...as the connection is good and i understand the ABR but expectation is the stream will upscale eventualy but we still observe the issue that once the stream fells down it does not upscale back. Never only think that helps is restarting the channel...

**Comment by tonihei** [comment] 2024-02-29 13:25
(Closing as a duplicate)

**Closed by tonihei** 2024-02-29 13:25 UTC
Labels: question, needs triage

**Comment by MHrezdovic** [comment] 2024-03-01 07:12
@tonihei Thanks for the reply!

Two more question tho:

1. do you have some suggestions how to serve the LL DASH in your player ? Like is there some at leas conservative setup that we could use to serve it or best option is to remove ABR and let it play in highest quality and pray that connection is stable enough ? 

2. In case only the last fragmented chunk is issue could we somehow set the player to e.g. latency target and dynamicaly set buffer size for such stream to e.g. value that it will not download the segmented chunks near live edge ?

**Comment by tonihei** [comment] 2024-03-04 10:30
> Like is there some at leas conservative setup that we could use to serve it or best option is to remove ABR and let it play in highest quality and pray that connection is stable enough ?

You can manually select a quality if you like via track selection parameters. See https://developer.android.com/media/media3/exoplayer/track-selection. But as you say, you wouldn't know any better whether this is actually sustainable or not. 

> In case only the last fragmented chunk is issue could we somehow set the stream to e.g. latency target and dynamically set buffer size in player for such stream to e.g. value that it will not download the segmented chunks near live edge ?

The issue is triggered by loading the last chunk, not how far away from the live edge you are playing. You might be able to combine these two things together though to limit the loading to full chunks only. This is untested, but you could do something like: 
 - Set the latency target to 3 * chunk duration
 - Set the `maxBufferMs` of `DefaultLoadControl` to 2 * chunk duration.

This way the player avoids loading this last unfinished chunk and should in theory get sufficient bandwidth measurements all the time. The downside is of course that you lose some ability to play low latency because the loading is artificially restricted. 

Another, different option could be to wire up the `DefaultBandwidthMeter` of the player to also listen to a complete separate measurement load (e.g. load 1 MB of placeholder data from your server every minute or so). This should also provide a fresh measurement, but again is not ideal because this load is definitely not needed and may negatively impact your actual loading in player.

**Comment by MHrezdovic** [comment] 2024-03-07 08:31
@tonihei Thanks for the reply!
