### ISSUE TITLE
How to get shuffled order of mediaItemList in demo session app

### ISSUE THREAD

**Issue by pawaom** [androidx/media#1387] opened 2024-05-22 08:36 UTC
How to get shuffled order of mediaItemList in demo session app

In the Demo session app the `PlayerActivity` we have the 

```
private fun updateCurrentPlaylistUI() {
    val controller = this.controller ?: return
    mediaItemList.clear()
    for (i in 0 until controller.mediaItemCount) {
      mediaItemList.add(controller.getMediaItemAt(i))
    }
    mediaItemListAdapter.notifyDataSetChanged()
  }
```

Provides the List of the MediaItems that are currently being played, 
how ever if the order is shuffled , it still returns the original list of MediaItems 

Is there any way we can get the shuffled order that is being played

**Comment by marcbaechinger** [comment] 2024-05-22 10:43
I think you can do this with somelike similar to this:

```kotlin
val shuffleOrder: ArrayList<Int> = ArrayList()
var windowIndex = controller.currentTimeline.getFirstWindowIndex(/* shuffleModeEnabled= */ true)
while (windowIndex != C.INDEX_UNSET) {
  shuffleOrder.add(windowIndex)
  windowIndex =
      controller.currentTimeline.getNextWindowIndex(
          windowIndex,
          /* repeatMode= */ Player.REPEAT_MODE_OFF,
          /* shuffleModeEnabled= */ true,
      )
}
```

**Comment by pawaom** [comment] 2024-05-22 15:19
this doesnot work, what we wnt is to get the order of media When we set the shuffle mode

I think it is a feature request since a long time[ here](https://github.com/androidx/media/issues/325#issuecomment-1688480995)

What I want is to get all the list of all the shuffled mediaitems, it should be easy to get the array of shuffled items is there a simpler method to get this array

Later on I want to reorder the list using moveMediaItem  or addmediaitem as discussed [here](https://github.com/androidx/media/issues/325#issuecomment-1688480995)

**Comment by marcbaechinger** [comment] 2024-05-22 15:43
Thanks for your feedback!

> it should be easy to get the array of shuffled items is there a simpler method to get this array

I think the snippet above does answer your initial question and works. You can get the window with the `windowIndex` and then get the media item from the window. I agree this should be easy which is way it is not super important that the library is doing it for an app..

Thanks for finding the other issue. I mark this issue as a duplicate of #325 to follow your suggestion and close this issue.

**Closed by marcbaechinger** 2024-05-22 15:43 UTC
Labels: duplicate, question
