### ISSUE TITLE
Compile error with `The following Android dependencies are set to compileOnly which is not supported com.google.j2objc:j2objc-annotations:2.8`

### ISSUE THREAD

**Issue by peterkhp2203** [androidx/media#1325] opened 2024-04-29 08:38 UTC
### Version

Media3 main branch

### More version details

Hi, 
I used to library version 1.2.1 that was compiled normally, but a compile error occurs after updating version 1.3.1

and I guess, it's because of the compileOnly declaration in guava's dependencies, j2objc library.

<img width="1170" alt="스크린샷 2024-04-29 오후 5 28 58" src="https://github.com/androidx/media/assets/102123872/88f6bdaf-f190-49cb-a52e-c164c2dc281a">

### Devices that reproduce the issue

Build environment

Android Studio Iguana(stable)
AGP : 8.3.2

### Reproducible in the demo app?

Yes

### Reproduction steps

implementation media3 library version 1.3.0 or later

### Expected result

Compile successfully

### Actual result

Build error version 1.3.0 or later

### Media

version 1.2.1
<img width="687" alt="스크린샷 2024-04-29 오후 4 44 58" src="https://github.com/androidx/media/assets/102123872/ed9d717c-1507-46cd-b78c-508f799c2943">

version 1.3.1
<img width="661" alt="스크린샷 2024-04-29 오후 5 24 49" src="https://github.com/androidx/media/assets/102123872/7ce0d445-68fb-47b4-af93-b9d11d63a404">

and suppress by exclude guava library
<img width="508" alt="스크린샷 2024-04-29 오후 5 26 46" src="https://github.com/androidx/media/assets/102123872/0dafd1f4-e2ba-40b6-a49d-9e6740a84c74">

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment] 2024-05-02 12:53
Closing as a duplicate of #1312.

**Closed by tonihei** 2024-05-02 12:53 UTC
Labels: bug, needs triage
