### ISSUE TITLE
Exo Player Video is cutoff when user switches to Full Screen Portrait Mode

### ISSUE THREAD

**Issue by aasthad21** [androidx/media#1270] opened 2024-04-11 16:07 UTC
### Version

Media3 1.3.0

### Devices that reproduce the issue

Pixel 6A running Android 14
Pixel 8 Pro running Android 14, but only some users.

### Devices that do not reproduce the issue

Pixel 3 running Android Pie
New Pixel 8 Pro 
Emulators for Pixel 6A and Pixel 8 Pro

### Reproducible in the demo app?

Yes

### Reproduction steps

Not tested. The issue has been reproduced in a simplified app created for testing, which indicates the problem might not be specific to the demo app.

We tried two video urls and the video cuts off on both. Strangely it is just for selective users (2 to be particular one using Google Pixel 6A and one using Google Pixel 8 Pro)

Video URLs:
"https://cfvod.kaltura.com/pd/p/1727781/sp/172778100/serveFlavor/entryId/1_vsintz2v/v/1/ev/7/flavorId/1_6uk1wjyx/name/a.mp4"
 "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

[MainActivityKtFile.docx](https://github.com/androidx/media/files/14948384/MainActivityKtFile.docx)
[VideoPlayerKtFile.docx](https://github.com/androidx/media/files/14948383/VideoPlayerKtFile.docx)

I have attached the sample code that was used to test which is written in Kotlin in Jetpack COmpose.

Reproduction Steps:

Open the simplified test app.
Play the video in non-full-screen mode.
Switch to full-screen portrait mode.
Observe the video cutoff issue.

### Expected result

The media plays without distortion

### Actual result

The video is cut off on the top and bottom when the user switches to full-screen portrait mode, though this is not consistently reproducible across all devices.

### Media

I have added two videos that show the issue being reproduced below:

https://github.com/androidx/media/assets/166735474/b0c2d02b-6e93-439a-9bd2-854a49c81fa5

https://github.com/androidx/media/assets/166735474/8d985f75-53af-4eaf-b8c2-a42d6c428ac3

Additionally, tests conducted via BrowserStack with real devices (videos attached for Google Pixel 6 Pro and Google Pixel 8 Pro) did not reproduce the issue, indicating it might be device-specific or related to specific conditions on the affected devices.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by ryanw-mobile** [comment] 2024-05-03 21:52
I came across another closed issue #1184 and then this one.

I am happy to share my findings and analysis, hoping it could help look for the real cause.

I use Media 1.3.0 and the `PlayerView` in a Jetpack Compose `AndroidView`.

I tried setting  `resizeMode = AspectRatioFrameLayout..*`. Everything works fine, as expected, on API 33 emulator.

When I run my code on an API 34 emulator and my Pixel 7 without changing anything, not even one character, the player behaves differently. Exactly like @sunnat629 mentioned in the issue #1184, "This issue does not occur with `RESIZE_MODE_FILL`, but it is present in all other resize modes, including `RESIZE_MODE_FIXED_HEIGHT`, `RESIZE_MODE_FIXED_WIDTH`, and `RESIZE_MODE_ZOOM`."

The same unexpected behaviour was observed on VanillaIceCream emulator. That is worrying, so I believe I should raise it here.

Following the closure of case #1184, my code and the library worked as expected on API 33, so it is not a bug—even not the case on API 34 and  VanillaIceCream with the library and my code unchanged.

I suggest that we can only conclude again that the library is doing what is expected from documentation (and then close the issue). I agree with this because it works on API 33.

However, I would offer a hint that, given the library's correct implementation, it works correctly on API 33 but not later versions. If the library has no API-specific code there, it can only suggest that it receives incorrect input values on API 34+, which can be related to the view/screen dimension.

I have attached the screenshots for all AspectRatioFrameLayout modes under different API versions. The observation resonates with @sunnat629 under #1184 - that only `RESIZE_MODE_FILL` exhibits consistent behaviour under all Android versions tested. Technically, given that the same piece of code and library version works correctly on API 33 but not later, it is more on what has been changed since API 33 rather than diving deep on the implementation of the library I believe. 

Before we talk about the aspect ratio, obviously the library is picking up the wrong screen width and height on API 34, that either the video cannot be rendered, or it enlarges the video much larger than the available space for the view layout.

This is what I can observe, and I believe it is the same thing as @aasthad21  reported above.

It can be a bug caused by other teams within Google, but as you can see below, it is hard to believe that this is not a bug.

Thank you for looking into this. 


## Emulator: Pixel 7 - API 33 - Correct Output

Sequence: `ZOOM`, `FIXED_WIDTH`, `FIXED_HEIGHT`, `FIT`, `FILL`


![API33_RESIZE_MODE_ZOOM](https://github.com/androidx/media/assets/22452240/c51b73ea-09ac-4ef1-b887-6da88331cfaa) ![API33_RESIZE_MODE_FIXED_WIDTH](https://github.com/androidx/media/assets/22452240/42446d16-19dc-4a10-82a1-873b7257c010) ![API33_RESIZE_MODE_FIXED_HEIGHT](https://github.com/androidx/media/assets/22452240/6b9122b1-b473-42e0-8fcd-6cce322f2c0c) ![API33_RESIZE_MODE_FIT](https://github.com/androidx/media/assets/22452240/e9e9b54c-74fd-40e6-8703-891fe2d3ebc4) ![API33_RESIZE_MODE_FILL](https://github.com/androidx/media/assets/22452240/0685a613-aa59-41bd-b45b-16d381cf9cfd)


## Emulator: Pixel 7 - API 34 - Distorted Output

![API34_RESIZE_MODE_ZOOM](https://github.com/androidx/media/assets/22452240/ca91cd92-d981-48ab-86f4-43d0d795b4a8) ![API34_RESIZE_MODE_FIXED_WIDTH](https://github.com/androidx/media/assets/22452240/abc04499-4b25-4097-aa76-c40a770075e6) ![API34_RESIZE_MODE_FIXED_HEIGHT](https://github.com/androidx/media/assets/22452240/27b7aee6-71b6-4dc5-888a-038b08ca6916) ![API34_RESIZE_MODE_FIT](https://github.com/androidx/media/assets/22452240/417878db-7270-402a-8d5d-ae0f01e95f00) ![API34_RESIZE_MODE_FILL](https://github.com/androidx/media/assets/22452240/f2abb7c5-edeb-4d90-bb85-2fbf1aff0cc1)


## Emulator: Pixel 7 - VanillaIceCream

![V_RESIZE_MODE_ZOOM](https://github.com/androidx/media/assets/22452240/43082301-d19d-48d9-8e07-ca9579163d4b) ![V_RESIZE_MODE_FIXED_WIDTH](https://github.com/androidx/media/assets/22452240/9ae930ab-16b1-40e2-b864-1a5aadabe997) ![V_RESIZE_MODE_FIXED_HEIGHT](https://github.com/androidx/media/assets/22452240/eb770559-b763-43e9-b30e-3909060d289e) ![V_RESIZE_MODE_FIT](https://github.com/androidx/media/assets/22452240/7ae60a01-eb0f-47e1-bad8-ef30ce403c9a) ![V_RESIZE_MODE_FILL](https://github.com/androidx/media/assets/22452240/6741189c-b832-4db2-9321-99df8cdb1920)

**Comment by oceanjules** [comment] 2024-05-08 19:05
@aasthad21 
I have taken a look at the 2 docx files you attached and they seem the same to me. Did you mean to paste `VideoPlayer` Composable implementation in the second one?

**Comment by anushagif** [comment] 2024-05-09 03:13
https://stackoverflow.com/questions/78376656/in-pixel-7-facing-issue-like-cropping-video-with-exoplayer-when-opening-initiall

**Comment by matthewmjohnson** [comment] 2024-05-24 21:34
In the sample project on my Pixel 7 Pro, the video plays but only black screen is shown. If I try to replay once it's complete either by pressing play again or by pressing the seek button, it will play again as expected, but remains black. If I background the app and then foreground the app and attempt to replay the video only then am I able to see the video correctly scaled for RESIZE_MODE_ZOOM.

https://github.com/androidx/media/assets/13541377/9f5bf79f-89c5-461b-b804-1eae3ac100b1

**Comment by MDXDave** [comment] 2024-06-14 10:03
The issue still persists.
I could reproduce it on Pixel 6/7a and Pixel 8.

**Comment by ryanw-mobile** [comment] 2024-06-14 10:11
> The issue still persists.
> I could reproduce it on Pixel 6/7a and Pixel 8.

From my test results, it seems to me the android os version is more of a factor than device. Which version are they running?

**Comment by MDXDave** [comment] 2024-06-14 10:57
The bug was introduced with on of the latest Android 14 updates ([this issue](https://github.com/androidx/media/issues/1237#issuecomment-2090106301) mentioned QPR2/March 5th).  
On A13 with the Pixel 7a everything works as expected but Pixel devices with the latest Android 14 version have this issue

**Comment by oceanjules** [comment] 2024-06-20 11:04
Duplicate of https://github.com/androidx/media/issues/1237

**Closed by oceanjules** 2024-06-20 11:04 UTC
Labels: duplicate, bug: in dependency
