### ISSUE TITLE
Offline Playback Error - MediaCodecVideoRenderer

### ISSUE THREAD

**Issue by taransinghlayal** [androidx/media#1684] opened 2024-09-02 05:48 UTC
I have a DASH Content (.mpd) which is working fine in online mode. But after downloading the same content I am facing one error as mentioned below. It appears there is some issue with the Video/Audio Codec but if the content is playing online, we are not able to figure out why this is not working in Offline mode. The key rotation is enabled for this content so I am generating the uuid after fetching from the segment url.

The Codec specifed in the Online .mpd files for different Representation IDs are **avc1.4D400C, avc1.4D4015 , avc1.4D401E, avc1.4D401E** respectivley and the audio codec is **mp4a.40.2**.

The Codec specified in offline .mpd file which is downloaded keeps one of the codec in the file which is **avc1.4D401E** for video and the audio codec is same as online file which is **mp4a.40.2**

When I try to play the downloaded content offline. Here are the Callbacks sequence triggered from the Event Listener.

onTracksChanged
onDrmSessionAcquired
onDrmKeysRestored
Video size changed - Width: 0 Height: 0
onDrmSessionReleased

Height and width is 0 for the content so it seems the offline content is not able to render on the player. I have also sent the bug report on the email. Any help/lead will be greatly appreciated.

```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=834800, null, null, video/avc, avc1.42E01E, 834800, null, [640, 360, -1.0, ColorInfo(BT601, Full range, Unset color transfer, false)], [-1, -1]), format_supported=YES
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:257)
      at android.os.Looper.loop(Looper.java:368)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: android.media.MediaCodec$CryptoException: Crypto key not available: ERROR_DRM_NO_LICENSE
  cdm err: 0, oem err: 0, ctx: 0
  ============================== Beginning of DRM Plugin Log ==============================
    09-02 11:11:38.565 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:11:38.565 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:11:38.971 I [cdm_engine.cpp(356):AddKey] session_id = sid287, key_set_id = <empty>
    09-02 11:11:39.065 I [cdm_engine.cpp(356):AddKey] session_id = sid288, key_set_id = <empty>
    09-02 11:11:43.953 I [cdm_engine.cpp(235):CloseSession] session_id = sid287
    09-02 11:11:43.955 I [cdm_engine.cpp(235):CloseSession] session_id = sid288
    09-02 11:11:43.963 I [(0):] L3 Terminate.09-02 11:11:43.963 E [oemcrypto_adapter_dynamic.cpp(831):Level1Terminate] L1 Terminate
    09-02 11:12:29.557 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
    09-02 11:12:29.557 I found instance=widevine version=android.hardware.drm@1.4::IDrmFactory
    09-02 11:12:29.562 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:12:29.563 I [oemcrypto_adapter_dynamic.cpp(783):Initialize] Level 3 Build Info (v16): OEMCrypto Level3 Code 28917 Feb  2 2023 02:22:33
    09-02 11:12:29.563 I [(0):] Level3 Library 28917 Feb  2 2023 02:22:33
    09-02 11:12:29.567 I [oemcrypto_adapter_dynamic.cpp(797):Initialize] L3 Initialized. Trying L1.
    09-02 11:12:29.585 W [oemcrypto_adapter_dynamic.cpp(1003):LoadLevel1] Could not load L1 _oecc113.
    09-02 11:12:29.585 W [oemcrypto_adapter_dynamic.cpp(1004):LoadLevel1] Could not load L1 _oecc114.
    09-02 11:12:29.585 I [oemcrypto_adapter_dynamic.cpp(819):Initialize] Level 1 Build Info (v16): OEMCrypto Level1 code with V16 on 2021/10/28
    09-02 11:12:29.586 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:12:29.588 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0
    09-02 11:12:29.590 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:12:29.591 I [file_utils.cpp(40):Exists] stat failed: ENOENT
    09-02 11:12:29.594 E [wv_content_decryption_module.cpp(426):GetMetricsInternal] Cdm Identifier not found
    09-02 11:12:29.594 E [wv_content_decryption_module.cpp(486):CloseCdm] Cdm Identifier not found
```

**Comment by taransinghlayal** [comment] 2024-09-05 12:04
Appreciate any leads or suggestion please. @icbaker @ojw28

**Comment by rohitjoins** [comment] 2024-09-12 01:03
```
Caused by: android.media.MediaCodec$CryptoException: Crypto key not available: ERROR_DRM_NO_LICENSE
```
This appears to be a duplicate of issue https://github.com/androidx/media/issues/1431 based on the log above. Please feel free to reopen the issue if you believe otherwise.

**Comment by taransinghlayal** [comment] 2024-09-12 06:21
No this is happening for offline content only with 100% reproducbility. In online same content is playing

**Comment by rrfrias** [comment] 2024-09-16 20:58
Can you share a logcat capturing the error, email it to [android-media-github@google.com](mailto:android-media-github@google.com), mention "Issue #1684" in the Subject

**Comment by taransinghlayal** [comment] 2024-09-17 04:50
Thanks for your revert. I have shared the error from the logcat.

**Comment by rrfrias** [comment] 2024-09-20 21:15
We took a look at the bugreport you sent on September 1st, but do not see the ExoPlaybackException mentioned in comment#1. We saw an updated message on the 16th but did not see any attachments. Can you send us another bugreport that includes the problem reproduction?

**Comment by taransinghlayal** [comment] 2024-09-24 10:25
Hi @rrfrias 

I am able to identify the root cause of this issue.

While downloading the content I was fetching the PSSH key from the Initialisation Segment(.dash) of the manifest but this key was different than the ones present inside each of the leaf videos segments(.m4s).

So when I used PSSH from the first Video Segment and send it to drm scheme the content got played offline successfully.

But this PSSH key is getting changed after almost 112 segments and then there is a new PSSH key for rest of the video segments.

Since the license downloaded was with previous PSSH. Player throws error Crypto Key not available.

Can you let me know how can I handle different PSSH inside segments in case of key rotation to achieve smooth playback.

**Comment by rrfrias** [comment] 2024-09-26 18:08
If you are a Widevine licensee you can reach out to https://widevine.com/contact for documentation around this usecase. If you are not, you can write in and ask to sign up.

**Closed** 2024-09-26 18:10 UTC
Labels: question, bug: in platform drm, needs triage

**Comment by rrfrias** [comment] 2024-10-15 22:28
If you are a Widevine licensee you can reach out to https://widevine.com/contact for documentation around this usecase. If you are not, you can write in and ask to sign up. We should be able to share some documentation about how to handle key rotation for Widevine.

Do let us know if there are any other questions about this topic.
