### ISSUE TITLE
Toggling skip silence breaks the output

### ISSUE THREAD

**Issue by JureSencar** [androidx/media#712] opened 2023-10-09 06:06 UTC
### Version

Media3 1.1.1

This did not happen in ExoPlayer 2.18.7 library.

### Devices that reproduce the issue

Pixel 6a Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

In PlayerActivity replace the body in `onClick` with
```
  @Override
  public void onClick(View view) {
    player.setSkipSilenceEnabled(!player.getSkipSilenceEnabled());
  }
```
Then open and play any file (e.g. `Google Play (MP3)`).
Press the button a few times. Sometimes it is enough to just turn it on and off, sometimes it takes a few clicks.

### Expected result

The media continues playing normally with the latest skipSilenceEnabled applied.

### Actual result

The sound at the output gets corrupted until a user performs seek operation.

### Media

This seems to be independent from the container and source type (stream or local file).

**Comment by tianyif** [comment] 2023-10-09 15:15
Hi @JureSencar, 

Thanks for reporting! I can reproduce this issue even on ExoPlayer 2.19.0, while 2.18.7 is not reproducible. @tonihei I feel that the commit https://github.com/google/ExoPlayer/commit/3d82846074049e3dc0e906b9cf8266bfc949c06b is suspicious, would it be possible that this commit causes the issue here?

**Comment by tonihei** [comment] 2023-10-16 14:53
Turns out, the change that broke this is https://github.com/androidx/media/commit/52f3ee81d40c4ccd6080db675f3ebfb6511033a7 (verified by syncing directly before and at this change)

@Samrobbo Could you take a look to see what may have caused this issue?

**Comment by droid-girl** [comment] 2023-12-13 10:13
Hi @JureSencar, the fix is in the main branch

**Closed** 2023-12-13 13:16 UTC
Labels: bug
