### ISSUE TITLE
IllegalStateException in PlayerInfo.Builder when replacing a playlist with controller.setMediaItem

### ISSUE THREAD

**Issue by XuQK** [androidx/media#106] opened 2022-07-04 11:07 UTC
### Media3 Version

1.0.0-beta01

### Devices that reproduce the issue

Samsung galaxy note 10 5G running Android 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

Call `MediaController.setMediaItems(List<MediaItem> mediaItems, int startIndex, long startPositionMs)`.

It only appears occasionally, but I don't know how to catch it.

### Expected result

No Exception, or I can catch Exception.

### Actual result

App collapsed directly.

```kotlin
java.lang.IllegalStateException
	at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
	at androidx.media3.session.PlayerInfo$Builder.build(PlayerInfo.java:272)
	at androidx.media3.session.PlayerInfo.copyWithSessionPositionInfo(PlayerInfo.java:472)
	at androidx.media3.session.MediaControllerImplBase.updateSessionPositionInfoIfNeeded(MediaControllerImplBase.java:2611)
	at androidx.media3.session.MediaControllerImplBase.notifyPeriodicSessionPositionInfoChanged(MediaControllerImplBase.java:2272)
	at androidx.media3.session.MediaControllerStub.lambda$onPeriodicSessionPositionInfoChanged$8(MediaControllerStub.java:166)
	at androidx.media3.session.MediaControllerStub.$r8$lambda$8K3N0BzHfcst2s2y0qvHjJBKA_A(Unknown Source:0)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda9.run(Unknown Source:2)
	at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$13(MediaControllerStub.java:280)
	at androidx.media3.session.MediaControllerStub.$r8$lambda$4ZCfN8D7EpE2s2a8GPEAFaDx3Lw(Unknown Source:0)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda14.run(Unknown Source:4)
	at androidx.media3.common.util.Util.postOrRun(Util.java:548)
	at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:272)
	at androidx.media3.session.MediaControllerStub.onPeriodicSessionPositionInfoChanged(MediaControllerStub.java:165)
	at androidx.media3.session.MediaSessionStub$Controller2Cb.onPeriodicSessionPositionInfoChanged(MediaSessionStub.java:1781)
	at androidx.media3.session.MediaSessionImpl.lambda$notifyPeriodicSessionPositionInfoChangesOnHandler$10(MediaSessionImpl.java:683)
	at androidx.media3.session.MediaSessionImpl.$r8$lambda$JBOdLr-zICy-EiI2G8Tv5Pio78A(Unknown Source:0)
	at androidx.media3.session.MediaSessionImpl$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at androidx.media3.session.MediaSessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaSessionImpl.java:596)
	at androidx.media3.session.MediaSessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaSessionImpl.java:569)
	at androidx.media3.session.MediaLibrarySessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaLibrarySessionImpl.java:269)
	at androidx.media3.session.MediaSessionImpl.notifyPeriodicSessionPositionInfoChangesOnHandler(MediaSessionImpl.java:682)
	at androidx.media3.session.MediaSessionImpl.$r8$lambda$zYsdAycGCkw3-ZeAd9qvGjw1w-M(Unknown Source:0)
	at androidx.media3.session.MediaSessionImpl$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-07-04 12:47
Thanks for reporting! I can repro this on tip of tree.

Reproduction steps:

```
controller.setMediaItems(listWithTenItems);
// seek to last item to have currentMediaItemIndex on 9
controller.seekTo(9, C.TIME_UNSET);
// set list of items with less than 10 items (no item on index 9)
controller.setMediaItems(listWIthLessThanTenItems);
```

or in demo app:

1. Play category 'Kai Engel' with about 10 items
2. Seek to the last item
3. Go back and play a category with less than 10 items (eg. 'Silent Panter`)
4. See stack trace below.

```
java.lang.IllegalStateException
at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
at androidx.media3.session.PlayerInfo$Builder.build(PlayerInfo.java:276)
at androidx.media3.session.PlayerInfo.copyWithSessionPositionInfo(PlayerInfo.java:478)
at androidx.media3.session.MediaControllerImplBase.updateSessionPositionInfoIfNeeded(MediaControllerImplBase.java:2611)
at androidx.media3.session.MediaControllerImplBase.notifyPeriodicSessionPositionInfoChanged(MediaControllerImplBase.java:2272)
at androidx.media3.session.MediaControllerStub.lambda$onPeriodicSessionPositionInfoChanged$8(MediaControllerStub.java:166)
at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda15.run(Unknown Source:2)
at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$13(MediaControllerStub.java:280)
at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda6.run(Unknown Source:4)
at androidx.media3.common.util.Util.postOrRun(Util.java:620)
at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:272)
at androidx.media3.session.MediaControllerStub.onPeriodicSessionPositionInfoChanged(MediaControllerStub.java:165)
at androidx.media3.session.MediaSessionStub$Controller2Cb.onPeriodicSessionPositionInfoChanged(MediaSessionStub.java:1781)
at androidx.media3.session.MediaSessionImpl.lambda$notifyPeriodicSessionPositionInfoChangesOnHandler$10(MediaSessionImpl.java:683)
at androidx.media3.session.MediaSessionImpl$$ExternalSyntheticLambda8.run(Unknown Source:2)
at androidx.media3.session.MediaSessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaSessionImpl.java:596)
at androidx.media3.session.MediaSessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaSessionImpl.java:569)
at androidx.media3.session.MediaLibrarySessionImpl.dispatchRemoteControllerTaskWithoutReturn(MediaLibrarySessionImpl.java:269)
at androidx.media3.session.MediaSessionImpl.notifyPeriodicSessionPositionInfoChangesOnHandler(MediaSessionImpl.java:682)
at androidx.media3.session.MediaSessionImpl.$r8$lambda$zYsdAycGCkw3-ZeAd9qvGjw1w-M(Unknown Source:0)
at androidx.media3.session.MediaSessionImpl$$ExternalSyntheticLambda1.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

In such a case `sessionPositionInfo.positionInfo.mediaItemIndex` needs to be adjusted before it hits the `PlayerInfo.Builder.build()` method. Alternatively, the assertion may be incorrect in that `build()` method. Asserting it with `newPositionInfo` would not fail as the new `mediaItemIndex` is already reflected there.

We need to investigate what's the best fix.

**Comment by marcbaechinger** [comment] 2022-07-26 16:47
This is a duplicate of #86 that has been fixed.

**Closed by marcbaechinger** 2022-07-26 16:47 UTC
Labels: bug, duplicate

**Comment by tonihei** [comment] 2022-12-07 09:10
@yschimke: This has been fixed by https://github.com/androidx/media/commit/dddc6026e90a1b8587f40d37272565782eef9949 in beta03, see also internal bug b/244526179.

**Comment by yschimke** [comment] 2022-12-07 09:13
@tonihei thanks, was hoping that was the case.
