### ISSUE TITLE
How To play encrypted video using ExoPlayer

### ISSUE THREAD

**Issue by officialdedsec** [androidx/media#1192] opened 2024-03-17 13:19 UTC
Im trying to play my encrypted video locally Using Exoplayer in bytearry or memory stream all others are working fine but when i try to play video im getting this error
**Error Log:**

**javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT**

import android.Manifest;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import com.google.android.exoplayer2.DefaultLoadControl;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.source.ConcatenatingMediaSource;
import com.google.android.exoplayer2.source.DefaultMediaSourceFactory;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.ProgressiveMediaSource;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.util.MimeTypes;

import android.view.WindowManager;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.ref.WeakReference;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.util.Arrays;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

public class MainActivity extends AppCompatActivity {
    private PlayerView playerView;
    private SimpleExoPlayer player;
    private Button browseButton;

    private static final int PERMISSION_REQUEST_CODE = 1;
    private static final int PICK_VIDEO_REQUEST_CODE = 2;
    private static WeakReference<MainActivity> instance;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        instance = new WeakReference<>(this);

        setContentView(R.layout.activity_main);
        checkPermissions(); // Call checkPermissions() in onCreate()

        // Prevent screenshots while the video is playing
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);

        // Check if USB debugging is enabled
       // if (isUsbDebuggingEnabled()) {
       //     showUsbDebuggingDialog();
      //  }

        if (RootChecker.isDeviceRooted()) {
            showRootedDeviceDialog();
            return; // Exit the onCreate method if the device is rooted
        }

        // Check if the app is running on an emulator
        if (EmulatorDetector.isEmulator()) {
            showEmulatorDetectedDialog();
            return; // Exit the onCreate method if running on an emulator
        }

        // Check app integrity
     //   if (!AppIntegrityChecker.isSignatureValid(this)) {
            // Show error dialog and redirect to Play Store
      //      showAppCorruptDialog();
     //       return; // Exit the onCreate method if app integrity check fails
     //   }

        // Initialize ExoPlayer

        playerView = findViewById(R.id.player_view);
        player = new SimpleExoPlayer.Builder(this)
                .setLoadControl(new DefaultLoadControl())
                .build();
        playerView.setPlayer(player);;

        // Set up browse button click listener
        browseButton = findViewById(R.id.browse_button);
        browseButton.setOnClickListener(v -> pickVideo());

    }
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        if (item.getItemId() == R.id.action_open) {
            // Launch file picker activity to select video file
            pickVideo();
            return true;
        } else if (item.getItemId() == R.id.action_add) {
            // Handle "Add License" menu item click
            openAddLicenseActivity();
            return true;
        } else if (item.getItemId() == R.id.action_edit) {
            // Handle "Edit License" menu item click
            openEditLicenseActivity();
            return true;
        } else if (item.getItemId() == R.id.action_exit) {
            // Handle "Exit" menu item click
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    private void openEditLicenseActivity() {
        Intent intent = new Intent(this, EditLicense.class);
        startActivity(intent);
    }

    private void openAddLicenseActivity() {
        Intent intent = new Intent(this, AddLicense.class);
        startActivity(intent);
    }

    @Override
    protected void onResume() {
        super.onResume();
        checkPermissions(); // Call checkPermissions() in onResume() too
    }

    private void checkPermissions() {
        String[] permissions = {Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE};
        if (!arePermissionsGranted(permissions)) {
            ActivityCompat.requestPermissions(this, permissions, PERMISSION_REQUEST_CODE);
        }
    }

    private void showAppCorruptDialog() {
        new AlertDialog.Builder(this)
                .setTitle("App Corrupted")
                .setMessage("Please download the app from the Google Play Store.")
                .setPositiveButton("OK", (dialog, which) -> redirectToPlayStore())
                .setCancelable(false)
                .show();
    }

    private void redirectToPlayStore() {
        try {
            startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=com.dedseec")));
        } catch (android.content.ActivityNotFoundException e) {
            startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=com.dedseec")));
        }
        finish(); // Close the current activity
    }

    private void showRootedDeviceDialog() {
        new AlertDialog.Builder(this)
                .setTitle("Rooted Device Detected")
                .setMessage("This app cannot be used on rooted devices.")
                .setPositiveButton("Exit", (dialog, which) -> finish())
                .setCancelable(false)
                .show();
    }

    private void showEmulatorDetectedDialog() {
        new AlertDialog.Builder(this)
                .setTitle("Emulator Detected")
                .setMessage("This app cannot be used on emulators.")
                .setPositiveButton("Exit", (dialog, which) -> finish())
                .setCancelable(false)
                .show();
    }

    private void pickVideo() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("*/*");  // Filter for all file types
        String[] mimeTypes = {"video/*", "application/octet-stream"}; // Add MIME types for videos and .ded files
        intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
        startActivityForResult(intent, PICK_VIDEO_REQUEST_CODE);
    }

    private void onVideoPicked(Uri videoUri) {
        if (videoUri != null) {
            try {
                // Check if the selected file has the .ded extension
                if (!videoUri.getPath().endsWith(".ded")) {
                    showToast("Please select a .ded file");
                    return;
                }

                // Retrieve the registered key from the license file
                String registeredKey = getRegisteredKey();

                // Decrypt the video using the registered key
                byte[] encryptedVideoBytes = readBytesFromUri(videoUri);
                byte[] decryptedVideoBytes = decryptVideo(encryptedVideoBytes, registeredKey);

                // Play the decrypted video
                playDecryptedVideo(decryptedVideoBytes);
            } catch (IOException e) {
                showToast("Error reading video file: " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                showToast("Error: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            showToast("Failed to pick video");
        }
    }

    private byte[] decryptVideo(byte[] encryptedVideoBytes, String key) {
        try {
            // Call your decrypt method here
            return decrypt(encryptedVideoBytes, key);
        } catch (BadPaddingException e) {
            throw new RuntimeException("Bad padding: " + e.getMessage());
        } catch (InvalidKeyException e) {
            throw new RuntimeException("Invalid key: " + e.getMessage());
        } catch (Exception e) {
            throw new RuntimeException("Error decrypting video: " + e.getMessage());
        }
    }

    // Helper method to show toast messages
    private void showToast(String message) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
    }

    private String getRegisteredKey() {
        String filePath = getLicenseFilePath();
        File licenseFile = new File(filePath);

        if (!licenseFile.exists()) {
            // Throw error message if the license file does not exist
            showToast("License file does not exist");
            throw new RuntimeException("License file does not exist");
        }

        // Show toast message indicating that the key is being read
        showToast("Reading key from license file...");

        String key = MainActivity.readFromFile(licenseFile);

        if (key != null && !key.isEmpty()) {
            // Show toast message indicating that the key has been read successfully
            showToast("Key read successfully from license file");
            return key;
        } else {
            // Handle case where no key is registered
            showToast("No key found in license file");
            return "";
        }
    }

    private String getLicenseFilePath() {
        AddLicense addLicense = new AddLicense();
        return addLicense.getPassFilePath();
    }

    private void playDecryptedVideo(byte[] decryptedVideoBytes) {
        try {
            // Create a ByteArrayDataSource from the decrypted video bytes
            ByteArrayDataSource dataSource = new ByteArrayDataSource(decryptedVideoBytes);

            // Create a DataSource.Factory for the custom DataSource
            DataSource.Factory dataSourceFactory = new DataSource.Factory() {
                @Override
                public DataSource createDataSource() {
                    return dataSource;
                }
            };

            // Create a ProgressiveMediaSource using the custom DataSource.Factory
            ProgressiveMediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(MediaItem.fromUri(Uri.parse("dummy://dummy")));

            // Set the media source to the player
            player.setMediaSource(mediaSource);
            player.prepare();
            player.setPlayWhenReady(true); // Start playback automatically
        } catch (Exception e) {
            showToast("Error playing decrypted video: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private File createTempFile(byte[] data) {
        File tempFile = null;
        FileOutputStream fos = null;
        try {
            tempFile = File.createTempFile("temp", ".mp4", getCacheDir());
            fos = new FileOutputStream(tempFile);
            fos.write(data);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return tempFile;
    }

    private byte[] readBytesFromUri(Uri uri) throws IOException {
        InputStream inputStream = getContentResolver().openInputStream(uri);
        ByteArrayOutputStream byteBuffer = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int len;
        while ((len = inputStream.read(buffer)) != -1) {
            byteBuffer.write(buffer, 0, len);
        }
        return byteBuffer.toByteArray();
    }

    public static byte[] decrypt(byte[] encryptedData, String key) throws Exception {
        byte[] keyBytes = MessageDigest.getInstance("SHA-256").digest(key.getBytes(StandardCharsets.UTF_8));
        SecretKeySpec secretKeySpec = new SecretKeySpec(keyBytes, "AES");

        // Extract IV from encrypted data
        byte[] iv = Arrays.copyOfRange(encryptedData, 0, 16);

        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, new IvParameterSpec(iv));
        return cipher.doFinal(encryptedData, 16, encryptedData.length - 16);
    }

    private void playVideo(Uri videoUri) {
        MediaItem mediaItem = MediaItem.fromUri(videoUri);
        player.setMediaItem(mediaItem);
        player.prepare();
        player.setPlayWhenReady(true); // Start playback automatically
    }

**Comment by oceanjules** [comment] 2024-03-18 12:21
Your `byte[] decrypt(byte[] encryptedData, String key)` is the one throwing the exception and the problem is in how you handle the keys/cipher creation.

The error suggests your content is either encrypted incorrectly or you've misconfigured the crypto algorithm or key info.

Since this is not a bug in ExoPlayer, I will close this issue. However, you may be lucky finding help and guidance on Stackoverflow among the cryptography/javax/android experts.

**Closed by oceanjules** 2024-03-18 12:21 UTC
Labels: question, needs triage
