### ISSUE TITLE
Notification reappears after closing app when media is paused.

### ISSUE THREAD

**Issue by muhammadalkady** [androidx/media#7] opened 2021-11-23 13:32 UTC
Media notification reappears when media is paused and its buttons not working when the app is removed from recents[demo-session].
Steps to reproduce:
1- Run demo-session app.
2- Play some media.
3- Pause it.
4- Remove the app from recents.
5- Notification will reappear and the media button does nothing.

See video [here](https://photos.app.goo.gl/A3uvxFJua8wGomsdA).

Device: Xiaomi mi a2 android 10

**Comment by marcbaechinger** [comment] 2021-12-15 11:33
Thanks for reporting. I tested the behaviour on Android 10 and Android 11 and I can confirm that the behaviour is odd. I don't have the same experience as you with a notification that is re-appering but there are several things we should look at after the app has been stopped. Needs further investigation.

Case 1) Android 10: Notification re-apprears (se repro steps above)


Case 2) Android 10: Notification with stale media item displayed

1 - Run demo-session app
2 - Play a media item

```
adb -s emulator-5556 shell dumpsys media_session
MEDIA SESSION SERVICE (dumpsys media_session)

[...]

User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: null
  Last MediaButtonReceiver: PendingIntent{ee26742: PendingIntentRecord{e84353 androidx.media3.demo.session startForegroundService}}
  Restored MediaButtonReceiver: null
  Restored MediaButtonReceiverComponentType: 0
  Media button session is androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
  Sessions Stack - have 1 sessions:
    androidx.media3.session.id. androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
      ownerPid=9102, ownerUid=10146, userId=0
      package=androidx.media3.demo.session
      launchIntent=PendingIntent{c9a2490: PendingIntentRecord{35959ec androidx.media3.demo.session startActivity (whitelist: d8a2167:+30s0ms)}}
      mediaButtonReceiver=PendingIntent{ee26742: PendingIntentRecord{e84353 androidx.media3.demo.session startForegroundService}}
      active=true
      flags=7
      rating type=0
      controllers: 2
      state=PlaybackState {state=3, position=5774, buffered position=75572, speed=1.0, updated=1619327, actions=3670015, custom actions=[], active item id=1, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_MUSIC flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata: size=8, description=Leaving, null, null
      queueTitle=null, size=9

  Session2Tokens:
Audio playback (lastly played comes first)
  uid=10146 packages=androidx.media3.demo.session 

```

3 - Pause the media
```
adb -s emulator-5556 shell dumpsys media_session
MEDIA SESSION SERVICE (dumpsys media_session)

2 sessions listeners.
[...]
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: null
  Last MediaButtonReceiver: PendingIntent{ee26742: PendingIntentRecord{e84353 androidx.media3.demo.session startForegroundService}}
  Restored MediaButtonReceiver: null
  Restored MediaButtonReceiverComponentType: 0
  Media button session is androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
  Sessions Stack - have 1 sessions:
    androidx.media3.session.id. androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
      ownerPid=9102, ownerUid=10146, userId=0
      package=androidx.media3.demo.session
      launchIntent=PendingIntent{c9a2490: PendingIntentRecord{35959ec androidx.media3.demo.session startActivity (whitelist: d8a2167:+30s0ms)}}
      mediaButtonReceiver=PendingIntent{ee26742: PendingIntentRecord{e84353 androidx.media3.demo.session startForegroundService}}
      active=true
      flags=7
      rating type=0
      controllers: 2
      state=PlaybackState {state=2, position=110914, buffered position=170370, speed=1.0, updated=1730623, actions=3670015, custom actions=[], active item id=1, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_MUSIC flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata: size=8, description=Leaving, null, null
      queueTitle=null, size=9

  Session2Tokens:
Audio playback (lastly played comes first)
  uid=10146 packages=androidx.media3.demo.session 

```
4 - Remove app from list of recent apps
5 - Notification is still there in paused state showing metadata of Media item for instance 'Leaving' 

```
adb -s emulator-5556 shell dumpsys media_session
MEDIA SESSION SERVICE (dumpsys media_session)

2 sessions listeners.
[...]
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: null
  Last MediaButtonReceiver: PendingIntent{b406bf4: PendingIntentRecord{e0a7f1d androidx.media3.demo.session startForegroundService}}
  Restored MediaButtonReceiver: null
  Restored MediaButtonReceiverComponentType: 0
  Media button session is androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
  Sessions Stack - have 1 sessions:
    androidx.media3.session.id. androidx.media3.demo.session/androidx.media3.session.id. (userId=0)
      ownerPid=9927, ownerUid=10146, userId=0
      package=androidx.media3.demo.session
      launchIntent=PendingIntent{aa12592: PendingIntentRecord{35959ec androidx.media3.demo.session startActivity (whitelist: d8a2167:+30s0ms)}}
      mediaButtonReceiver=PendingIntent{b406bf4: PendingIntentRecord{e0a7f1d androidx.media3.demo.session startForegroundService}}
      active=true
      flags=7
      rating type=0
      controllers: 1
      state=PlaybackState {state=0, position=0, buffered position=0, speed=1.0, updated=2525699, actions=3670015, custom actions=[], active item id=0, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_MUSIC flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata: null
      queueTitle=null, size=0

  Session2Tokens:
Audio playback (lastly played comes first)
  uid=10146 packages=androidx.media3.demo.session 
```

Note the number of connected controllers is down to 1 above and the state is back to 0 (NONE).

6 - User clicks the notification and is taken to the PlayerActivity that shows an empty playlist

**Comment by spun** [comment] 2021-12-15 11:55
Hi, I was having the same problem and my fix was changing `onStartCommand` to return  `START_NOT_STICKY`. The default `START_STICKY` was relaunching my MediaLibraryService after removing the app from recents.

The Service documentation says:

__START_STICKY__
> makes sense for things that will be explicitly started and stopped to run for arbitrary periods of time, such as a service performing background music playback" 

Now I don't know if my fix can cause problems. Could you explain why `START_STICKY` is important and if it could be the cause of the notification reappearing?

**Comment by muhammadalkady** [comment] 2021-12-15 12:23
@marcbaechinger This happens only when media paused from notification.
I have also tried with Android 11 same issue.

**Comment by muhammadalkady** [comment] 2021-12-20 13:39
@marcbaechinger This is right. The service is crashing, but I can not see the crash in the logs. The logs below happen after pausing the media from notification and killing the app from recents.
```
2021-12-20 15:32:49.198 1863-3336/? W/ActivityManager: Scheduling restart of crashed service androidx.media3.demo.session/.PlaybackService in 1000ms for start-requested
2021-12-20 15:32:50.230 1863-1906/? I/ActivityManager: Start proc 10345:androidx.media3.demo.session/u0a288 for service {androidx.media3.demo.session/androidx.media3.demo.session.PlaybackService}
2021-12-20 15:32:50.952 10345-10345/androidx.media3.demo.session D/PlaybackService: onCreate: 
```

**Comment by marcbaechinger** [comment] 2022-01-26 15:22
I think preventing the crash is the first step here. I'm going to close this issue. Please reopen if you think there is a problem with the library that causes the crash you are seeing.

**Closed by marcbaechinger** 2022-01-26 15:22 UTC
Labels: bug

**Comment by muhammadalkady** [comment] 2022-01-27 13:42
The crash in the library demo and it is not showing in the logs. This happens also in my implementation so I think this is a bug in the lib itself.

**Comment by vfsfitvnm** [comment] 2022-04-15 15:31
Here's a consequence of the reappearing notification:

1. Run `demo-session` app;
2. Play any media;
3. Leave the app and clean it from recents;
4. Pause the media and close;
5. Press any button of the reappeared notification;
6. Reopen the app;
7. Wait for crash.

```
E/ActivityManager: ANR in androidx.media3.demo.session
Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3a10fd8 u0 androidx.media3.demo.session/.PlaybackService}
```


https://user-images.githubusercontent.com/46219656/163589078-96bfefb9-cf99-44cd-8fea-6c4a147b8727.mp4
