### ISSUE TITLE
i'm facing an issue regarding the media3 exo player controlls position in a horizoantal tab .

### ISSUE THREAD

**Issue by sid1605** [androidx/media#1119] opened 2024-02-22 05:32 UTC
![Screenshot 2024-02-21 113358](https://github.com/androidx/media/assets/137288149/78e66737-2542-4fb3-8f58-5a1fe3e9dd2a)

-------------------------

i'm making a video player in jetpack compsoe using media3 exo player. thae problem i'm facing is that in a horizontal tab mode i give an aspect ration of 16/9f to my player and defined 60% of total screen width for the player so the default controlls should be visible inside the defined 60% width but they are visible in the end of screen or outside the defined area for the video player. i'm using media3 version 1.2.1 and all latest version of dependencies
i'm mentioning the screenshots for my problem
-------------------------
`AndroidView(
            factory = {
                PlayerView(context).apply {
                    useController = true
                    resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FILL
                    player = exoPlayer
                    setShowBuffering(PlayerView.SHOW_BUFFERING_WHEN_PLAYING)
                    hideController()
                    setKeepContentOnPlayerReset(true)
                    setShowNextButton(false)
                    setShowPreviousButton(false)
                    setFullscreenButtonClickListener {
                        isFullscreen = !isFullscreen
                        setScreenValue()
                        handleFullscreen(isFullscreen, context)
                    }
                    controllerShowTimeoutMs = 2000
                    setControllerVisibilityListener(PlayerView.ControllerVisibilityListener { visibility ->
                        isControlVisible = visibility == View.VISIBLE
                        Log.i("fsdsdsdajsdfsdsdsdsdsdsdsdsdsdsdsdsdsdsd", "TravelxpPlayer: hello sid")
                        val selectedAudioLanguage = exoPlayer.audioFormat?.language
                        if (defLanguage != selectedAudioLanguage) {
                            defLanguage = selectedAudioLanguage
                            if (selectedAudioLanguage != null) {
                                coroutineScope.launch {
                                    userStore.setLanguage(selectedAudioLanguage)
                                }
                            }
                        }
                    })
                    val progressBar = findViewById<ProgressBar>(R.id.exo_buffering)
                    progressBar.indeterminateDrawable.setTint(
                        ContextCompat.getColor(context, R.color.travelxp_red),
                    )
                    layoutParams = FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT
                    )
                    setShowSubtitleButton(true)
                }
            }, modifier = Modifier
                .aspectRatio(aspectRatio)
                .fillMaxHeight()
        )`

**Comment by oceanjules** [comment] 2024-02-22 16:05
Duplicate of https://github.com/androidx/media/issues/1120

**Closed by oceanjules** 2024-02-22 16:05 UTC
Labels: question, needs triage
