### ISSUE TITLE
How to reduce glass to glass latency?

### ISSUE THREAD

**Issue by renaudcerrato** [androidx/media#1180] opened 2024-03-13 13:47 UTC
I'm receiving a raw H264 stream by TCP (with PTS informations) using a custom `Extractor`, feeding it to an `H264Reader`, and I'm looking to achieve the lowest latency. The stream is coming from the local network only, and I may be considering switching to UDP at some point if required.

For an **evaluation purpose** I've run both the streamer and the player on the same device (in 2 different process), the streamer actually streams the current screen. I'm using a zeroified load control:

```kotlin
val loadControl = DefaultLoadControl.Builder()
            .setBufferDurationsMs(0, 0, 0, 0)
            .setPrioritizeTimeOverSizeThresholds(true)
            .build()
```

I've put a running timer at the top of screen, and the best I can achieve is roughly 250ms(800x390@1Mbps) which sounds quite a lot:

<img width="424" alt="image" src="https://github.com/androidx/media/assets/1930949/89648634-8ac6-4c31-9e2a-9ddc8cb65279">

Is there anything I could look at to improve the latency ? I'm sure there's a lot of room for improvements and I may be missing something.

Related to https://github.com/androidx/media/issues/1179

**Comment by tonihei** [comment] 2024-03-14 16:16
As you say, this is more or less a duplicate of #1179, which I just converted to a feature request.

**Closed by tonihei** 2024-03-14 16:16 UTC
Labels: question, needs triage
