### ISSUE TITLE
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs

### ISSUE THREAD

**Issue by amit12kumardish** [androidx/media#1661] opened 2024-08-28 09:33 UTC
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs

**Comment by tonihei** [comment] 2024-08-29 16:07
This is a duplicate of #1660

**Closed by tonihei** 2024-08-29 16:07 UTC
Labels: question, needs triage
