### ISSUE TITLE
add support to play mpd dash which doesn't have default kid

### ISSUE THREAD

**Issue by imrsaleh** [androidx/media#916] opened 2023-12-21 23:19 UTC
add support for playing DASH that do not have a default KID (Key ID) in ExoPlayer.
This can be achieved by updating ExoPlayer to support playing DASH files without a default kid or by modifying the default behavior of the library to handle this type of DASH correctly.

**Comment by oceanjules** [comment] 2023-12-22 09:00
Duplicate of https://github.com/androidx/media/issues/563, https://github.com/androidx/media/issues/780, https://github.com/google/ExoPlayer/issues/9169,

**Closed by oceanjules** 2023-12-22 09:00 UTC
Labels: duplicate, wont fix: intended behavior
