### ISSUE TITLE
Is there a way to disable unused subtitle tracks from being downloaded?

### ISSUE THREAD

**Issue by gtwelve** [androidx/media#1900] opened 2024-11-18 07:27 UTC
I am currently implementing a new feature to allow playing videos in my app. 
Each Video has around 20 subtitle files which I load into the associated MediaItem with:

`mediaItem.setSubtitleConfigurations(ImmutableList.copyOf(subtitleList));`

I have noticed when inspecting the network requests that all 20 subtitles files are loaded from the server which causes (in my opinion) unnecessary network requests and bandwidth usage.

Is this typical behaviour for ExoPlayer or could I be doing something wrong?

I am creating each subtitle file by using:

```
MediaItem.SubtitleConfiguration.Builder subBuilder = new MediaItem.SubtitleConfiguration.Builder(entryUri)
    .setMimeType(subtitleMime)
    .setLanguage(entryLanguage);
```

and setting 

`subBuilder.setSelectionFlags(C.SELECTION_FLAG_DEFAULT);`

on the subtitle entry associated with the users language preference, which is the subtitle file I want to play by default and ideally the only subtitle file which is loaded from the server.

Any advice on, if loading all 20 is expected or if there is a way to prevent this from happening would be appreciated.

I am currently using release `1.4.1`

**Comment by icbaker** [comment] 2024-11-21 17:49
Duplicate of https://github.com/androidx/media/issues/1721

**Closed by icbaker** 2024-11-21 17:49 UTC
Labels: question, needs triage
