### ISSUE TITLE
Loading an external exolist.json file doesn't work with TV API >= 31

### ISSUE THREAD

**Issue by gramound** [androidx/media#687] opened 2023-09-30 05:24 UTC
### Version

Media3 1.1.1

### Devices that reproduce the issue

All TV devices with API >= 31.

For example, reproduced with TV emulator + 'S' Android TV image for x86 on Windows, and arm64-v8a on Mac.

### Devices that do not reproduce the issue

TV API <= 30. For example, cannot reproduce on TV emulator + 'R' Android TV image for x86.

Phone or Tablet devices are not affected. Even API >= 31.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Open the project in Android Studio
1. click 'Run', 'Edit Configurations...'
1. Select the 'demo' configuration
1. In the 'General' tab, under 'Launch Options', 'Launch', change 'Default Activity' to 'URL'
1. In the 'URL' field, type https://github.com/androidx/media/raw/release/demos/main/src/main/assets/media.exolist.json
1. Save and run the 'demo' configuration

Or manually type the command:
```
adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d 'https://github.com/androidx/media/raw/release/demos/main/src/main/assets/media.exolist.json' 
```

### Expected result

The `SampleChooserActivity` should launch with the specified exolist.json
```
I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://github.com/... flg=0x10000000 cmp=androidx.media3.demo.main/.SampleChooserActivity} from uid 2000
```

### Actual result

System toast message saying "You don't have an app that can do this". 
```
I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://github.com/... flg=0x10000000 cmp=com.android.tv.frameworkpackagestubs/.Stubs$BrowserStub} from uid 2000
```

### Media

![Screenshot_20230929_220725](https://github.com/androidx/media/assets/16066120/13847838-bb27-4576-b201-d0111ac92279)

This was also reported by NimaTajfar in old ExoPlayer issues #9437 and #9441, but was missing important details:
* This is TV-specific, and API version-specific, but not ATV or GTV specific.
* The exact 'am start' command included above.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment] 2023-10-04 11:47
Thanks for your report. 

I think this is a duplicate of #438. 

It works if you are using the specific action `androidx.media3.demo.main.action.BROWSE` that we added for this reason:

```bash
adb -s emulator-5554 shell am start -a androidx.media3.demo.main.action.BROWSE \
    -d 'https://github.com/androidx/media/raw/release/demos/main/src/main/assets/media.exolist.json'
```

If you want to use it from Android Studio like you explain above, then you can change the `Launch options` in `Run configuration`  to URL and add `-a androidx.media3.demo.main.action.BROWSE` as the `Launch flags`. With this in place I was able to start the app from AS to an TV emulator running API 33.

**Comment by marcbaechinger** [comment] 2023-10-04 13:02
I added a not in the documentation about using `androidx.media3.demo.main.action.BROWSE` on TV devices.

https://developer.android.com/guide/topics/media/exoplayer/demo-application#2-loading

I'm closing this issue. Please open a new one if there are further issues regarding starting the app on ATV.

**Closed by marcbaechinger** 2023-10-04 13:02 UTC
Labels: bug, duplicate

**Comment by gramound** [comment] 2023-10-04 16:10
Thanks Marc! I always wondered what that custom action was for, but never bothered digging (I should have).
And sorry I missed #438 in my search (I must have searched in the old ExoPlayer repo only).
