### ISSUE TITLE
MediaCodecVideoRenderer error during playback (Decoder Failed)

### ISSUE THREAD

**Issue by robm92** [androidx/media#582] opened 2023-08-15 11:05 UTC
### Version

Media3 1.1.0

### Devices that reproduce the issue

Devices by decoder name

**c2.exynos.h264.decoder**
 - Pixel 7 Pro
 
**OMX.qcom.video.decoder.avc**
 - Galaxy A52 5G (Android 13)
 - OnePlus 8 (Android 13)
 - OnePlus 8 Pro (Android 13)
 - Galaxy S10 (Android 12)
 - Pixel 2 (Android 11)
 - Galaxy A9 (2018) (Android 10)
 - Galaxy S20 FE (Android 13)
 - Poco F2 Pro (Android 12)

**OMX.Exynos.avc.dec**
 - Galaxy S20 Ultra 5G (Android 13)
 - Galaxy Note 10 (Android 12)
 - Galaxy Tab S6 Lite (Android 13)
 - Galaxy XCover 5 (Android 13)
 - Galaxy S10 (Android 12)
 - Galaxy S20+ 5G (Android 13)

**OMX.MTK.VIDEO.DECODER.AVC**
 - Red Note 8 Pro

**c2.qti.avc.decoder**
 - Redmi Note 11 Pro 5G 
 - Galaxy S21 Ultra 5G (Android 13)
 - Galaxy A52s 5G

### Devices that do not reproduce the issue

As this is difficult to replicate, I cannot confirm however it appears to be most prominent on Samsung devices.

### Reproducible in the demo app?

Not tested

### Reproduction steps

We are sourcing a Samsung device to attempt to replicate however users have reported:
"It will happen just in the middle of watching content. I could view a few videos and have no issues and then the playback will start buffering and the error will be displayed."

Playback is of an HLS stream

### Expected result

Playback should not be interrupted

### Actual result

Non-fatal Exception: k4.v0: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.64001E, 1121472, null, [640, 360, 25.0, null], [-1, -1]), format_supported=YES
       at androidx.media3.session.PlayerInfo.fromBundle(PlayerInfo.java:377)
       at androidx.media3.session.MediaControllerStub.onPlayerInfoChangedWithExclusions(MediaControllerStub.java:4)
       at androidx.media3.session.MediaSessionStub$Controller2Cb.onPlayerInfoChanged(MediaSessionStub.java:53)
       at androidx.media3.session.MediaSessionImpl.dispatchOnPlayerInfoChanged(MediaSessionImpl.java:144)
       at androidx.media3.session.MediaSessionImpl.access$600(MediaSessionImpl.java:144)
       at androidx.media3.session.MediaSessionImpl$PlayerInfoChangedHandler.handleMessage(MediaSessionImpl.java:144)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Caused by android.os.RemoteException: Decoder failed: OMX.Exynos.avc.dec **<--- interchangeable with the device's decoder**
       at androidx.media3.session.PlayerInfo.fromBundle(PlayerInfo.java:377)
       at androidx.media3.session.MediaControllerStub.onPlayerInfoChangedWithExclusions(MediaControllerStub.java:4)
       at androidx.media3.session.MediaSessionStub$Controller2Cb.onPlayerInfoChanged(MediaSessionStub.java:53)
       at androidx.media3.session.MediaSessionImpl.dispatchOnPlayerInfoChanged(MediaSessionImpl.java:144)
       at androidx.media3.session.MediaSessionImpl.access$600(MediaSessionImpl.java:144)
       at androidx.media3.session.MediaSessionImpl$PlayerInfoChangedHandler.handleMessage(MediaSessionImpl.java:144)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### Media

An example of a known issue stream URL has been emailed to android-media-github@google.com

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-09-04 11:30
I'm afraid there is probably not much we can do about it. The issue is either
 (a) invalid (non-spec-compliant) media where decoders correctly fail to parse it. 
or
 (b) valid media and a decoder bug that fails to parse it.

For case (a), you'd need to fix the media as we generally don't attempt to work around media issues and for case (b) you'd need to check with the device manufacturer (or rather the codec producer) to fix their code and wait for system updates on these devices.

Based on the number of different codecs involved (from different companies), I guess it's more case (a) and something related to your media. I'd suggest to check with media validation or analysis tools to see if there any obvious problems with these streams. It's also a common and established format with no obvious special properties, so this also points more to a media issue than a decoder issue.

The only case that would allow us to help you effectively is when we establish it's a decoder issue and we also know a way working around it from the player code. I'll close the issue under the assumption that this is unlikely, but feel free to reopen file a new one if you have more information that could allow us to make progress.

**Closed by tonihei** 2023-09-04 11:30 UTC
Labels: bug, needs triage
