### ISSUE TITLE
Detected problems with API compatibility.  

### ISSUE THREAD

**Issue by flsdiver** [androidx/media#367] opened 2023-04-30 14:00 UTC
### Media3 Version

ExoPlayer 2.18.6

### Devices that reproduce the issue

Android studio emulator...AndtroidTV API 28.

### Devices that do not reproduce the issue

Actual devices.

### Reproducible in the demo app?

Not tested

### Reproduction steps

When running on SDK >= 27.
After calling
```
mInternalPlayer = new ExoPlayer.Builder(this.mAppContext, renderersFactory)
                .setTrackSelector(mTrackSelector)
                .setMediaSourceFactory(new DefaultMediaSourceFactory(mDataSourceFactory))
                .build();
```
After stop video and close activity 1st time only emulator displays popup wtih....Detected problem with API compatibility.

Enable Strict mode in oncreate application:
```
        if (BuildConfig.DEBUG && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectNonSdkApiUsage()
                    .penaltyLog()
                    .build());
        }
```

### Expected result

Don't use reflections in code anymore.

### Actual result

throws stack trace for this incompatibility
```
2023-04-30 09:34:47.115 14877-14877/com.xxxxx.tv I/ExoPlayerImpl: Init ac41cef [ExoPlayerLib/2.18.6] [generic_x86, sdk_google_atv_x86, unknown, 28]
2023-04-30 09:34:47.151 14877-14877/com.xxxxx.tv W/com.xxxxxx.tv: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
2023-04-30 09:34:47.152 14877-14877/com.xxxxx.tv D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/media/AudioTrack;->getLatency()I
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.google.android.exoplayer2.audio.AudioTrackPositionTracker.<init>(AudioTrackPositionTracker.java:209)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:607)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:79)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Builder.build(DefaultAudioSink.java:351)
        at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:634)
        at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:305)
        at com.google.android.exoplayer2.ExoPlayerImpl.<init>(ExoPlayerImpl.java:244)
        at com.google.android.exoplayer2.ExoPlayer$Builder.build(ExoPlayer.java:1131)
        at com.xxxx.exo.player.ExoMediaPlayer.prepareAsync(ExoMediaPlayer.java:159)

```

Using reflection at line 209 of AudioTrackPositionTracker which shouldn't be used.
        getLatencyMethod = AudioTrack.class.getMethod("getLatency", (Class<?>[]) null);

### Media

Any media

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2023-05-02 18:42
> Don't use reflections in code anymore.

Are you asking us to remove the reflection in [`AudioTrackPositionTracker`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/AudioTrackPositionTracker.java#L209)?

If this is the case I don't think we are going to do this. This is intended as it is. We use reflection in other cases ase well (see `DefaultMediaSourceFactory` for instance). While I agree this shouldn't be done normally, in the cases we do it we think it is justified.

Beside adding the strict mode policy checker to the app to make it crash. Have you found some issues with the reflection code in Media3? If this is the case we should investigate. In such a case please report what the observed problem is so we can look into this. If it is just about the recommendation to not use reflection, I'd say, yes, but....

Please clarify the issue that was caused by that line you are mentioning. No rush with this, but without it I think I'm gaing to close this issue soon.

**Comment by mustfaunlu** [comment] 2024-07-23 12:56
can you resolve this issue @flsdiver

**Closed** 2024-07-23 13:32 UTC
Labels: wont fix: intended behavior
