### ISSUE TITLE
Headers are not passed in live streaming request

### ISSUE THREAD

**Issue by kosiarska** [androidx/media#1241] opened 2024-04-03 15:07 UTC
This is my code:
```val mediaItem: MediaItem =
        MediaItem
          .Builder()
          .setUri(channel.sourceURL?.url ?: "")
          .setLiveConfiguration(
            MediaItem.LiveConfiguration.Builder()
              .setMaxPlaybackSpeed(1f)
              .build()
          )
          .build()

      val dataSourceFactory = ResolvingDataSource.Factory(source()) { dataSpec ->
        var token = refreshToken()
        val headersMap: MutableMap<String, String> = HashMap()
        headersMap["Authorization"] = "Bearer $token"
        dataSpec.withRequestHeaders(headersMap)
      }

      val mediaSource = HlsMediaSource.Factory(dataSourceFactory)
        .createMediaSource(mediaItem)

      player.addListener(this)
      player.setMediaSource(mediaSource)
      player.prepare()
      player.play()

   fun source() {
    val headersMap: MutableMap<String, String> = HashMap()
    headersMap["Authorization"] = "Bearer $token"
    val factory = DefaultHttpDataSource.Factory()
      .setDefaultRequestProperties(headersMap)
      .setUserAgent("agent")
      return factory;
   }

```

When I use network inspector in android studio I don't see this authorization header and also no user agent. This happens on android tv platform (android version 13).
Exoplayer library version is 2.16.0.

**Comment by icbaker** [comment] 2024-04-03 16:28
The issue title mentions "in live streaming request". Do you see the same problematic behaviour playing VOD content, or is this a live-specific issue?

----

It looks like you're trying to set the `Authorization` header twice - why is that? It's probably clearer to reason about if you only set it once, either on `DefaultDataSource.Factory` if it's meant to be the same for every media item, or inside `ResolvingDataSource.Resolver.resolveDataSpec` if it should be newly generated for each media item.

----

> ```
> fun source() {
>   val headersMap: MutableMap<String, String> = HashMap()
>   headersMap["Authorization"] = "Bearer $token"
>```

I don't think there's any value called `token` in scope here, so I don't think this substitution will work? In fact I'm not sure this even compiles.

----

I'm afraid it's hard for us to investigate further without a minimal reproducible example. I'd suggest you step through with a debugger to see what happens to the headers - you should see them being handled here (this is the 2.16.0 version of this class):

https://github.com/androidx/media/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L592-L601

**Comment by kosiarska** [comment] 2024-04-03 16:50
I'm afraid that I cannot disclose more without consequences. But I think there is something causing this in the code around it. I created minimal test project and it works. So definitely not on the exoplayer side. Sorry for wasting your time. I will post solution here when I will know more about this case.

**Comment by kosiarska** [comment] 2024-04-04 10:30
Turns out I first called setMediaSource and right after that setMediaItem. It seems that this call overrides previous call and that's why passing headers did not work at all.

**Closed** 2024-04-04 12:39 UTC
Labels: question
