### ISSUE TITLE
PlayerView and Playercontrollview Next button not clickable even when using ForwardingPlayer for the Last mediaitem of Playlist

### ISSUE THREAD

**Issue by pawaom** [androidx/media#1588] opened 2024-08-02 06:03 UTC
### Version

Media3 1.4.0

### Devices that reproduce the issue

Samsung Galaxy Tab 7  android version 14
Pixel 2 emulator api 26 Android 8.0.0

### Reproducible in the demo app?

Yes

### Reproduction steps

Add a Playercontrolview in activity_player.xml 

```
<androidx.media3.ui.PlayerControlView

      android:background="@color/purple_200"
      android:id="@+id/playerControlView"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_gravity="center"
      app:controller_layout_id="@layout/custom_exo_controller_view"

      app:show_timeout="0" />
```
**custom_exo_controller_view.xml**
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"

    android:layoutDirection="ltr"
    android:orientation="vertical"
    android:paddingStart="20dp"
    android:paddingEnd="20dp"
    tools:targetApi="28">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:orientation="horizontal"
        android:paddingTop="4dp">

        <ImageButton
            android:id="@id/exo_shuffle"
            style="@style/ExoStyledControls.Button.Bottom.Shuffle"
            app:tint="@color/black"
            app:tintMode="src_in" />

        <ImageButton
            android:id="@id/exo_prev"
            style="@style/ExoMediaButton.Previous"
            app:tint="@color/black"
            app:tintMode="src_in" />

        <ImageButton
            android:id="@+id/exo_play"
            style="@style/ExoMediaButton.Play"
            app:tint="@color/black"
            app:tintMode="src_in" />

        <ImageButton
            android:id="@+id/exo_pause"
            style="@style/ExoMediaButton.Pause"
            app:tint="@color/black"
            app:tintMode="src_in" />

        <ImageButton
            android:id="@id/exo_next"
            style="@style/ExoMediaButton.Next"
            app:tint="@color/black"
            app:tintMode="src_in" />

        <ImageButton
            android:id="@id/exo_repeat_toggle"
            style="@style/ExoMediaButton"
            app:tint="@color/black"
            app:tintMode="src_in" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="4dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <TextView
            android:id="@id/exo_position"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:includeFontPadding="false"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:textColor="#ff323232"
            android:textSize="14sp"
            android:textStyle="bold" />

        <androidx.media3.ui.DefaultTimeBar
            android:id="@id/exo_progress"
            android:layout_width="0dp"
            android:layout_height="26dp"
            android:layout_weight="1"
            app:played_color="@color/teal_200"
            app:unplayed_color="@color/grey" />

        <TextView
            android:id="@id/exo_duration"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:includeFontPadding="false"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:textColor="#ff323232"
            android:textSize="14sp"
            android:textStyle="bold" />

    </LinearLayout>

</LinearLayout>
```

in initializeSessionAndPlayer() in  [DemoPlaybackService](https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/demos/session_service/src/main/java/androidx/media3/demo/session/DemoPlaybackService.kt#L103) 

add the following code

```
val forwardingPlayer : Player = object : ForwardingPlayer(player) {
            //https://github.com/google/ExoPlayer/issues/9971
            // Overrides to always enable COMMAND_SEEK_TO_NEXT
            override fun getAvailableCommands(): Player.Commands {
                return wrappedPlayer
                    .availableCommands
                    .buildUpon()
                    .add(COMMAND_SEEK_TO_NEXT)
                    .build()
            }

            override fun isCommandAvailable(command: @Player.Command Int): Boolean {
                return player.isCommandAvailable(command) || command == COMMAND_SEEK_TO_NEXT
            }

            // Override to implement your custom action when seeking.
            override fun seekToNext() {
                if (wrappedPlayer.hasNextMediaItem()) {
                    // Dispatch to the wrapped player if not at the final media item
                    wrappedPlayer.seekToNextMediaItem()
                }
                else {
                    wrappedPlayer.seekTo(0,
                        C.TIME_UNSET)

                }
            }
        }

        mediaLibrarySession =
            MediaLibrarySession.Builder(this, forwardingPlayer, createLibrarySessionCallback())
                .also { builder -> getSingleTopActivity()?.let { builder.setSessionActivity(it) } }
                .build()
```

in setController() in[ PlayerActivity](https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/demos/session/src/main/java/androidx/media3/demo/session/PlayerActivity.kt#L115) add the code 

```
playerControlView = findViewById(R.id.playerControlView)
playerControlView.player = controller
        playerControlView.showShuffleButton = true
        playerControlView.repeatToggleModes = Player.REPEAT_MODE_OFF
```
I have referred [this ](https://github.com/google/ExoPlayer/issues/9971)

here is a demo video

https://github.com/user-attachments/assets/18cbe248-8db1-43b0-9f22-7be6ef4ec2b8

### Expected result

The next button should work even for the Last MediaItem with forwardingplayer, in the playerview and playercontrolview like it does in the notification 

### Actual result

The next button does not work even for the Last MediaItem with forwardingplayer, in the playerview and playercontrolview like it does in the notification 

### Media

Jazz and Blues or any other album or list of mediaitems

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment] 2024-08-02 21:52
Hi @pawaom,

Thanks for reporting! I think the referred approach only works for player UI (https://github.com/google/ExoPlayer/issues/9971) and the legacy `MediaController` (notification), but don't work for the media3 `MediaController`.

For the player UI case, the `Player` set to the `PlayerControlView` is exactly your custom `ForwardingPlayer`. Then whether to enable the "next" button is determined by the [result of `Player.isCommandAvailable`](https://github.com/androidx/media/blob/release/libraries/ui/src/main/java/androidx/media3/ui/PlayerControlView.java#L1204), where your custom code will take effect. 

For the legacy controller case (media notification is using the legacy controller to control the session), the legacy `MediaController` doesn't have `isCommandAvailable` method (it doesn't implement the [`Player` interface](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L170)) and system UI doesn't use the `PlayerControlView` in our library. Also legacy controller doesn't check if the command is available upon the corresponding method call at its side (eg. skipToNext), then whether this method call can actually go through [directly depends on the call to the player in the session](https://source.corp.google.com/piper///depot/google3/third_party/java_src/android_libs/media/libraries/session/src/main/java/androidx/media3/session/MediaSessionLegacyStub.java;l=445?q=mediasessionle), thus your custom code can take effect either.

However, for media3 `MediaController`, it implements [`Player` interface](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L172). If you set the controller as the player in the `PlayerControlView`, it will call `Player.isCommandAvailable` to determine whether to enable the "next" button as well, however, this call will firstly flow through the `MediaController`'s [implementation](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L1964). Taking look at it's implementation, it checks with a maintained property [`intersectedPlayerCommands`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplBase.java#L1959). It is a intersection of the available player commands set on the session and from the player, which means that if one of them doesn't contain the `Command.SEEK_TO_NEXT`, then it will be unavailable. Then why the `SEEK_TO_NEXT` becomes unavailable? In fact, when the underlying `ExoPlayer` plays the last item, the `SEEK_TO_NEXT` becomes unavailable at the `ExoPlayer` side, then it will send an event [`onAvailableCommandsChanged`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L892) to its listener, then `ForwardingPlayer` receives it and [further forwards](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/ForwardingPlayer.java#L990) this event with a new `availableCommands` (no `SEEK_TO_NEXT`) to the session and then controller. This process doesn't consider your custom implementation in `ForwardingPlayer.isCommandAvailable`, thus, the controller will finally get a updated `intersectedPlayerCommands` without `SEEK_TO_NEXT`.

I'll discuss internally to see if we already have some approach somewhere to workaround this problem or we need to add one. Will update this issue next week.

**Comment by tianyif** [comment] 2024-08-05 16:18
Hi @pawaom,

I spoke with the team today, and it seems that we already had [the similar issue](https://github.com/androidx/media/issues/1183) reported before, which caused by the inconsistency in the custom `ForwardingPlayer`.

In fact, we have a `ForwardingSimpleBasePlayer` that addresses this issue. It allows you to wrap your underlying `Player` and [override the `state`](https://github.com/androidx/media/blob/main/libraries/common/src/main/java/androidx/media3/common/ForwardingSimpleBasePlayer.java#L41) that should be forwarded to another player, including the available commands that you hope to declare aside from those coming from the underlying player. However, this class hasn't been included in the latest release, so you may want to copy this class and manually add it into your code base and extend it until it is officially released.

If your problem is just about letting the next button show for the last item and the player play the first item, then you can probably [set the repeat mode](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L2521) to `REPEAT_MODE_ALL`, without bothering to copy the above unreleased code.

Hope the above can help!

**Comment by pawaom** [comment] 2024-08-06 04:21
I know about the `REPEAT_MODE_ALL`  however that is not what we require.

I copied the `ForwardingSimpleBasePlayer `  how ever it gives me the following error `Expected 1 arguments but found 3` [here](https://github.com/androidx/media/blob/a23f655cf4a4fbc88b086de7d0ef7a57bad2b576/libraries/common/src/main/java/androidx/media3/common/ForwardingSimpleBasePlayer.java#L179)







![image](https://github.com/user-attachments/assets/0a8e3933-fc08-46ab-a333-c395ad3fef68)

**Comment by tonihei** [comment] 2024-08-06 08:20
@pawaom  This is because there were some additional changes to the `SimpleBasePlayer` super class to make this possible. If you keep a temporary fork of `ForwardingSimpleBasePlayer` until the class is officially released in 1.5.0, you will also need to keep a forked version of [`SimpleBasePlayer`](https://github.com/androidx/media/blob/main/libraries/common/src/main/java/androidx/media3/common/SimpleBasePlayer.java) I'm afraid.

**Comment by icbaker** [comment] 2024-08-06 13:18
`1.5.0-alpha01` is planned for the first half of September.

**Closed** 2024-08-09 14:29 UTC
Labels: duplicate, question
