### ISSUE TITLE
Application using the library will crash if 1000 DownloadHelper instances are created with a non-null RenderersFactory

### ISSUE THREAD

**Issue by retiredreplicant** [androidx/media#1224] opened 2024-03-26 18:24 UTC
### Version

Media3 1.3.0

### More version details

d13a0f4ec62ca092b79746a5725b62a3244cc5b4

### Devices that reproduce the issue

All devices

### Devices that do not reproduce the issue

No devices excluded

### Reproducible in the demo app?

No

### Reproduction steps

1. Create a player application that can create and release 1000 DownloadHelper instances with a non-null RenderersFactory (or modify the demo app to do so.)
2. Create and release 1000 DownloadHelper instances with a non-null RenderersFactory 

### Expected result

An application using the player should be able to create an unlimited number of DownloadHelper instances with a non-null RenderersFactory.

### Actual result

The application will crash with a "Too many receivers, total of 1000, registered for pid" exception.

**Source of Issue**
The source of the issue is that the DownloadHelper uses the passed RenderersFactory to create renderers, and to get capabilities for those renderers, but never releases the renderers that are created. One of the renderers created is a MediaCodecAudioRenderer. That renderer is created with a DefaultAudioSink. When the DownloadHelper processes a DOWNLOAD_HELPER_CALLBACK_MESSAGE_PREPARED message, the DownloadHelper calls runTrackSelection and this results in the DefaultAudioSink creating an instance of AudioCapabilitiesReceiver and registering that receiver. The release() method for the DefaultAudioSink unregisters that listener, but since the DownloadHelper does not call release() on the renderers it creates, release is never called on the DefaultAudioSink and the unregister never occurs.  If 1000 DownloadHelpers are created with a non-null RenderersFactory, the application will crash with a "Too many receivers, total of 1000, registered for pid" exception. 

**Reproduction with Demo App**
Not reproducible with the demo app only because there are not 1000 items to download.  However, the registration of a AudioCapabilitiesReceiver for each download without a corresponding unregister can be seen with the demo app.  Set breakpoints at lines 1520 `audioCapabilitiesReceived.unregister();` and 1749 `audioCapabilities = audioCapabilitiesReceiver.register();` in DefaultAudioSink and initiated a download with the demo app.  You will hit the breakpoint at 1749 (register) for each download, but the breakpoint at 1520 (unregister) is never hit.  This demonstrates receivers being registered but never unregistered.  Note that the player **_does_** properly release the renderers that it creates.  It is only the DownloadHelper that does not. 

**Recommend Change**
The DownloadHelper needs to keep a handle to the renderers it creates much in the same way it keeps a handle on the RendererCapabilities that it obtains.  When DownloadHelper.release() is called, the class needs to iterate through the renderers that it has created and call the release method for each.  This will result the MediaCodecAudioRenderer being released, which will in turn result in the the DefaultAudioSink being released and the AudioCapabilitiesReceiver being unregistered. 

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2024-03-27 15:02
> 2\. Create and release 1000 DownloadHelper instances with a non-null RenderersFactory

I tried to repro this by adding a `for (int i = 0; i < 1001; i++)` loop around this code: https://github.com/androidx/media/blob/66547cc331f4aa465848ae3e290ad32d655634c7/demos/main/src/main/java/androidx/media3/demo/main/DownloadTracker.java#L120-L128

This should result in creating, preparing, then releasing 1001 `DownloadHelper` instances. 

I then launched the application and downloaded the `Misc > Dizzy (MP4)` asset.

The application didn't crash. I also added `checkNotNull` to ensure that `renderersFactory` is non-null.

----

I then tried waiting for `DownloadHelper.Callback.onPrepared` before releasing and re-creating, by adding the following code here: https://github.com/androidx/media/blob/66547cc331f4aa465848ae3e290ad32d655634c7/demos/main/src/main/java/androidx/media3/demo/main/DownloadTracker.java#L196

```
if (prepareCount.getAndIncrement() < 2001) {
  downloadHelper.release();
  downloadHelper =
      DownloadHelper.forMediaItem(context, mediaItem, renderersFactory, dataSourceFactory);
  downloadHelper.prepare(this);
}
```

The application still didn't crash.

----

Please can you provide some more precise repro steps, ideally as a fork of the demo app that we can clone.

**Comment by retiredreplicant** [comment] 2024-03-27 16:02
I will work on modifying the demo app to reproduce. In attempting to reproduce the issue with my application, sometimes it is the player that hits the 1000 receiver limit and the application does not crash in that case.  There is just a player error. 

Since both the the player and the DownloadHelper register an AudioCapabilitiesReceiver, it is a 50/50 chance which will run into the 1000 receiver limit first. But, it is the DownloadHelper that is registering receivers and not releasing them. The player always unregisters the listeners that in registers. The dumpstate is too big to attach here or email.  I have attached the stack trace for the case where the application crashes.

[stack_trace.txt](https://github.com/androidx/media/files/14775924/stack_trace.txt)

**Comment by retiredreplicant** [comment] 2024-03-27 17:06
For you reproduction attempts, you definitely need to prepare the media.  Also, the media selected has to be something that results in DownloadHelper.onMediaPrepared() calling runTrackSelection.  That is when the AudioCapabilitiesReceiver is registered. 
![Screenshot (81)](https://github.com/androidx/media/assets/12139534/f2586bee-965a-4626-b41a-b1f71cb2de98)

**Comment by icbaker** [comment] 2024-03-27 17:41
> Also, the media selected has to be something that results in DownloadHelper.onMediaPrepared() calling runTrackSelection.

Thanks, this was the clue I was missing. Switching to using the `Clear DASH -> HD (MP4, H264)` sample, and then fixing a bug in my second repro case above (adding missing `return` at the bottom of the `if`) I'm able to reproduce.

**Comment by sahilgarg90** [comment] 2024-03-28 13:47
@retiredreplicant @icbaker 
I was facing the same issue and the following pull request changes worked for me.

https://github.com/androidx/media/pull/1230

**Comment by icbaker** [comment] 2024-03-28 15:27
This is fixed by the commit referenced above.

**Comment by sahilpocketfm** [comment] 2024-03-29 09:08
When can we expect this to be included in final release?

**Comment by icbaker** [comment] 2024-04-02 12:32
The fix will be included in the 1.4.0 release.

**Comment by icbaker** [comment] 2024-04-08 07:19
Unfortunately https://github.com/androidx/media/commit/c5e894e2d63aae9d0014e01fff99b34cd5ba3ec5 was rolled back in https://github.com/androidx/media/commit/c2356e398976f8a975f58acc1e8a76d93f336afd due to causing crashes when integrated with a google app which calls `DownloadHelper.forMediaItem` from a non-looper thread. Re-opening this issue while we look into resolving this and rolling the fix back forward.

**Comment by sahilpocketfm** [comment] 2024-04-08 11:22
@icbaker Since above mentioned commit is rolled back, can we consider this PR now? This worked in our case

https://github.com/androidx/media/pull/1230

**Comment by icbaker** [comment] 2024-04-08 16:39
The fix has been resubmitted with a fix & related tests: https://github.com/androidx/media/commit/fad325707254ecddb92a2c2d8c0274e852836966

**Closed by icbaker** 2024-04-08 16:39 UTC
Labels: bug, needs triage
