### ISSUE TITLE
MediaButtonReceiver and KEYCODE_HEADSETHOOK

### ISSUE THREAD

**Issue by DavidEdwardsBL** [androidx/media#1581] opened 2024-08-01 07:03 UTC
### Version

Media3 main branch

### Devices that reproduce the issue

SDK_INT >= 26

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Run a media app
2. Play some content
3. Pause it
4. Swipe the app away from recents
5. Make a headset hook event `adb shell input keyevent 79`

### Expected result

The App should behave as if a play event was received.

### Actual result

The App delivers 

> Ignore key event that is not a `play` command on API 26 or above to avoid an 'ForegroundServiceDidNotStartInTimeException'

Related issue: https://github.com/androidx/media/issues/1493

The headset hook key event is not taken into account when only allowing a play command through the MediaButtonReceiver. 

### Media

n/a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by DavidEdwardsBL** [comment] 2024-08-01 07:04
@icbaker I was going to post in the previous issue, but thought this is perhaps unique enough for a new issue.

**Comment by icbaker** [comment] 2024-08-05 08:15
Would you be able to clarify if this is a change/regression **introduced** in 1.4.0 (i.e. not present in 1.3.1, and maybe caused by https://github.com/androidx/media/commit/c64dacf3df9097dc2c4535674a31dac4f568d344), or a longstanding inconsistency where we are not handling `HEADSETHOOK` the same way as `PLAY`?

**Comment by DavidEdwardsBL** [comment] 2024-08-05 09:35
The code in question is quite old:

https://github.com/androidx/media/blame/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/session/src/main/java/androidx/media3/session/MediaButtonReceiver.java#L133

This part exists over a year, so it is not a problem introduced in 1.4.0.

The issue is here:

```
      if (keyEvent != null
          && keyEvent.getKeyCode() != KeyEvent.KEYCODE_MEDIA_PLAY
          && keyEvent.getKeyCode() != KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE) {
```

Whereby `KEYCODE_MEDIA_PLAY` and `KEYCODE_MEDIA_PLAY_PAUSE` are detected, but not the `KEYCODE_HEADSETHOOK`.

**Comment by icbaker** [comment] 2024-08-13 15:19
Thanks for the extra info - this should be resolved by the commit linked above.

**Closed by icbaker** 2024-08-13 15:19 UTC
Labels: bug, needs triage
