### ISSUE TITLE
Exoplayer got stuck in STATE_BUFFERING while playing some video content on Ugoos X4 Pro device

### ISSUE THREAD

**Issue by gags-lover** [androidx/media#560] opened 2023-08-04 09:14 UTC
### Version

ExoPlayer 2.16.1

### Devices that reproduce the issue

* Ugoos X4 Pro running Android 11

### Devices that do not reproduce the issue

* Ugoos X3 Cube
* HAIER 32 SMART TV S1
* almost every other device tested, including Android Emulator

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Make 2 original video (send to android-media-github@google.com) play one after another using ConcatenatingMediaSource on Ugoos X4 Pro

### Expected result

Original videos play one after another successfully

### Actual result

After the first video ends player gets stuck in STATE_BUFFERING and stays like that forever. At the screen i can see last frame of the first video.
I fixed the bug by processing these 2 original videos with ffmpeg, and after that everything plays fine. But processing all videos before playing is not an option, our app needs to be able to play raw videos without any issue. 
I assume that it may be caused by device specificity, because i could only get the bug at Ugoos X4 Pro (even the previous model Ugoos X3 works well)
So i hope you'd help me to get to know what the problem is.

Logs are attached. It contains system logs and our app's exoplayer adapter logs as well. In the "bug" logs it stucks at the line with time 2023-08-04 10:51:16.787. 
[video stucks, original videos.txt](https://github.com/androidx/media/files/12258847/video.stucks.original.videos.txt)
[plays successfully, rendered video.txt](https://github.com/androidx/media/files/12258849/plays.successfully.rendered.video.txt)

### Media

Send original and processed videos to [android-media-github@google.com](mailto:android-media-github@google.com). first_original.mp4 and second_original.mp4 are the original videos, first_processed.mp4 and second_processed.mp4 are the files after processing it with ffmpeg

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.
P.S. bugreport's time is written with UTC0, but logs attached - UTC+3

**Comment by tonihei** [comment] 2023-08-09 12:10
Thanks for sharing all the information. If the problem only reproduces with the combination of these media files and this device, then it's likely that the media bytes and the decoder do not work well together. It could be an issue with the media itself or the decoder, but because it plays fine on all other devices, I assume it's more of a decoder issue.

Unfortunately, the logs you shared don't contain any obvious error and problematic output that is useful for debugging. What you could try to debug this further is:
 - Share a new bugreport with the latest ExoPlayer version (2.19.0) and an [`EventLogger` attached](https://developer.android.com/guide/topics/media/exoplayer/listening-to-player-events#using_eventlogger).  This ensures we definitely test the latest code and see all the events related to decoder usage. 
- Test out existing workarounds for codec issues. This requires to build from source, but you can try to enable the various workarounds starting from [this line](https://github.com/google/ExoPlayer/blob/f42566558294c91f0c1425299b3f4e322767d90c/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L2388) (all the methods named `codecNeeds...Workaround`). If one of these workarounds help, we can see if it makes sense to add this device/decoder to the list.

**Comment by tonihei** [comment] 2023-08-09 17:26
The `EventLogger` details show that the codec never produces a new frame after the stream transition, which block the playback. I'd still suggest to try out the existing workarounds we have to see if they help on this device.

**Comment by astat1cc** [comment] 2023-08-10 09:06
Tried following workarounds one by one but none of them helped:
- codecNeedsFlushWorkaround
- codecNeedsDiscardToSpsWorkaround
- codecNeedsSosFlushWorkaround
- codecNeedsEosPropagationWorkaround
- codecNeedsEosFlushWorkaround
- codecNeedsEosBufferTimestampWorkaround
- codecNeedsEosOutputExceptionWorkaround
- codecNeedsMonoChannelCountWorkaround

**Comment by tonihei** [comment] 2023-08-10 12:20
Thanks for checking. Unfortunately this means I can't really debug this further at the moment. If you have any means of doing so, please try to get in touch with the device manufacturer with the debugging steps and highlight that the problem is that the codec stops outputting samples for your media file. Will leave this bug open regardless in case we find a way to debug this further.

**Comment by tonihei** [comment] 2024-06-24 08:13
Closing due to lack of further actionable info. Feel free to reopen or file a new one if you have further information we can use to workaround these issues.

**Closed by tonihei** 2024-06-24 08:13 UTC
Labels: bug: device specific
