### ISSUE TITLE
Fatal Exception: android.view.InflateException Binary XML file line #64 in com.my.app:layout/exo_player_control_view: Binary XML file line #64 in com.my.app:layout/exo_player_control_view: Error inflating class ImageButton

### ISSUE THREAD

**Issue by anonym24** [androidx/media#1217] opened 2024-03-23 18:08 UTC
### Version

Media3 1.2.1

### More version details

Noticed crashes at Firebase Crashlytics with `android.content.res.Resources$NotFoundException` when using `PlayerControlView`
```
Caused by android.content.res.Resources$NotFoundException
Unable to find resource ID #0x7f080092
android.content.res.ResourcesImpl.getResourceName (ResourcesImpl.java:281)
android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:949)
android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:724)
android.content.res.Resources.loadDrawable (Resources.java:1072)
android.content.res.TypedArray.getDrawableForDensity (TypedArray.java:1017)
android.content.res.TypedArray.getDrawable (TypedArray.java:991)
android.widget.ImageView.<init> (ImageView.java:205)
android.widget.ImageButton.<init> (ImageButton.java:96)
android.widget.ImageButton.<init> (ImageButton.java:92)
androidx.appcompat.widget.AppCompatImageButton.<init> (AppCompatImageButton.java:1)
androidx.appcompat.widget.AppCompatImageButton.<init> (AppCompatImageButton.java:18)
androidx.appcompat.app.AppCompatViewInflater.createImageButton (AppCompatViewInflater.java:18)
androidx.appcompat.app.AppCompatViewInflater.createView (AppCompatViewInflater.java:18)
androidx.appcompat.app.AppCompatDelegateImpl.createView (AppCompatDelegateImpl.java:18)
androidx.appcompat.app.AppCompatDelegateImpl.onCreateView (AppCompatDelegateImpl.java:18)
android.view.LayoutInflater.tryCreateView (LayoutInflater.java:1083)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:1019)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:983)
android.view.LayoutInflater.rInflate (LayoutInflater.java:1145)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:1106)
android.view.LayoutInflater.rInflate (LayoutInflater.java:1148)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:1106)
android.view.LayoutInflater.rInflate (LayoutInflater.java:1148)
android.view.LayoutInflater.inflate (LayoutInflater.java:666)
android.view.LayoutInflater.inflate (LayoutInflater.java:544)
android.view.LayoutInflater.inflate (LayoutInflater.java:491)
androidx.media3.ui.PlayerControlView.<init> (PlayerControlView.java:30)
androidx.media3.ui.PlayerView.<init> (PlayerView.java:300)
androidx.media3.ui.PlayerView.<init> (PlayerView.java:300)
androidx.media3.ui.PlayerView.<init> (PlayerView.java:300)
com.my.app.PlayerScreenKt$PlayerContent$2$1$1.invoke (PlayerScreen.kt:10)
com.my.app.PlayerScreenKt$PlayerContent$2$1$1.invoke (PlayerScreen.kt:10)
androidx.compose.ui.viewinterop.ViewFactoryHolder.<init> (AndroidView.android.kt:1)
androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke (AndroidView_android.kt:43)
androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke (AndroidView_android.kt:43)
androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke (AndroidView_android.kt:128)
androidx.compose.runtime.changelist.Operation$InsertNodeFixup.a (Operation.kt:8)
androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations (Operations.kt:23)
androidx.compose.runtime.changelist.FixupList.executeAndFlushAllPendingFixups (FixupList.java:36)
androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute (Operation.kt:36)
androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations (Operations.kt:23)
androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges (ChangeList.kt:1)
androidx.compose.runtime.CompositionImpl.applyChangesInLocked (Composition.kt:50)
androidx.compose.runtime.CompositionImpl.i (Composition.kt:6)
androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:186)
androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:186)
androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame (AndroidUiFrameClock.android.kt:1)
androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch (AndroidUiDispatcher.java:48)
androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch (AndroidUiDispatcher.java:48)
androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:48)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1299)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1309)
android.view.Choreographer.doCallbacks (Choreographer.java:923)
android.view.Choreographer.doFrame (Choreographer.java:847)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1283)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8762)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

in my PlayerContent (Composable function):

			if (mediaController != null) {
                AndroidView(
                    modifier = Modifier
                        .fillMaxSize(),
                    factory = { context ->
                        PlayerView(context).also {
                            it.controllerHideOnTouch = false
                            it.controllerAutoShow = true
                            it.controllerShowTimeoutMs = 0
                            it.setShowRewindButton(true)
                            it.setShowFastForwardButton(true)
                            it.showController()
                        }
                    },
                    update = {
                        it.keepScreenOn = keepScreen
                        it.player = mediaController
                    }
                )
            }
			
PlaybackService:
			
	override fun onCreate() {
        super.onCreate()
        val context = this

        player = ExoPlayer.Builder(context)
            .setSeekBackIncrementMs(15_000L)
            .setSeekForwardIncrementMs(15_000L)
            .setMediaSourceFactory(
                DefaultMediaSourceFactory(
                    /* context = */ context,
                    /* extractorsFactory = */ DefaultExtractorsFactory().apply {
                        setConstantBitrateSeekingEnabled(true)
                    }
                )
            )
            .build()

        player.pauseAtEndOfMediaItems = true
        mediaSession = MediaSession.Builder(this, player).build()
    }

### Devices that reproduce the issue

Galaxy A23 (Android 13)
Galaxy Tab A9+ 5G (Android 13)

### Reproducible in the demo app?

I don't know

### Reproduction steps

using ExoPlayer View

### Expected result

ImageButtons doesn't inflate (crashes)

### Actual result

ImageButtons inflates without crash

**Comment by icbaker** [comment] 2024-03-25 16:33
Duplicate of https://github.com/google/ExoPlayer/issues/10409

**Closed by icbaker** 2024-03-25 16:33 UTC
Labels: bug, needs triage

**Comment by anonym24** [comment] 2024-03-28 12:19
> Duplicate of [google/ExoPlayer#10409](https://github.com/google/ExoPlayer/issues/10409)

it still can be fixed from exo part - keep only vector drawable at `/res/drawable` folder and remove all other images (png) in `drawable-*`, simple, this way the drawable vector will be available on all devices even if it's related to sideloading apk
