### ISSUE TITLE
Please support rtsp live stream

### ISSUE THREAD

**Issue by chuwza** [androidx/media#1452] opened 2024-06-13 00:00 UTC
There's already some same requests here.
https://github.com/androidx/media/issues/1426
https://github.com/google/ExoPlayer/issues/9400

Here's the same problem!

Sparkle TV is an IPTV Application that uses AndroidX Media as the built-in player. Similar to tivimate. (https://play.google.com/store/apps/details?id=se.hedekonsult.sparkle&hl=en_US)

Because Sparkle TV on Android TV uses AndroidX Media, which makes it impossible to play (rtsp://[2409:8087:2001:20:2800:0:df6e:eb18]:554/ott.mobaibox.com/000000400000001/H265_8000k_1080P_cctv1_CR) from (https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u)
![屏幕截图(421)](https://github.com/androidx/media/assets/30049891/3b191e53-9fa4-4de8-b6e7-a44ca556526e)

**Comment by microkatz** [comment] 2024-10-31 11:45
Closing as duplicate of https://github.com/androidx/media/issues/1426

**Closed by microkatz** 2024-10-31 11:45 UTC
Labels: duplicate, enhancement, needs triage
