### ISSUE TITLE
video in playing , how to get playerView shotScreen.

### ISSUE THREAD

**Issue by 309152665** [androidx/media#534] opened 2023-07-20 03:30 UTC
how to get a bitmap in video current frame?

**Comment by icbaker** [comment] 2023-07-20 14:16
https://github.com/google/ExoPlayer/issues/8975 and https://github.com/google/ExoPlayer/issues/5076 detail various ways to get the current frame as a bitmap.

There's no direct support for this in `PlayerView`, and we don't plan to add it - so closing this as a duplicate of the above two issues.

**Closed by icbaker** 2023-07-20 14:16 UTC
Labels: enhancement, needs triage
