### ISSUE TITLE
16kb page size support for native extensions (ffmpeg, opus, etc.)

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1805] opened 2024-10-15 02:24 UTC
### [REQUIRED] Use case description
[Android 15](https://developer.android.com/guide/practices/page-sizes#build) introduced new 16kb page size support, which could be a pretty big performance improvement, especially for native audio decoding. I want to make sure my app supports it, but I'm unsure if the native ffmpeg extension I use supports it.

### Proposed solution
Make the required patches to support 16kb page sizes for the ffmpeg, flac, opus, and other native extensions.

### Alternatives considered
I can port this myself, albeit it seems very risky since it probably requires some level of ffmpeg build configuration.

**Comment by Tolriq** [comment] 2024-10-15 10:28
https://github.com/androidx/media/commit/2640ebd58ff2c35dc2ad384c9db6fbe68ab05587

**Comment by rohitjoins** [comment] 2024-10-15 10:31
Hi @OxygenCobalt, we have recently added 16 KB page size support on Android 15 in https://github.com/androidx/media/commit/2640ebd58ff2c35dc2ad384c9db6fbe68ab05587.

Closing as duplicate of https://github.com/androidx/media/issues/1685.

**Closed by rohitjoins** 2024-10-15 10:31 UTC
Labels: duplicate, enhancement
