### ISSUE TITLE
Feature request: disable automatic foreground service management

### ISSUE THREAD

**Issue by mopfattn** [androidx/media#45] opened 2022-02-23 08:52 UTC
### Use case description
We would like to disable the automatic foreground service management of the `MediaSessionService` or at least get a callback wenn the foreground service is stopped to be able to keep the service alive for a longer time. Unfortunately the `Service.stopForeground` method is final and we can't override it.

### Proposed solution
Provide an option whether handling the foreground service should be done by the `MediaSessionService` or whether it's handled by the implementation of that service itself.

### Alternatives considered
Provide a callback or a `startForeground`/`stopForeground` method that can be overridden.

**Comment by marcbaechinger** [comment] 2022-02-23 18:07
Thanks for your request. 

Currently the service is started (instantiated and `onCreate`) when an app builds a controller and binds to the service. As long as the controller is not released, the service is in a bound state and will never be stopped by the system. When the controller is released, the services looses the bound state and it continues in the foreground when the player is still playing (playWhenReady=true). If not playing it continues in the background. This is due to the restrictions for background services since [O (API 26)](https://developer.android.com/about/versions/oreo/android-8.0-changes) or [S (API 31)](https://developer.android.com/guide/components/foreground-services#background-start-restrictions)

Base on this I believe there are not many options besides the current behaviour or you risk that the service is crashed by the system.

Can you elaborate a bit on your use case and in which condition you want to leave the service started in the foreground that is currently not possible? I would like to understand the conditions a bit better you are in and in which you want to continue in foreground.

Besides this I think you would be able to override `onTaskRemoved()` of your service that is called when your controller unbinds. At this point you could call `startForeground(id, notification)` but I think you can run into problems with the restrictions described above if you do so.

**Comment by mopfattn** [comment] 2022-02-24 04:08
Our goal is to build a more or less fully customized Android UI providing various apps. One of the apps is our music player which can then be controlled by other apps using the `MediaSession`/`MediaController`. The current issue is the stopped `MediaSessionService` (which is normally destroyed around a minute after `stopForeground`is called) which also removes the `MediaSession`, therefore we would have to restart the service in order to be able to restart the media player again.

Unfortunately `onTaskRemoved` is not called, even if we set `android:stopWithTask="false"`.

Our current workaround simply calls `startForeground` again after the player is stopped. This works, but it's not a very nice solution.

A better workaround would probably be to restart the service from other apps by using an appropriate Intent to resume the music playback.

**Comment by marcbaechinger** [comment] 2022-02-24 12:48
Thanks for your explanation. It's valuable for us to hear what developers try to achieve and make us think about what is the best solution. Thank you for getting into that conversation with us. This is helpful!

As for your case, I think you should not start the service with an intent, but instead bind to the service from another app. Looks like you are already doing that. If not, I think that would probably solve your problem because the service is kept alive as long as you have an app in foreground that binds to it. When using a service from another app [the recommended way is to bind to it](https://developer.android.com/guide/components/services). If Android thinks that your service should be stopped since it has been started, it's hard to make it think otherwise - it may simple crash the app.

> A better workaround would probably be to restart the service from other app by using an appropriate Intent to resume the music playback.

I don't think the intent approach is preferable over binding.

When you build a controller with Media3 you automatically (start and ) bind to the service. You also get the media controller API that allows you to control the player by using the media controller. That provides you with a better API than compared to sending intents. 

> Our current workaround simply calls startForeground again after the player is stopped. This works, but it's not a very nice solution.

This only works when the call to `startForeground` is initiated from the foreground I think. In this case binding would help in the same way. If you call 'startForeground` from the background on S/T your service crashes. 

This is a consequence of Android stopping your service more and more aggressively (starting with O) for reasons of system health. If you are looking for a 'nice solution' that keeps shutting down the service to a minimum, then binding is the what you should look into. Keeping the service alive 'manually' by sending `PendingIntent`s doesn't sound right to me and I would stay away from it because it won't get easier with that approach as you are fighting against the system policies with this. 

When no app that is in foreground is bound to the service Android may think it's best to shut down the service and it hard to convince it not to do so I think. 

> which is normally destroyed around a minute after `stopForeground` is called

When the `playWhenReady` is false and the user hasn't resumed playback within a minute, this is working as intended I think. Imaging I'm having 5 media apps like yours that decide to keep the service in the foreground until further notice when the player is paused. Each app has a player with codecs initialized and each app has decided to to run it until the user actively stops it.

Aside: If you tried T with your app, you may have noticed that the notification (SystemUI) is solely using the media controller from the notification on T (not using pending intents anymore like on S). The reason for this is what we are discussing here - to not use a service when an app is not in the foreground.

**Comment by mopfattn** [comment] 2022-02-25 07:39
Thank's for the explanations. Then we will simply bind our service to prevent it from being destroyed by the system.

**Comment by marcbaechinger** [comment] 2022-03-01 20:07
I'm closing this issue. Please re-open or create a new issue when something comes up. Thanks again!

**Closed by marcbaechinger** 2022-03-01 20:07 UTC
Labels: enhancement, need more info

**Comment by y20k** [comment] 2022-08-01 14:05
Hi and greetings, @marcbaechinger 

I just wanted to chime in: The automatic foreground handling in media3 in combination with the aggressive idle service killing of the OS causes some problems in real world usage of audio apps. Let me give an example:

Protagonist: Podcast listener with in-ear headphones

1. user starts listening to a podcast on the way to the office
2. user stops in front of a bakery, pauses playback via headphone button
3. user buys a croissant, leaves the bakery
4. user resumes playback via headphone button
5. user is happy and continues to the office

Note: Step 4 will only work if the user is the only customer in the bakery. (This is actually a real world example with me being the podcast listener on my way to work 😄 five day a week): If the interaction in the bakery lasts more than a minute or two, than the user taps his headphone without any effect. The playback service has been killed. In this case step 5 would be: user is confused / unhappy.

In the past my solution was: I only called `stopForeground` when the user pressed STOP. As long as the user only hit PAUSE I left the app running.

I am now wondering: Is [Playback Resumption](stopForeground) the way to go here?

**Comment by christosts** [comment] 2022-08-10 15:57
Maybe try building the player with a custom `DefaultLoadControl` whose `shouldContinueLoading()` returns false when you pause the player.

I have not tested this but it might work.
