### ISSUE TITLE
How to stop the service and remove the notification when connected with MediaController?

### ISSUE THREAD

**Issue by Waldmann375** [androidx/media#73] opened 2022-05-07 07:27 UTC
I mean, release the MediaSession, stop the MediaSessionService and remove the notification.

The problem is that just calling stopService(intent) and releasing the MediaController from the activity does not work. I suspect it's because the service keeps being used by the MediaSession.

I know that I should release the mediasession, but the mediasession belongs to the sevice, which I can't control from Activity. 
I can't even get into the service's onDestroy callback to release the mediasession.

So my current workaround is to release the MediaController in activity's onDestroy(), so the process stops by a fatal crash: 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException: Attempt to invoke interface method 'void androidx.media3.session.IMediaSession.flushCommandQueue(androidx.media3.session.IMediaController)' on a null object reference
        at androidx.media3.session.MediaControllerImplBase$FlushCommandQueueHandler.handleMessage(MediaControllerImplBase.java:3041)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:255)
        at android.app.ActivityThread.main(ActivityThread.java:8212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

It does the job, but I believe there should be a better way for such a simple task.

**Comment by marcbaechinger** [comment] 2022-05-07 21:33
As long as you are bound to the service with a connected controller in your activity, you can't easily stop the service.

If you for some reason want to stop the service from the activity, I think it should work if you first release the controller and then stop the service in `MediaController.Listener.onDisconnected(MediaController)` (of the last controller disconnecting). You can set a listener when you build the controller with the `Builder`.

Because the service can only be stopped when no controller is bound to it, I think you can always stop the service on the service side when you call

```
mediaSession.release();
stopSelf();
```

This disconnects (unbinds) all controllers and then stops the service.

If I understand your requirement correctly, overriding `onTaskRemoved` of your service, releasing the player there and calling the two lines above would probably just do what you want. Looking into the [JavaDoc of `onTaskRemoved()`](https://developer.android.com/reference/android/app/Service#onTaskRemoved(android.content.Intent)) is worth it, as it can free you from registering the media controller listener and do book-keeping (with multiple controllers) in the activity as explained above.

The stack trace above is a bug that I think is actually unrelated. I filled #74 for this, so we can keep this as a question for future readers. Thanks for reporting!

**Comment by Waldmann375** [comment] 2022-05-08 15:03
Thank you for your answer, **marcbaechinger**

I did what you said regarding `onTaskRemoved `, and I've got following behavior: If the player was playing when I remove the app task from the recents, the notification vanish along with activity, but(!) the playback doesn't stop. The app has no single sign of being run, but the song was still playing. I fixed it by adding the line `mediaSession.player.stop()` before `mediaSession.release()` and then it went ok.

But this solution only covers the case when a user swipes the app from the recents. Is there a way to somehow send a signal from activity to a service (by a button click for example)? One usually does it by `IBinder`, but the `MediaSessionService ` class already has it's own `Binder`, so if I override onBind(), it will breake everything else.

All I am trying to achieve is to ensure that if user wants to remove the notification and stop the player, he does it easily.

**Comment by marcbaechinger** [comment] 2022-05-09 10:05
You need to release the player in any case. It's documented in the class level JavaDoc of `MediaSession` that an app still needs to call `mediaSession.player.release` when the session is released. However, this should be documented on the `release()` method as well I think, so I marked this issue as a documentation candidate also.

But it still sounds odd that it keeps playing. I would assume you do release the player in `onDestroy`, because your app definitely needs to care about releasing the player as normally in any scenario. So I would expect you have this in `onDestroy` and `onDestroy` should be called when you call `stopSelf` if it works as expected. So I would investigate whether `onDestroy` is actually called accordingly after you did what you describe above. If it is called the you should release the player there, if it's not called you need to investigate why.

**Comment by marcbaechinger** [comment] 2022-05-27 22:04
The stack trace from the initial post was caused by #74 and is fixed.

The question of this issues looks like answered to me with the post above,  so I close this issue for now. Please re-open or open a new issue if you think something on the library side is wrong.

For future readers and further reading this [DAC article](https://developer.android.com/guide/components/bound-services#bind-started-service) about `bound and started services` may be of interest. `MediaLibraryService/MediaSessionService` both are _bound_ services (when a `MediaController` binds to the service) and _started_ services as well (when the service is started in the foreground in case of the activity being put into the background). A bound service can't be stopped. If an app wants to stop the service, the session needs to be released to disconnect all bound controllers and then the service be stopped with for instance `stopSelf()` that causes `onDestroy()` to be called where the app releases the remaining resources (like the player).

**Closed by marcbaechinger** 2022-05-27 22:04 UTC
Labels: question, documentation candidate
