### ISSUE TITLE
Provide example of MediaItem  as an image in Main Demo

### ISSUE THREAD

**Issue by omkarsurya** [androidx/media#1206] opened 2024-03-21 03:45 UTC
Provide example of MediaItem  as an image in Main Demo

I recently came across the `setImageDurationMs` 
 [here](https://developer.android.com/reference/androidx/media3/common/MediaItem.Builder#setImageDurationMs(long))

Which allows to create a mediaitem using an image after we set the URI as an image

the main exoplayer demo provides example for various video and audio formats but there is no example for image as mediaitem
 

Please provide example for various image formats and specify which image formats like jpg, png etc are supported

Also is webp supported?

**Comment by oceanjules** [comment] 2024-03-23 22:20
Look like a duplicate of https://github.com/androidx/media/issues/1157

**Comment by omkarsurya** [comment] 2024-03-24 03:46
the question is not about being able to display an image, I am asking  will there be a demo application for various image types, 
As there are already example provided for various video and audio files, similarly the demo application can have examples of image files .

**Comment by icbaker** [comment] 2024-03-25 09:44
The demo app uses `PlayerView` which doesn't currently support image output: https://github.com/androidx/media/issues/1144

When the demo app supports displaying images we can add some example image assets.

**Comment by pawaom** [comment] 2024-03-25 12:25
@icbaker  can this be included in other demos like  

[surface](https://github.com/androidx/media/tree/release/demos/surface)

or 

[gl](https://github.com/androidx/media/tree/release/demos/gl)

**Comment by AndreyMedal** [comment] 2024-10-09 21:22
Any ideas why compose demo doesn't work with images? I tried to add MediaSourceFactory, RenderersFactory and ImageDurationMs for MediaItem. But still I see only black screen for `SURFACE_TYPE_SURFACE_VIEW`. I think good example of usage images with compose will be useful.

**Comment by tonihei** [comment] 2024-10-10 08:39
Image support in the UI modules has been implemented in 1.4.0, there are also some example images in the demo app and we added documentation on the guide pages: https://developer.android.com/media/media3/exoplayer/images

So I think we can close this bug as done. 

@AndreyMedal the compose demo is work in progress and will eventually support images too.

**Closed by tonihei** 2024-10-10 08:39 UTC
Labels: enhancement, low priority
