### ISSUE TITLE
MediaLibraryService getting stopped due to app idle

### ISSUE THREAD

**Issue by XilinJia** [androidx/media#1715] opened 2024-09-09 21:25 UTC
My app implements `class PlaybackService : MediaLibraryService()`

Lately I noticed when a media is played (on Samsung S21 Android 14) and the screen is turned off, after a while the media stops playing. From Logcat, I have the message: 

> ActivityManager                     system_server                        W  Stopping service due to app idle: u0a708 -1m56s672ms 

It appears I need to set the app to Unrestricted (from Optimized) for battery to keep the media keep playing. I wonder what this means. Does it mean the service is not actually a foreground service?

Also, I notice the service is started automatically just after the app is started, without the need to call `ContextCompat.startForegroundService(context, intent)` (I'm not quite sure what starts service). Even if I force calling `ContextCompat.startForegroundService(context, intent)` when playing a media, the behavior stays the same.

This seems only happening on my Samsung phone.  Can anyone explain or advise what needs to be done correctly?

If anyone wants to test, my app is https://github.com/XilinJia/Podcini

**Comment by XilinJia** [comment] 2024-09-10 06:47
Got some more evidence.

Actually upon the first play (based upon the press of the play button), the services runs OK, never got stopped, no matter how long the play time. 

The issue arrives when the service is playing the next media in queue after finishing the first one.  This time there is no user interaction.  I see a Logcat error message:

```
07:25:35.978 19648-19648 MSessionService                     ac.mdiq.podcini.R.debug              E  Failed to start foreground
 android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ac.mdiq.podcini.R.debug/ac.mdiq.podcini.playback.service.PlaybackService
     at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
     at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
     at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
     at android.os.Parcel.readParcelable(Parcel.java:4864)
     at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
     at android.os.Parcel.createException(Parcel.java:3053)
     at android.os.Parcel.readException(Parcel.java:3036)
     at android.os.Parcel.readException(Parcel.java:2978)
     at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457)
     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002)
     at android.app.ContextImpl.startForegroundService(ContextImpl.java:1967)
     at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847)
     at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1128)
     at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:700)
     at androidx.media3.session.MediaNotificationManager.startForeground(MediaNotificationManager.java:366)
     at androidx.media3.session.MediaNotificationManager.updateNotificationInternal(MediaNotificationManager.java:223)
     at androidx.media3.session.MediaNotificationManager.lambda$updateNotification$6$androidx-media3-session-MediaNotificationManager(MediaNotificationManager.java:179)
     at androidx.media3.session.MediaNotificationManager$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
     at androidx.media3.common.util.Util.postOrRun(Util.java:794)
     at androidx.media3.session.MediaNotificationManager.lambda$new$0(MediaNotificationManager.java:81)
     at androidx.media3.session.MediaNotificationManager$$ExternalSyntheticLambda2.execute(D8$$SyntheticClass:0)
     at androidx.media3.session.MediaNotificationManager.lambda$updateNotification$7$androidx-media3-session-MediaNotificationManager(MediaNotificationManager.java:177)
     at androidx.media3.session.MediaNotificationManager$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
     at androidx.media3.common.util.Util.postOrRun(Util.java:794)
     at androidx.media3.session.MediaNotificationManager.updateNotification(MediaNotificationManager.java:171)
     at androidx.media3.session.MediaSessionService.onUpdateNotification(MediaSessionService.java:587)
     at androidx.media3.session.MediaSessionService.onUpdateNotificationInternal(MediaSessionService.java:623)
     at androidx.media3.session.MediaNotificationManager$MediaControllerListener.onEvents(MediaNotificationManager.java:358)
     at androidx.media3.session.MediaControllerImplBase.lambda$new$0$androidx-media3-session-MediaControllerImplBase(MediaControllerImplBase.java:164)
     at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda89.invoke(D8$$SyntheticClass:0)
     at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:350)
     at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:294)
     at androidx.media3.common.util.ListenerSet.$r8$lambda$rFcF5Pkb99AL585p5-2u78YfNkY(Unknown Source:0)
     at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(D8$$SyntheticClass:0)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loopOnce(Looper.java:230)
     at android.os.Looper.loop(Looper.java:319)
     at android.app.ActivityThread.main(ActivityThread.java:8919)
     at java.lang.reflect.Method.invoke(Native Method)
07:25:35.978 19648-19648 MSessionService                     ac.mdiq.podcini.R.debug              E        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
So not being a foreground service, it's getting stopped in a while when the app is in the background

**Comment by rohitjoins** [comment] 2024-09-12 01:07
Closing this issue as a duplicate of https://github.com/androidx/media/issues/111 to consolidate all activity in one place.

**Closed by rohitjoins** 2024-09-12 01:07 UTC
Labels: question, needs triage
