### ISSUE TITLE
`WebvttParser` creates duplicate `CuesWithTiming` when handling cues sharing same start/end timestamps

### ISSUE THREAD

**Issue by JunkFood02** [androidx/media#1177] opened 2024-03-12 05:15 UTC
### Version

Media3 1.3.0

### More version details

media3-extractor

### Devices that reproduce the issue

Android Studio

### Reproducible in the demo app?

Not tested

### Reproduction steps

Use `WebvttParser.parse()` to parse the vtt captions below:
```
private const val vttSample = """WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:01.712
[MUSIC PLAYING]

00:00:02.533 --> 00:00:03.950
SPEAKER: As an
Android engineer, I

00:00:03.950 --> 00:00:06.350
have seen firsthand how
the ecosystem is growing--
"""
```

```kotlin
val cuesWithTimingList = buildList {
            WebvttParser().parse(
                vttSample.toByteArray(),
                SubtitleParser.OutputOptions.allCues()
            ) {
                add(it)
            }
        }
```

### Expected result

The `cuesWithTimingList` contains 3 items or lines

### Actual result

The list contains 4 items, see screenshot

<img width="896" alt="image" src="https://github.com/androidx/media/assets/69683722/2069bb1b-4ff1-4944-8958-547c2e27c009">

### Media

```
WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:01.712
[MUSIC PLAYING]

00:00:02.533 --> 00:00:03.950
SPEAKER: As an
Android engineer, I

00:00:03.950 --> 00:00:06.350
have seen firsthand how
the ecosystem is growing--
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2024-03-13 10:07
The duplication is expected for cues that **actually** overlap, that's checked in a test case here:
https://github.com/androidx/media/blob/12aa637fa1831b704f89377f16bf8da73ec5a264/libraries/extractor/src/test/java/androidx/media3/extractor/text/webvtt/WebvttParserTest.java#L338

This duplication is currently required due to the way we implement WebVTT's simultaneous cues handling (by creating synthetic `CuesWithTiming` objects representing the overlapping state) - which is mostly done inside `WebvttSubtitle`: https://github.com/androidx/media/blob/12aa637fa1831b704f89377f16bf8da73ec5a264/libraries/extractor/src/main/java/androidx/media3/extractor/text/webvtt/WebvttSubtitle.java#L81

If we didn't create these synthetic cues here, we would have lost too much information to correctly implement the layout rules later in the playback pipeline. It's still not perfect, and it would be better to implement this layout logic later, but it's not likely something we're going to change soon.

However, this duplication is **not expected** for consecutive cues where one cue ends at the same time the next cue starts. I can reproduce that the duplication does occur in this case, I'll look into fixing it.

**Comment by JunkFood02** [comment] 2024-03-13 11:03
Thanks for the quick and detailed response! Edited the title since I didn't intend to work with subtitles with overlapping timestamp

**Closed** 2024-03-15 14:57 UTC
Labels: bug, needs triage

**Comment by szaboa** [comment] 2024-04-02 13:32
@icbaker as I understood this was just a preparation to handle overlapping vtt cues?

> If we didn't create these synthetic cues here, we would have lost too much information to correctly implement the layout rules later in the playback pipeline. It's still not perfect (see e.g. https://github.com/google/ExoPlayer/issues/10980), and it would be better to implement this layout logic later, but it's not likely something we're going to change soon.

Do you have suggestions on the "layout logic"?
