### ISSUE TITLE
Add Support for HLS With ClearKey Encryption

### ISSUE THREAD

**Issue by iamatomic77** [androidx/media#1045] opened 2024-01-29 18:56 UTC
Can you add support for HLS with ClearKey encryption in ExoPlayer/Media3?

Here's an example of a HLS stream with ClearKey encryption (US Geoblocked):
**Stream Link:**
https://dfwlive-v1-c2p5-sponsored.akamaized.net/Content/HLS.cps/Live/channel(AMAXHD-4067.dfw.1080)/index.m3u8
**ClearKey Key:**
59c355414d0aae9388c00cc22b751c8c
**ClearKey Key ID:**
1470fffc6a2ddfcea6db98995691b79a

**Comment by icbaker** [comment] 2024-02-08 16:34
I had a look in the provided HLS manifest. I saw two `#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES` lines.

The first one seems to be related to FairPlay (based on the `KEYFORMAT="com.apple.streamingkeydelivery"`), so not relevant to Android playback:
```
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://1470fffc6a2ddfcea6db98995691b79a",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```

The second one seems to be widevine (based on `KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"`)

```
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgSEBRw//xqLd/OptuYmVaRt5pI88aJmwY=",KEYID=0X1470fffc6a2ddfcea6db98995691b79a,KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1"
```

In DASH, clearkey is included in the manifest: https://github.com/Dash-Industry-Forum/ClearKey-Content-Protection/blob/master/README.md#workflow

I was assuming that HLS clearkey content would also include some clearkey signalling in the playlist - but I don't see this in your example playlist. Please can you link to the spec that describes how clearkey content should be packaged in HLS?

---

I'm also curious **why** you want clearkey support? It's not a production-appropriate encryption/DRM scheme, since it's really inherently insecure.

**Comment by spotanjo3** [comment] 2024-03-14 21:25
The same thing with hallmark channel in mpd file through peacock US Live and there is a key too and it seems to run on VLC okay but a black screen and keep running without a key but with a key which I do have.. how do I added it to one link to make it run correctly ? An available all countries mpd clearkeys for restreaming live channels & restream pannels which can restream the live in real time with out any delay

Also available script for extracting all channels and vod mpd and keys for Peacock instantly & fully automatically. Is there a way I can run it properly on my VLC Player ?

**Comment by spotanjo3** [comment] 2024-03-18 20:40
Anybody ?

**Comment by Dragonball3** [comment] 2024-05-30 14:09
Other alternatives on how to play HLS + clearkey on Android? Seems restreaming is the only solution I know, but no idea on how to find free server with drmstuff installable.

**Comment by icbaker** [comment] 2024-12-13 16:56
To summarise my current understanding:

1. There is no published spec for how HLS playlists with ClearKey encryption should look.
2. It's possible to write a custom `HlsPlaylistParser` which makes some HLS streams work with ClearKey decryption with ExoPlayer:
    * https://github.com/androidx/media/issues/1496#issuecomment-2195812969
3. This custom parser doesn't work for other HLS playlists:
   * https://github.com/androidx/media/issues/1964

Since there is no published spec, it is not possible to say what the expected behaviour in case 3 is.

I'm going to close this as we have no plans to implement support for this while it remains undocumented and unspecified.

**Closed by icbaker** 2024-12-13 16:56 UTC
Labels: enhancement, needs triage
