### ISSUE TITLE
How to add subtitle when video is played

### ISSUE THREAD

**Issue by Hamamas** [androidx/media#774] opened 2023-10-27 14:17 UTC
**How can I add subtitles to an ExoPlayer video while it's playing?
What are the steps to dynamically add subtitles to an ExoPlayer when a video is already prepared?
Is it possible to load and display subtitles in ExoPlayer after the video has started playing?
How do I programmatically enable subtitle support in ExoPlayer during video playback?
What is the process for adding external subtitle tracks to an ExoPlayer instance after the video has started?
Can ExoPlayer load subtitles from different sources, such as local files or remote URLs, while a video is playing?
Are there any events or listeners I can use to trigger the addition of subtitles to a playing video in ExoPlayer?
How do I switch between multiple subtitle tracks in ExoPlayer during video playback?
What is the recommended way to handle subtitle formats and character encoding when adding subtitles to ExoPlayer while a video is playing?
Is there a specific API or method in ExoPlayer for adding subtitles to a video that is already prepared and playing?**

**Comment by icbaker** [comment] 2023-10-27 14:51
Duplicate of https://github.com/google/ExoPlayer/issues/1649

**Closed by icbaker** 2023-10-27 14:51 UTC
Labels: question, needs triage
