### ISSUE TITLE
How to set a playback error with media 3

### ISSUE THREAD

**Issue by Bwaim** [androidx/media#1077] opened 2024-02-08 16:23 UTC
I want to display a specific error message for my android auto app. Before media3, the error was managed like this ([see](https://developer.android.com/training/cars/media#errors)) :

```
mediaSession.setPlaybackState(
    PlaybackStateCompat.Builder()
        .setState(PlaybackStateCompat.STATE_ERROR)
        .setErrorMessage(PlaybackStateCompat.ERROR_CODE_NOT_AVAILABLE_IN_REGION, getString(R.string.error_unsupported_region))
        // ...and any other setters.
        .build())
```

How should we do this with media3 ?

**Comment by marcbaechinger** [comment] 2024-02-09 17:12
Duplicate of #543

**Closed** 2024-02-12 19:25 UTC
Labels: duplicate, enhancement
