### ISSUE TITLE
Is it possible with media3 to replace the MediaMetadataRetriever thumbnail extraction functionality? 

### ISSUE THREAD

**Issue by casolorz** [androidx/media#1067] opened 2024-02-04 20:10 UTC
My title basically explains what I need. I use `MediaMetadataRetriever` to get video thumbnails. Would it be possible to use all the new `media3` stuff to recreate the same functionality? 

Thanks.

**Comment by icbaker** [comment] 2024-02-07 18:24
Duplicate of https://github.com/google/ExoPlayer/issues/3609

**Closed by icbaker** 2024-02-07 18:24 UTC
Labels: question, needs triage
