### ISSUE TITLE
All Streams (Video and audio) works great on Media 1.3.0 (latest) except one mp3 Stream url.

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [androidx/media#1233] opened 2024-03-31 02:41 UTC
### Version

Media3 main branch

### More version details

 Media 1.3.0 (latest stable Release version) 

### Devices that reproduce the issue

Google Tv 4K (Chrome-Cast) Android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

1. use following url in assets folder:  https://shoutcast.glwiz.com/RadioYAR.mp3
2. I am not sure if I miss anything after upgrading the library to the most recent however I will see all Streams (Videos , Audios with any type supported are working great except above URL Streams which unfortunately can not be played

### Expected result

Since Mp3 format has been supported with this library (media3) and also this streams works great when using other libraries ie Web browsers or Vice  , it should be played when using it in demo apps with Media3 too.
  https://shoutcast.glwiz.com/RadioYAR.mp3

### Actual result

Not playing

### Media

 [](https://shoutcast.glwiz.com/RadioYAR.mp3)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment] 2024-04-03 18:16
Hi @pooya-mohammadhossein,

The issue is duplicate of https://github.com/google/ExoPlayer/issues/9851.

Please see the https://github.com/google/ExoPlayer/issues/9851#issuecomment-1009823571. Same stack trace is observable for the url provided above.

When I try a `curl` on the url, it gives the same error:

```
curl https://shoutcast.glwiz.com/RadioYAR.mp3
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by rohitjoins** [comment] 2024-04-04 10:27
Hi @pooya-mohammadhossein,

Media3 Library is new home for ExoPlayer library (which is now deprecated). Your issue sounds very similar to the one reported in this existing thread https://github.com/google/ExoPlayer/issues/9851. 

I also provided the output we get when I `curl` on the url above. As said before, I think the issue is with the URL and not with with Media3 Library itself.

Let us know if you don't agree with our observation and I'll be happy to re-open this ticket.

**Comment by rohitjoins** [comment] 2024-04-04 10:36
I have re-opened the ticket but I'm afraid we can help much on this issue. I can play other MP3 streams with Media3 without any issues. 

Irrespective of Media3 library, I believe doing a curl on the url shouldn't give `SSL certificate problem`. Media3 library is not able to fetch media from this URL and fails with network connection error.

**Comment by icbaker** [comment] 2024-04-04 12:05
@pooya-mohammadhossein This is not an issue with the media3 library. As @rohitjoins has explained (repeatedly) above, this is a configuration issue with the server. It's possible that VLC and some web browsers have less strict security than Android by default, I'm afraid I don't know the details of this - but suffice to say "it works in VLC" is not the same "this is a bug in media3".

Please read the [troubleshooting section on SSL errors](https://developer.android.com/media/media3/exoplayer/troubleshooting#fixing-sslhandshakeexception-certpathvalidatorexception-and-err_cert_authority_invalid-errors) and the Android SSL docs it links to - that may help resolve your issue. I'm afraid we are not in a position to offer further assistance on this tracker (since this is out of scope of the media3 library).

**Closed by icbaker** 2024-04-04 12:05 UTC
Labels: duplicate, bad media
