### ISSUE TITLE
SessionToken creation error: class MediaSessionCompat not found

### ISSUE THREAD

**Issue by davide99** [androidx/media#226] opened 2022-12-17 15:52 UTC
### Media3 Version

1.0.0-beta03

### Devices that reproduce the issue

* Samsung Galaxy A5 2017 (Android 8)

### Reproducible in the demo app?

No

### Reproduction steps

1. Follow the [official tutorial](https://developer.android.com/guide/topics/media/media3/getting-started/playing-in-background)
2. Override the `onStart` method to create a SessionToken with 
```java
SessionToken sessionToken = new SessionToken(
   this,
   new ComponentName(this, PlaybackService.class)
);
```
3. Build the app

### Expected result

The app should build normally

### Actual result

Build fails with:
```
        SessionToken sessionToken = new SessionToken(
                                    ^
  class file for android.support.v4.media.session.MediaSessionCompat not found
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment] 2022-12-19 20:56
Hi @davide99,

Have you tried to clear and rebuild your project on Android Studio? 

If the problem is still there after rebuilding, could you please attach your minimum reproducible sample project here or zipped up and sent it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by davide99** [comment] 2022-12-20 11:13
Yep, already tried to clear and rebuild.

This is a minimum reproducible sample [StegoRadioMinimal.zip](https://github.com/androidx/media/files/10267854/StegoRadioMinimal.zip).
Thank you

**Comment by icbaker** [comment] 2022-12-21 10:56
Thanks for reporting - after a bit of investigation it seems this:
1. Only reproduces in Java and not Kotlin, so our initial attempts to repro using our session demo (in Kotlin) app didn't work (thanks for the sample app, that helped)
2. Is due to `media3-session` depending on `androidx.media` (i.e. 'media1') as an `implementation` and not `api` dependency **and** there being two two-arg `SessionToken` constructors, one public (that doesn't use 'media1' types) and the other package-private (that does use 'media1' types) [1]. This **should** be OK (because we're not actually using media1 types in our public API) but it looks like this is an unfortunate interaction between gradle dependency management and `javac` behaviour when there are overloads with the same arity: https://stackoverflow.com/questions/65424898/gradle-implementation-dependency-isnt-compile-with-correct-code

By chance we've actually removed the 2-arg package-private constructor that uses the media1 type in https://github.com/androidx/media/commit/2fd4aac310787d1a57207b5142a0ab08d5e1a2a5 - so this problem is actually already fixed on the main branch - and the fix will be included in the next release.

For now you can work around this problem by adding the following line to the `deps` in your `build.gradle` file:

```
compileOnly 'androidx.media:media:1.6.0'
```

[1]
* [Public constructor](https://github.com/androidx/media/blob/1.0.0-beta03/libraries/session/src/main/java/androidx/media3/session/SessionToken.java#L104): `public SessionToken(Context context, ComponentName serviceComponent)`
* [Package-private](https://github.com/androidx/media/blob/1.0.0-beta03/libraries/session/src/main/java/androidx/media3/session/SessionToken.java#L146): `SessionToken(Context context, MediaSessionCompat.Token compatToken)`

**Closed by icbaker** 2022-12-21 10:56 UTC
Labels: bug, need more info, needs triage
