### ISSUE TITLE
Jetpack compose  , Hilt and coroutines example for the demo apps 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#238] opened 2023-01-02 04:23 UTC
Jetpack compose example for the demo apps 

Since the recommended way for future android is Kotlin with Jetpack compose, dagger hilt and coroutines, can you provide examples for media 3 using these .

**Comment by marcbaechinger** [comment] 2023-01-03 11:46
This is a duplicate of [#google/ExoPlayer/9654](https://github.com/google/ExoPlayer/issues/9654). Some users provided some resources on how to integrate with compose.  I'm closing this issue. Please comment in the other issue.

**Closed by marcbaechinger** 2023-01-03 11:46 UTC
Labels: question, needs triage
