### ISSUE TITLE
Add a method to resolve the shuffled position from the Timeline

### ISSUE THREAD

**Issue by tzugen** [androidx/media#343] opened 2023-04-20 11:45 UTC
Currently one has too loop through the Timeline, to figure out to which shuffle position an MediaItem at a given index resolves to:

```
    fun getCurrentShuffleIndex(): Int {
        val timeline = controller?.currentTimeline!!
        val currentMediaItemIndex = controller?.currentMediaItemIndex ?: return -1
        var windowIndex = timeline.getFirstWindowIndex(true)
        var count = 0
        while (windowIndex != C.INDEX_UNSET) {
            count++
            windowIndex = timeline.getNextWindowIndex(
                windowIndex, REPEAT_MODE_OFF,true
            )
            if (windowIndex == currentMediaItemIndex) return count
        }

        return -1
  }
```

It would be great if Timeline would have a method like getShuffledPositionOf(index: Int): Int as well as the reverse getUnshuffledPositionOf(shuffledIndex: Int)

**Comment by marcbaechinger** [comment] 2023-04-21 09:49
Drive-by comment: given your sample is in Kotlin, this looks like a candidate for a Kotlin extension?

**Comment by tonihei** [comment] 2023-04-27 11:24
This is essentially a duplicate of https://github.com/google/ExoPlayer/issues/5426.

More generically, there are two problems we want to solve:
 1. Add the concept of `PlaybackOrder` to the `Player` interface that allows you to access and modify the playback order, including for shuffle and repeat modes. While you can currently query the order, it's hard to set and configure. This is the main reason you are seeing https://github.com/androidx/media/issues/325. I'll rephrase that issue to track this general effort. 
 2. Make the `PlaybackOrder`/`ShuffleOrder` more flexible and provide easy access to information. The issue here is that we have multiple conflicting feature request: https://github.com/google/ExoPlayer/issues/5426 (get 1:1 mapping between shuffled/unshuffled order) and https://github.com/google/ExoPlayer/issues/6431 (make it easy to repeat elements in the shuffled order)

**Closed by tonihei** 2023-04-27 11:24 UTC
Labels: enhancement, needs triage
