### ISSUE TITLE
HLS + Clearkey with Custom HLS Parser

### ISSUE THREAD

**Issue by efkann** [androidx/media#1964] opened 2024-12-10 21:54 UTC
Hi,

I've been trying to play HLS + Clearkey streams for a while, following some issues opened in this repo.

I couldn't get past the `Media does not support uuid: e2719d58-a985-b3c9-781a-b030af78d30e` error.

Related: #1496

It was possible to play Clearkey DASH streams even though Clearkey wasn't signaled in the manifest by creating a custom DASH manifest parser and using it like:

```java
mediaSourceFactory = new DashMediaSource.Factory(dataSourceFactory)
                  .setManifestParser(new CustomDashManifestParser(defaultKeyIDs));
```

then, we could provide a license URL which contained keys in this format:

```json
{"keys": [{"k": "ABEiM0RVZneImaq7zN3u_w", "kty": "oct", "kid": "_u3wDe7erb7v8Lqt8A3QDQ"}], "type": "temporary"}
```

However, this doesnt seem like the case for Clearkey HLS streams or I'm probably doing something wrong.

```java
mediaSourceFactory = new HlsMediaSource.Factory(dataSourceFactory)
                    .setPlaylistParserFactory(new CustomDefaultHlsPlaylistParserFactory());
```

I'll add the relevant part of `CustomHlsPlaylistParser.java` which is the  `parseDrmSchemeData` method

```java
    private static SchemeData parseDrmSchemeData(
            String line, String keyFormat, Map<String, String> variableDefinitions)
            throws ParserException, JSONException {

        String keyFormatVersions =
                parseOptionalStringAttr(line, REGEX_KEYFORMATVERSIONS, "1", variableDefinitions);
        if (KEYFORMAT_WIDEVINE_PSSH_BINARY.equals(keyFormat)) {
            /* SOME_CODE_HERE_FOR_RETRIEVING_PROVIDED_DEFAULT_KEYIDS */
            UUID[] defaultKids = new UUID[providedDefaultKidStrings.length];
            for (int i = 0; i < providedDefaultKidStrings.length; i++) {
                defaultKids[i] = UUID.fromString(providedDefaultKidStrings[i]);
            }
            byte[] psshData = PsshAtomUtil.buildPsshAtom(C.COMMON_PSSH_UUID, defaultKids, null);

            return new SchemeData(C.COMMON_PSSH_UUID, MimeTypes.VIDEO_MP4, psshData);
        }
       /* MORE_CODE_HERE */ 
}
```

So even if the player recognizes only Widevine, by providing default keyids we also want to make it recognize this as a Clearkey stream.

However this didn't work and showed this error:

```
Media does not support uuid: e2719d58-a985-b3c9-781a-b030af78d30e
```

Are there additional steps need to be done inside CustomHlsPlaylistParser to make this work or is this not doable at all ?

Stream URL to test (Clearkey isn't signaled in the HLS playlist but should be possible by providing default keyids):
```
https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8
```

Raw key ids and keys:
```
4d97930a3d7b55fa81d0028653f5e499:429ec76475e7a952d224d8ef867f12b6
d21373c0b8ab5ba9954742bcdfb5f48b:150a6c7d7dee6a91b74dccfce5b31928
6f1729072b4a5cd288c916e11846b89e:a84b4bd66901874556093454c075e2c6
800aacaa522958ae888062b5695db6bf:775dbf7289c4cc5847becd571f536ff2
67b30c86756f57c5a0a38a23ac8c9178:efa2878c2ccf6dd47ab349fcf90e6259
```

Or as a license URL, you can use the URL below:

```
https://clearkeys.deno.dev/?keys=4d97930a3d7b55fa81d0028653f5e499:429ec76475e7a952d224d8ef867f12b6,d21373c0b8ab5ba9954742bcdfb5f48b:150a6c7d7dee6a91b74dccfce5b31928,6f1729072b4a5cd288c916e11846b89e:a84b4bd66901874556093454c075e2c6,800aacaa522958ae888062b5695db6bf:775dbf7289c4cc5847becd571f536ff2,67b30c86756f57c5a0a38a23ac8c9178:efa2878c2ccf6dd47ab349fcf90e6259
```
which should return the keys in the `k, kty, kid` format

I'd really appreciate your help !

**Comment by efkann** [comment] 2024-12-13 03:10
I believe this issue might occur due to `#EXT-X-DISCONTINUITY`. Just removed the tag manually and stream started working.

**Comment by efkann** [comment] 2024-12-13 15:31
I've extracted 480P playlist from the official Shaka demo stream asset below:

https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8


Uploaded to Github, so you can test them as well.


With the `EXT-X-DISCONTINUITY` tag (Original version) :

https://gist.githubusercontent.com/efkann/4ce3d60b29edf67b31a6e7fd75e6ecf9/raw/65f98e1feab91994940f013894a03c5ef9b0ee3c/with-discontinuity.m3u8

Works with Widevine `https://cwip-shaka-proxy.appspot.com/no_auth`
Doesn't work with keys `800aacaa522958ae888062b5695db6bf:775dbf7289c4cc5847becd571f536ff2`



Without the `EXT-X-DISCONTINUITY` tag `EXT-X-KEY` placed at the top (Modified version) :
https://gist.githubusercontent.com/efkann/375e8e9a1680548c665544bbbf3462b9/raw/6f8efae4bcf8aba349d26110e53a73dda51a3fc7/without-discontinuity-x-key-at-the-top.m3u8

Works with Widevine `https://cwip-shaka-proxy.appspot.com/no_auth`
Also works with the keys `800aacaa522958ae888062b5695db6bf:775dbf7289c4cc5847becd571f536ff2`

**Comment by efkann** [comment] 2024-12-13 16:45
As I tested other streams, I found that HLS + Clearkey works with the custom parser I shared above. 

However, Shaka's demo stream with the `EXT-X-DISCONTINUITY` tag doesn't work unless the tag is manually removed. I'm not sure if this is a bug or if it's supposed to work this way. Feel free to close the issue if this is by design."

**Comment by icbaker** [comment] 2024-12-13 16:57
Thanks - I'm going to close this following the same reasoning I just posted in https://github.com/androidx/media/issues/1045#issuecomment-2541862780 - without a spec it's impossible to answer questions about whether this is "working as intended" or not.

**Closed by icbaker** 2024-12-13 16:57 UTC
Labels: question, needs triage
