### ISSUE TITLE
Casting crashes app

### ISSUE THREAD

**Issue by JonathanMasonProtostream** [androidx/media#866] opened 2023-12-06 16:49 UTC
### Version

ExoPlayer 2.19.1

### Devices that reproduce the issue

Sony Xperia Phone XQ-BC52 running Android 11 casting to Sony 43” TV, Bravia 4K VH2, KD-43X80J running Android 10

### Reproducible in the demo app?

Yes

### Reproduction steps

Using demo-cast app with following added to line 184 of its MainActivity.java to work around problem where RecyclerView remains blank:

`playerManager.addItem(DemoUtil.SAMPLES.get(5)); // Workaround to automatically play dizzy.mp4.`

To reproduce:

1. Running demo-cast app on phone, press round Plus (+) button to bottom-right of app.
2. Press OK when message box appears - dizzy.mp4 should display.
3. Press Play button of video player.
4. Press Cast button on right of tool bar above video player.
5. Cast message box should display with available TVs.
6. Press TV to cast to.
7. On phone, video stops playing and app abruptly seems to go into background and then reloads, perhaps a crash. On TV, video briefly plays but then whatever app is playing it disappears.

### Expected result

When casting, on phone, video continues playing and and app does not crash. On TV, video plays and continues to play.

### Actual result

When casting, on phone, video stops playing and app abruptly seems to go into background and then reloads, perhaps a crash. On TV, video briefly plays but then whatever app is playing it disappears.

### Media

https://html5demos.com/assets/dizzy.mp4

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by JonathanMasonProtostream** [comment] 2023-12-06 17:55
The problem was introduced by commit 1d082ee9 of the ExoPlayer2 repository, which removed a casting workaround and moved to a newer version of the Google casting framework:

https://github.com/google/ExoPlayer/commit/1d082ee9

**Comment by JonathanMasonProtostream** [comment] 2023-12-06 18:09
Attached video of problem happening using modified demo-cast app:

https://github.com/androidx/media/assets/101563176/268edd34-30ae-4fe6-90bd-063faf6f9112

**Comment by tonihei** [comment] 2023-12-06 18:11
@JonathanMasonProtostream  Thanks for filing the report, when you are saying that the issue was introduced by https://github.com/google/ExoPlayer/commit/1d082ee9 - do you mean changing the Cast SDK version or removing the workaround? You can try out the previous code state with the workaround and manually added `implementation 'com.google.android.gms:play-services-cast-framework:21.2.0'` in your Gradle setup to combine the fix with the new Cast SDK to check. 

And is it reproducing on all devices you tested on or only on the specified TVs? I'm wondering whether I can just test this with another TV or whether it's bound to the ones you mentioned.

**Comment by JonathanMasonProtostream** [comment] 2023-12-07 09:52
Thank you for looking into this so quickly @tonihei.

I've emailed the bug report to android-media-github@google.com and attached 'logcat.txt' here.
[Logcat.txt](https://github.com/androidx/media/files/13598413/Logcat.txt)

It does not happen for all devices.

**Comment by tonihei** [comment] 2023-12-13 13:54
The logs don't seem to contain much useful information I'm afraid, for example I can't find any of the crashes. 

In any case, if the issue is clearly caused by upgrading the Cast SDK dependency to 21.2.0, then I suggest you can file a bug here for the Cast SDK itself: https://issuetracker.google.com/issues?q=status:open%20componentid:190205

**Comment by JonathanMasonProtostream** [comment] 2023-12-18 14:13
Reported against Cast SDK:
https://issuetracker.google.com/issues/316844809

**Comment by tonihei** [comment] 2024-03-11 09:47
Closing this issue here because it's outside of our control.

**Closed by tonihei** 2024-03-11 09:47 UTC
Labels: bug: in dependency
