### ISSUE TITLE
Encountering ERROR_CODE_AUDIO_TRACK_INIT_FAILED Error when Playing Music with media3-exoplayer

### ISSUE THREAD

**Issue by XthPasserby** [androidx/media#748] opened 2023-10-20 05:43 UTC
Hi, we encountered the ERROR_CODE_AUDIO_TRACK_INIT_FAILED error when playing local music from the sdcard using media3 on an Android 11 pad. This issue occurs when we switch between songs, usually after playing for a period of time. The problem persists until restarting the device. We are using version androidx.media3:media3-exoplayer:1.1.1. Below is the error log:

```
10-10 10:28:19.781   296  6772 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000008) and output flags (00000000)
10-10 10:28:19.781   296  6772 D AudioFlinger: Client defaulted notificationFrames to 16537 for frameCount 33075
10-10 10:28:19.781   296  6772 E AF::TrackBase: TrackBase(1023): not enough memory for AudioTrack size=262368
10-10 10:28:19.781   296  6772 D MemoryDealer:   AudioTrack (0xf1d8f7b0, size=4194304)
10-10 10:28:19.781   296  6772 D MemoryDealer:     0: 0xf1d8e710 | 0x00000000 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     1: 0xf1d92ef0 | 0x000400E0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     2: 0xf1d924d0 | 0x000801C0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     3: 0xf1d92ed0 | 0x000C02A0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     4: 0xf1d918d0 | 0x00100380 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     5: 0xf1d91b90 | 0x00140460 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     6: 0xf1d8fb90 | 0x00180540 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     7: 0xf1d91d10 | 0x001C0620 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     8: 0xf1d8dfb0 | 0x00200700 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:     9: 0xf1d90690 | 0x002407E0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    10: 0xf1d91eb0 | 0x002808C0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    11: 0xf1d914b0 | 0x002C09A0 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    12: 0xf1d93650 | 0x00300A80 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    13: 0xf1d92cf0 | 0x00340B60 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    14: 0xf1d8f510 | 0x00380C40 | 0x000400E0 | A 
10-10 10:28:19.781   296  6772 D MemoryDealer:    15: 0xf1d919b0 | 0x003C0D20 | 0x0003F2E0 | F 
10-10 10:28:19.781   296  6772 D MemoryDealer:   size allocated: 3935520 (3843 KB)
10-10 10:28:19.784   296  6772 D AF::TrackHandle: OpPlayAudio: track:1023 usage:1 not muted
10-10 10:28:19.786   296  6772 E AudioFlinger: createTrack_l() initCheck failed -12; no control block?
10-10 10:28:19.787 24684 24787 E IAudioFlinger: createTrack returned error -12
10-10 10:28:19.787 24684 24787 E AudioTrack: createTrack_l(7471204): AudioFlinger could not create track, status: -12 output 0
10-10 10:28:19.787 24684 24787 E AudioTrack-JNI: Error -12 initializing AudioTrack
10-10 10:28:19.787 24684 24787 D AudioTrack: gather(): no metrics gathered, track status=-12
10-10 10:28:19.787 24684 24787 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer: Audio sink error
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:   androidx.media3.exoplayer.audio.AudioSink$b: AudioTrack init failed 0 Config(44100, 12, 132300) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0, null], [2, 44100])
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:7)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.J(DefaultAudioSink.java:2)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.K(DefaultAudioSink.java:1)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.T(DefaultAudioSink.java:2)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.v(DefaultAudioSink.java:17)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at io.X0(MediaCodecAudioRenderer.java:7)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at pq.l0(MediaCodecRenderer.java:32)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at pq.s(MediaCodecRenderer.java:16)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.o(ExoPlayerImplInternal.java:15)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:26)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at android.os.Looper.loop(Looper.java:223)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:   Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at android.media.AudioTrack$Builder.build(AudioTrack.java:1279)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.f(DefaultAudioSink.java:11)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.d(DefaultAudioSink.java:2)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:1)
10-10 10:28:19.789 24684 24787 E MediaCodecAudioRenderer:       ... 12 more
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal: Playback error
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:   dk: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0, null], [2, 44100]), format_supported=YES
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:44)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.audio.AudioSink$b: AudioTrack init failed 0 Config(44100, 12, 132300) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0, null], [2, 44100])
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:7)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink.J(DefaultAudioSink.java:2)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink.K(DefaultAudioSink.java:1)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink.T(DefaultAudioSink.java:2)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink.v(DefaultAudioSink.java:17)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at io.X0(MediaCodecAudioRenderer.java:7)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at pq.l0(MediaCodecRenderer.java:32)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at pq.s(MediaCodecRenderer.java:16)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.o(ExoPlayerImplInternal.java:15)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:26)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       ... 3 more
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       Suppressed: androidx.media3.exoplayer.audio.AudioSink$b: AudioTrack init failed 0 Config(44100, 12, 132300) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0, null], [2, 44100])
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           ... 13 more
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           at android.media.AudioTrack$Builder.build(AudioTrack.java:1279)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.f(DefaultAudioSink.java:11)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.d(DefaultAudioSink.java:2)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:1)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:           ... 12 more
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:   Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at android.media.AudioTrack$Builder.build(AudioTrack.java:1279)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.f(DefaultAudioSink.java:11)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.d(DefaultAudioSink.java:2)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:1)
10-10 10:28:19.792 24684 24787 E ExoPlayerImplInternal:       ... 12 more
10-10 10:28:19.793 24684 24796 D CCodecBuffers: [c2.android.mp3.decoder#237:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
10-10 10:28:19.793 24684 24796 D CCodecBuffers: [c2.android.mp3.decoder#237:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
10-10 10:28:19.793 24684 24796 D CCodecBuffers: [c2.android.mp3.decoder#237:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
10-10 10:28:19.794 24684 24796 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
10-10 10:28:19.794 24684 24796 W Codec2Client: query -- param skipped: index = 1342179345.
10-10 10:28:19.794 24684 24796 W Codec2Client: query -- param skipped: index = 2415921170.
10-10 10:28:19.796 24684 24796 D CCodecBufferChannel: [c2.android.mp3.decoder#237] MediaCodec discarded an unknown buffer
10-10 10:28:19.797 24684 24796 I chatty  : uid=1000(system) com.smartos.xinch.setting identical 2 lines
10-10 10:28:19.797 24684 24796 D CCodecBufferChannel: [c2.android.mp3.decoder#237] MediaCodec discarded an unknown buffer
10-10 10:28:19.799 24684 24796 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
10-10 10:28:19.799   375   403 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
10-10 10:28:19.831 24684 24684 D MusicPlayer: audioDisabled [eventTime=3191.00, mediaPos=0.00, window=1, period=1]
10-10 10:28:19.832 24684 24684 D MusicPlayer: audioDecoderReleased [eventTime=3191.00, mediaPos=0.00, window=1, period=1, c2.android.mp3.decoder]
10-10 10:28:19.833 24684 24684 D MusicPlayer: timeline [eventTime=3191.01, mediaPos=0.00, window=1, period=1, periodCount=7, windowCount=7, reason=SOURCE_UPDATE
10-10 10:28:19.833 24684 24684 D MusicPlayer:   period [?]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   period [236.38]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   period [?]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   ...
10-10 10:28:19.834 24684 24684 D MusicPlayer:   window [?, seekable=false, dynamic=true]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   window [236.38, seekable=true, dynamic=false]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   window [?, seekable=false, dynamic=true]
10-10 10:28:19.834 24684 24684 D MusicPlayer:   ...
10-10 10:28:19.834 24684 24684 D MusicPlayer: ]
10-10 10:28:19.837 24684 24684 E MusicPlayer: playerFailed [eventTime=3191.01, mediaPos=0.00, window=1, period=1, errorCode=ERROR_CODE_AUDIO_TRACK_INIT_FAILED
10-10 10:28:19.837 24684 24684 E MusicPlayer:   dk: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0, null], [2, 44100]), format_supported=YES
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:44)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at android.os.Looper.loop(Looper.java:223)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-10 10:28:19.837 24684 24684 E MusicPlayer:   Caused by: androidx.media3.exoplayer.audio.AudioSink$b: AudioTrack init failed 0 Config(44100, 12, 132300) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0, null], [2, 44100])
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:7)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.J(DefaultAudioSink.java:2)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.K(DefaultAudioSink.java:1)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.T(DefaultAudioSink.java:2)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.v(DefaultAudioSink.java:17)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at io.X0(MediaCodecAudioRenderer.java:7)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at pq.l0(MediaCodecRenderer.java:32)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at pq.s(MediaCodecRenderer.java:16)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.o(ExoPlayerImplInternal.java:15)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:26)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       ... 3 more
10-10 10:28:19.837 24684 24684 E MusicPlayer:       Suppressed: androidx.media3.exoplayer.audio.AudioSink$b: AudioTrack init failed 0 Config(44100, 12, 132300) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0, null], [2, 44100])
10-10 10:28:19.837 24684 24684 E MusicPlayer:           ... 13 more
10-10 10:28:19.837 24684 24684 E MusicPlayer:       Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
10-10 10:28:19.837 24684 24684 E MusicPlayer:           at android.media.AudioTrack$Builder.build(AudioTrack.java:1279)
10-10 10:28:19.837 24684 24684 E MusicPlayer:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.f(DefaultAudioSink.java:11)
10-10 10:28:19.837 24684 24684 E MusicPlayer:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.d(DefaultAudioSink.java:2)
10-10 10:28:19.837 24684 24684 E MusicPlayer:           at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:1)
10-10 10:28:19.837 24684 24684 E MusicPlayer:           ... 12 more
10-10 10:28:19.837 24684 24684 E MusicPlayer:   Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at android.media.AudioTrack$Builder.build(AudioTrack.java:1279)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.f(DefaultAudioSink.java:11)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.d(DefaultAudioSink.java:2)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       at androidx.media3.exoplayer.audio.DefaultAudioSink$f.a(DefaultAudioSink.java:1)
10-10 10:28:19.837 24684 24684 E MusicPlayer:       ... 12 more
10-10 10:28:19.837 24684 24684 E MusicPlayer: ]
```

According to the log, it seems like ExoPlayer has a memory leak when using AudioTrack.
We implemented the local music player following the example at https://github.com/android/uamp/tree/compose

**Comment by tonihei** [comment] 2023-10-20 09:34
The logs seem to indicate that there is not enough memory to instantiate a new `AudioTrack` (` E AF::TrackBase: TrackBase(1023): not enough memory for AudioTrack size=262368`).

I'm not sure about your integration, but could it be that you are not releasing `Player` instances after using them for example?

**Comment by XthPasserby** [comment] 2023-10-23 01:49
I only created one ExoPlayer instance, and used it along with MediaLibraryService to provide music playback services. The UI interface uses MediaBrowser to control playback. In most cases, there were no abnormalities. The only exception is that occasionally this error would appear when connecting to a Bluetooth speaker for playback.
Some of the playback code is as follows:

```
class MusicService: MediaLibraryService() {
    private val exoPlayer: ExoPlayer by lazy {
        val player = ExoPlayer.Builder(this).setWakeMode(C.WAKE_MODE_LOCAL).build().apply {
            setAudioAttributes(customAudioAttributesBuilder.build(), true)
            setHandleAudioBecomingNoisy(true)
            addListener(playerListener)
        }
        player.addAnalyticsListener(EventLogger("MusicPlayer"))
        player
    }

    override fun onDestroy() {
        super.onDestroy()
        releaseMediaSession()
    }

    private fun releaseMediaSession() {
        mediaSession.run {
            release()
            if (player.playbackState != Player.STATE_IDLE) {
                player.removeListener(playerListener)
                player.release()
            }
        }
        // Cancel coroutines when the service is going away.
        serviceJob.cancel()
    }
}

class MusicServiceConnection {

    val player: Player? get() = browser
    private var browser: MediaBrowser? = null

    init {
        scope.launch {
            val newBrowser =
                MediaBrowser.Builder(context, SessionToken(context, serviceComponent))
                    .setListener(BrowserListener())
                    .buildAsync()
                    .await()
            newBrowser.addListener(playerListener)
            newBrowser.repeatMode = REPEAT_MODE_ALL
            browser = newBrowser
        }
    }
}

class MusicViewModel: ViewModel() {
    private val musicServiceConnection: MusicServiceConnection by lazy {
        InjectorUtils.provideMusicServiceConnection(MicroContext.getApplication())
    }

    fun playAll() {
        val player = musicServiceConnection.player ?: return

        viewModelScope.launch {
            val songs = songList.value ?: emptyList()
            val playlist: MutableList<MediaItem> = songs.map { it.toMedia() }.toMutableList()
            player.setMediaItems(
                playlist, 0, C.TIME_UNSET
            )
            player.prepare()
            player.play()
        }
    }
}
```

MusicServiceConnection is a singleton implementation.

**Comment by tonihei** [comment] 2023-12-11 16:24
The only suspicious part of your setup is `if (player.playbackState != Player.STATE_IDLE) { player.release() }` because the player should always be released, no matter which state it is in. Maybe that helps already, otherwise I don't think I can help you further unless you have very concrete reproduction steps that would let me reproduce the issue myself.

**Comment by tonihei** [comment] 2024-03-11 09:44
Closing because no need information was provided

**Closed by tonihei** 2024-03-11 09:44 UTC
Labels: question
