### ISSUE TITLE
Incorrect currentPosition fetched for mp3 file 

### ISSUE THREAD

**Issue by angry010101** [androidx/media#878] opened 2023-12-08 08:58 UTC
### Version

Media3 1.2.0

### Devices that reproduce the issue

Pixel 6

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play https://www.ivoox.com/como-trabajar-la-profundidad-en-amway-2016_mf_13394401_feed_1.mp3
2. Fast forward to 39.36 
3. Wait 15 seconds 
4. You should see currentPosition > duration in remaining column after 8 seconds 
 
 

### Expected result

Playback should stop when currentPosition = duration

### Actual result

Playback continues after currentPosition = duration

### Media

Audio content:

https://www.ivoox.com/como-trabajar-la-profundidad-en-amway-2016_mf_13394401_feed_1.mp3

Video with a bug reproduced on Exoplayer demo app and media3 1.2.0:

[exobug.webm](https://github.com/androidx/media/assets/24439691/946c363d-68f1-440f-b2a2-3ef00162692c)

You can see the timeline at the end of the content doesn't match duration 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment] 2023-12-13 17:33
I can reproduce what you see of the position exceeding the duration after seeking near the end of the stream.

The provided stream is constant bitrate (CBR) with an `Info` header (the CBR version of the VBR `Xing` header). This header provides some information about how to resolve a time position to a byte offset in the file, to allow starting to read the file at the right offset when seeking to a new position. Unfortunatley the format of the Info/Xing header is extremely imprecise, which leads to inaccurate seeks - with the inaccuracy being more pronounced in longer files (see also https://github.com/google/ExoPlayer/issues/7767#issuecomment-677760688). Each individual MP3 sample doesn't contain any timing information, so there's no way to correct this inaccuracy once the seek is complete.

ExoPlayer uses a Xing/Info header if it's present, but also supports seeking in CBR MP3 files **without** these headers by simply knowing that every sample is the same size. I hacked `Mp3Extractor` to use constant bitrate seeking on your file (instead of the Info data) and it resolved the issue (playback stops at 39:44, it doesn't overrun). Unfortunately it's not currently possible to configure this behaviour (ignore Info header and use constant bitrate seeking) on `Mp3Extractor` without making changes to the library.

I will discuss with the team about whether we should either automatically use constant bitrate seeking when we see an `Info` header (since I believe this indicates a CBR file), or at least allow apps to request constant bitrate seeking in this case using `@Mp3Extractor.Flags` values.

**Comment by icbaker** [comment] 2024-01-25 09:46
The commits above change ExoPlayer's behaviour to use CBR-seeking if the file contains an `Info` frame - this should result in more accurate seeking than relying on the table of contents in the `Info` frame. These changes will be part of 1.3.0-beta01.

This has no effect on seeking accuracy on VBR MP3s with only an `Xing` header - but there's nothing better we can do for these files, there is fundamentally not enough information in the file to seek accurately without indexing it from the beginning (which is already possible using [`FLAG_ENABLE_INDEX_SEEKING`](https://developer.android.com/reference/androidx/media3/extractor/mp3/Mp3Extractor#FLAG_ENABLE_INDEX_SEEKING())).

**Closed by icbaker** 2024-01-25 09:46 UTC
Labels: bug
